-- FAKKIR seed — part 3 of 9. Generated; do not edit by hand.
-- Run server/sql/schema.sql once, then paste these part files into the Supabase SQL Editor in order (01, 02, ...).
begin;

-- Categories (idempotent; required by the questions foreign key)
insert into categories(slug,name,color,image,sort_order) values
('geo','الجغرافيا','blue','assets/img/categories/geo.png',0),
('history','التاريخ','gold','assets/img/categories/history.png',1),
('palestine','فلسطين','green','assets/img/categories/palestine.png',2),
('seerah','السيرة النبوية','teal','assets/img/categories/seerah.png',3),
('quran','القرآن الكريم','green','assets/img/categories/quran.png',4),
('flags','أعلام الدول','red','assets/img/categories/flags.png',5),
('sports','الرياضة','cyan','assets/img/categories/sports.png',6),
('football','كرة القدم','blue','assets/img/categories/football.png',7),
('riddles','الألغاز','purple','assets/img/categories/riddles.png',8),
('science','العلوم','teal','assets/img/categories/science.png',9),
('tech','التكنولوجيا','cyan','assets/img/categories/tech.png',10),
('animals','عالم الحيوان','gold','assets/img/categories/animals.png',11),
('general','المعلومات العامة','gold','assets/img/categories/general.png',12),
('math','الرياضيات والأرقام','blue','assets/img/categories/math.png',13),
('whoami','احزر ماذا أنا','purple','assets/img/categories/whoami.png',14),
('proverbs','تكملة المثل','teal','assets/img/categories/proverbs.png',15),
('dish','ما هي الأكلة','red','assets/img/categories/dish.png',16),
('crime','الجريمة','red','assets/img/categories/crime.png',17),
('rescue','إنقاذ المتهم','green','assets/img/categories/rescue.png',18),
('closest','الأقرب إلى الرقم','purple','assets/img/categories/closest.png',19),
('capitals','عواصم الدول','blue','assets/img/categories/capitals.png',20),
('currencies','عملات الدول','gold','assets/img/categories/currencies.png',21),
('verse','أكمل الآية','green','assets/img/categories/verse.png',22),
('ordering','الترتيب الصحيح','cyan','assets/img/categories/ordering.png',23)
on conflict(slug) do update set name=excluded.name,color=excluded.color,image=excluded.image,sort_order=excluded.sort_order;

-- Questions 501..750
insert into questions(category,version,ord,value,type,q,a,note,flag,clues,num,evidence,suspects) values
('quran',9,2,400,'normal','كم عدد الآيات في سورة البقرة؟','286 آية',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',9,3,400,'normal','ما هو معنى "المد المنفصل"؟','أن يكون حرف المد في نهاية كلمة والهمزة في بداية الكلمة التي تليها',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',9,4,600,'normal','ما هي السورة التي ذكر فيها "الخنساء"؟','لا توجد سورة بهذا الاسم',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',9,5,600,'normal','ما معنى "المحكم" في القرآن؟','الآيات الواضحة الدلالة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',10,0,200,'normal','ما اسم الغار الذي نزل فيه القرآن لأول مرة؟','غار حراء',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',10,1,200,'normal','ما هو اسم السورة التي تتحدث عن قصة أصحاب الكهف؟','سورة الكهف',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',10,2,400,'normal','ما هي السورة التي تتحدث عن قصة قارون؟','سورة القصص',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',10,3,400,'normal','ما هي السورة التي تسمى "سورة الحديد"؟','سورة الحديد',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',10,4,600,'normal','ما هي السورة التي بدأت بـ "طه"؟','سورة طه',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',10,5,600,'normal','كم عدد آيات سورة الإخلاص؟','4 آيات',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',11,0,200,'normal','ما هي السورة التي تسمى "سورة النساء الصغرى"؟','سورة الطلاق',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',11,1,200,'normal','ما هي السورة التي ذكرت فيها قصة يوسف عليه السلام؟','سورة يوسف',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',11,2,400,'normal','ما هو عدد مرات ذكر الجنة في القرآن؟','حوالي 138 مرة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',11,3,400,'normal','ما هي السورة التي تتحدث عن الغاشية؟','سورة الغاشية',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',11,4,600,'normal','ما هي السورة التي تسمى "سورة الحجرات"؟','سورة الحجرات',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',11,5,600,'normal','ما هو الفرق بين "القرآن" و"الحديث القدسي"؟','القرآن معجز بلفظه ومعناه، الحديث القدسي معناه من الله ولفظه من النبي',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',12,0,200,'normal','كم عدد آيات سورة الفاتحة؟','7 آيات',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',12,1,200,'normal','ما هي الآية التي تعتبر أعظم آية في القرآن؟','آية الكرسي',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',12,2,400,'normal','ما اسم الصحابي الذي كان يكتب الوحي للرسول؟','زيد بن ثابت وآخرون',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',12,3,400,'normal','ما هي السورة التي يطلق عليها "سورة النساء"؟','سورة النساء',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',12,4,600,'normal','ما هي السورة التي ذكرت فيها "قصة ذبح البقرة"؟','سورة البقرة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',12,5,600,'normal','من هو القارئ الملقب بـ "شيخ المقارئ المصرية"؟','سؤال عام، يوجد عدة شخصيات مثل محمود خليل الحصري',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',13,0,200,'normal','ما معنى كلمة "القرآن" لغةً؟','القراءة أو الجمع',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',13,1,200,'normal','هل القرآن محفوظ من التحريف؟','نعم (إنا نحن نزلنا الذكر وإنا له لحافظون)',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',13,2,400,'normal','ما معنى "الناسخ والمنسوخ" في القرآن؟','أن تأتي آية ترفع حكم آية سابقة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',13,3,400,'normal','ما هي السورة التي تسمى "القلم"؟','سورة القلم',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',13,4,600,'normal','ما هي السورة التي تسمى "الفرقان"؟','سورة الفرقان',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',13,5,600,'normal','ما هو حكم الميم الساكنة إذا جاء بعدها "باء"؟','الإخفاء الشفوي',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',14,0,200,'normal','من هو الصحابي الذي جمع القرآن في عهد أبي بكر؟','زيد بن ثابت',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',14,1,200,'normal','ما هي السورة التي تسمى "سورة الملك"؟','سورة تبارك',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',14,2,400,'normal','ما هي السورة التي بدأت بـ "عم يتساءلون"؟','سورة النبأ',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',14,3,400,'normal','ما هي السورة التي تتحدث عن القمر؟','سورة القمر',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',14,4,600,'normal','ما هي السورة التي تسمى "الواقعة"؟','سورة الواقعة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',14,5,600,'normal','كم عدد السور التي تنتهي بـ "الله"؟','لا توجد',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',15,0,200,'normal','ما اسم السورة التي تتحدث عن النمل؟','سورة النمل',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',15,1,200,'normal','ما هي السورة التي تتحدث عن النحل؟','سورة النحل',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',15,2,400,'normal','كم عدد آيات الكرسي؟','آية واحدة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',15,3,400,'normal','ما هو "تجويد" القرآن؟','إعطاء كل حرف حقه ومستحقه في النطق',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',15,4,600,'normal','ما هي السورة التي ذكر فيها "أصحاب الأخدود"؟','سورة البروج',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',15,5,600,'normal','ما هو "التفخيم والترقيق" في الحروف؟','صفات الحروف من حيث السمن والنحول',NULL,NULL,NULL,NULL,NULL,NULL),
('flags',1,0,200,'flag',NULL,'السعودية',NULL,'sa',NULL,NULL,NULL,NULL),
('flags',1,1,200,'flag',NULL,'مصر',NULL,'eg',NULL,NULL,NULL,NULL),
('flags',1,2,400,'flag',NULL,'جنوب أفريقيا',NULL,'za',NULL,NULL,NULL,NULL),
('flags',1,3,400,'flag',NULL,'كوريا الجنوبية',NULL,'kr',NULL,NULL,NULL,NULL),
('flags',1,4,600,'flag',NULL,'بوتان',NULL,'bt',NULL,NULL,NULL,NULL),
('flags',1,5,600,'flag',NULL,'نيبال',NULL,'np',NULL,NULL,NULL,NULL),
('flags',2,0,200,'flag',NULL,'الإمارات',NULL,'ae',NULL,NULL,NULL,NULL),
('flags',2,1,200,'flag',NULL,'فلسطين',NULL,'ps',NULL,NULL,NULL,NULL),
('flags',2,2,400,'flag',NULL,'بلجيكا',NULL,'be',NULL,NULL,NULL,NULL),
('flags',2,3,400,'flag',NULL,'السويد',NULL,'se',NULL,NULL,NULL,NULL),
('flags',2,4,600,'flag',NULL,'كازاخستان',NULL,'kz',NULL,NULL,NULL,NULL),
('flags',2,5,600,'flag',NULL,'أوزبكستان',NULL,'uz',NULL,NULL,NULL,NULL),
('flags',3,0,200,'flag',NULL,'لبنان',NULL,'lb',NULL,NULL,NULL,NULL),
('flags',3,1,200,'flag',NULL,'المغرب',NULL,'ma',NULL,NULL,NULL,NULL),
('flags',3,2,400,'flag',NULL,'النرويج',NULL,'no',NULL,NULL,NULL,NULL),
('flags',3,3,400,'flag',NULL,'النمسا',NULL,'at',NULL,NULL,NULL,NULL),
('flags',3,4,600,'flag',NULL,'قرغيزستان',NULL,'kg',NULL,NULL,NULL,NULL),
('flags',3,5,600,'flag',NULL,'طاجيكستان',NULL,'tj',NULL,NULL,NULL,NULL),
('flags',4,0,200,'flag',NULL,'قطر',NULL,'qa',NULL,NULL,NULL,NULL),
('flags',4,1,200,'flag',NULL,'الكويت',NULL,'kw',NULL,NULL,NULL,NULL),
('flags',4,2,400,'flag',NULL,'الدنمارك',NULL,'dk',NULL,NULL,NULL,NULL),
('flags',4,3,400,'flag',NULL,'بولندا',NULL,'pl',NULL,NULL,NULL,NULL),
('flags',4,4,600,'flag',NULL,'تركمانستان',NULL,'tm',NULL,NULL,NULL,NULL),
('flags',4,5,600,'flag',NULL,'أذربيجان',NULL,'az',NULL,NULL,NULL,NULL),
('flags',5,0,200,'flag',NULL,'الجزائر',NULL,'dz',NULL,NULL,NULL,NULL),
('flags',5,1,200,'flag',NULL,'تونس',NULL,'tn',NULL,NULL,NULL,NULL),
('flags',5,2,400,'flag',NULL,'التشيك',NULL,'cz',NULL,NULL,NULL,NULL),
('flags',5,3,400,'flag',NULL,'المجر',NULL,'hu',NULL,NULL,NULL,NULL),
('flags',5,4,600,'flag',NULL,'جورجيا',NULL,'ge',NULL,NULL,NULL,NULL),
('flags',5,5,600,'flag',NULL,'أرمينيا',NULL,'am',NULL,NULL,NULL,NULL),
('flags',6,0,200,'flag',NULL,'الولايات المتحدة',NULL,'us',NULL,NULL,NULL,NULL),
('flags',6,1,200,'flag',NULL,'بريطانيا',NULL,'gb',NULL,NULL,NULL,NULL),
('flags',6,2,400,'flag',NULL,'كولومبيا',NULL,'co',NULL,NULL,NULL,NULL),
('flags',6,3,400,'flag',NULL,'تشيلي',NULL,'cl',NULL,NULL,NULL,NULL),
('flags',6,4,600,'flag',NULL,'إستونيا',NULL,'ee',NULL,NULL,NULL,NULL),
('flags',6,5,600,'flag',NULL,'لاتفيا',NULL,'lv',NULL,NULL,NULL,NULL),
('flags',7,0,200,'flag',NULL,'فرنسا',NULL,'fr',NULL,NULL,NULL,NULL),
('flags',7,1,200,'flag',NULL,'ألمانيا',NULL,'de',NULL,NULL,NULL,NULL),
('flags',7,2,400,'flag',NULL,'المكسيك',NULL,'mx',NULL,NULL,NULL,NULL),
('flags',7,3,400,'flag',NULL,'فيتنام',NULL,'vn',NULL,NULL,NULL,NULL),
('flags',7,4,600,'flag',NULL,'ليتوانيا',NULL,'lt',NULL,NULL,NULL,NULL),
('flags',7,5,600,'flag',NULL,'فنلندا',NULL,'fi',NULL,NULL,NULL,NULL),
('flags',8,0,200,'flag',NULL,'إيطاليا',NULL,'it',NULL,NULL,NULL,NULL),
('flags',8,1,200,'flag',NULL,'إسبانيا',NULL,'es',NULL,NULL,NULL,NULL),
('flags',8,2,400,'flag',NULL,'ماليزيا',NULL,'my',NULL,NULL,NULL,NULL),
('flags',8,3,400,'flag',NULL,'إندونيسيا',NULL,'id',NULL,NULL,NULL,NULL),
('flags',8,4,600,'flag',NULL,'أيسلندا',NULL,'is',NULL,NULL,NULL,NULL),
('flags',8,5,600,'flag',NULL,'أيرلندا',NULL,'ie',NULL,NULL,NULL,NULL),
('flags',9,0,200,'flag',NULL,'البرازيل',NULL,'br',NULL,NULL,NULL,NULL),
('flags',9,1,200,'flag',NULL,'الأرجنتين',NULL,'ar',NULL,NULL,NULL,NULL),
('flags',9,2,400,'flag',NULL,'سنغافورة',NULL,'sg',NULL,NULL,NULL,NULL),
('flags',9,3,400,'flag',NULL,'تايلاند',NULL,'th',NULL,NULL,NULL,NULL),
('flags',9,4,600,'flag',NULL,'كرواتيا',NULL,'hr',NULL,NULL,NULL,NULL),
('flags',9,5,600,'flag',NULL,'صربيا',NULL,'rs',NULL,NULL,NULL,NULL),
('flags',10,0,200,'flag',NULL,'اليابان',NULL,'jp',NULL,NULL,NULL,NULL),
('flags',10,1,200,'flag',NULL,'الصين',NULL,'cn',NULL,NULL,NULL,NULL),
('flags',10,2,400,'flag',NULL,'الفلبين',NULL,'ph',NULL,NULL,NULL,NULL),
('flags',10,3,400,'flag',NULL,'إيران',NULL,'ir',NULL,NULL,NULL,NULL),
('flags',10,4,600,'flag',NULL,'سلوفينيا',NULL,'si',NULL,NULL,NULL,NULL),
('flags',10,5,600,'flag',NULL,'سلوفاكيا',NULL,'sk',NULL,NULL,NULL,NULL),
('flags',11,0,200,'flag',NULL,'كندا',NULL,'ca',NULL,NULL,NULL,NULL),
('flags',11,1,200,'flag',NULL,'تركيا',NULL,'tr',NULL,NULL,NULL,NULL),
('flags',11,2,400,'flag',NULL,'العراق',NULL,'iq',NULL,NULL,NULL,NULL),
('flags',11,3,400,'flag',NULL,'الأردن',NULL,'jo',NULL,NULL,NULL,NULL),
('flags',11,4,600,'flag',NULL,'بلغاريا',NULL,'bg',NULL,NULL,NULL,NULL),
('flags',11,5,600,'flag',NULL,'رومانيا',NULL,'ro',NULL,NULL,NULL,NULL),
('flags',12,0,200,'flag',NULL,'روسيا',NULL,'ru',NULL,NULL,NULL,NULL),
('flags',12,1,200,'flag',NULL,'الهند',NULL,'in',NULL,NULL,NULL,NULL),
('flags',12,2,400,'flag',NULL,'سلطنة عمان',NULL,'om',NULL,NULL,NULL,NULL),
('flags',12,3,400,'flag',NULL,'اليمن',NULL,'ye',NULL,NULL,NULL,NULL),
('flags',12,4,600,'flag',NULL,'مولدوفا',NULL,'md',NULL,NULL,NULL,NULL),
('flags',12,5,600,'flag',NULL,'بيلاروسيا',NULL,'by',NULL,NULL,NULL,NULL),
('flags',13,0,200,'flag',NULL,'أستراليا',NULL,'au',NULL,NULL,NULL,NULL),
('flags',13,1,200,'flag',NULL,'المكسيك',NULL,'mx',NULL,NULL,NULL,NULL),
('flags',13,2,400,'flag',NULL,'ليبيا',NULL,'ly',NULL,NULL,NULL,NULL),
('flags',13,3,400,'flag',NULL,'السودان',NULL,'sd',NULL,NULL,NULL,NULL),
('flags',13,4,600,'flag',NULL,'أوكرانيا',NULL,'ua',NULL,NULL,NULL,NULL),
('flags',13,5,600,'flag',NULL,'مدغشقر',NULL,'mg',NULL,NULL,NULL,NULL),
('flags',14,0,200,'flag',NULL,'هولندا',NULL,'nl',NULL,NULL,NULL,NULL),
('flags',14,1,200,'flag',NULL,'البرتغال',NULL,'pt',NULL,NULL,NULL,NULL),
('flags',14,2,400,'flag',NULL,'موريتانيا',NULL,'mr',NULL,NULL,NULL,NULL),
('flags',14,3,400,'flag',NULL,'نيجيريا',NULL,'ng',NULL,NULL,NULL,NULL),
('flags',14,4,600,'flag',NULL,'موريشيوس',NULL,'mu',NULL,NULL,NULL,NULL),
('flags',14,5,600,'flag',NULL,'سيشل',NULL,'sc',NULL,NULL,NULL,NULL),
('flags',15,0,200,'flag',NULL,'اليونان',NULL,'gr',NULL,NULL,NULL,NULL),
('flags',15,1,200,'flag',NULL,'سويسرا',NULL,'ch',NULL,NULL,NULL,NULL),
('flags',15,2,400,'flag',NULL,'كينيا',NULL,'ke',NULL,NULL,NULL,NULL),
('flags',15,3,400,'flag',NULL,'غانا',NULL,'gh',NULL,NULL,NULL,NULL),
('flags',15,4,600,'flag',NULL,'جامايكا',NULL,'jm',NULL,NULL,NULL,NULL),
('flags',15,5,600,'flag',NULL,'باراغواي',NULL,'py',NULL,NULL,NULL,NULL),
('sports',1,0,200,'normal','ما هي الرياضة الأكثر شعبية في العالم؟','كرة القدم',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',1,1,200,'normal','كم عدد اللاعبين في فريق كرة السلة على الملعب؟','5 لاعبين',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',1,2,400,'normal','ما هو اللقب الذي يطلق على الفائزين ببطولة "تور دي فرانس"؟','بطل الدراجات الهوائية',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',1,3,400,'normal','في أي رياضة يُستخدم مصطلح "Checkmate" (كش ملك)؟','الشطرنج',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',1,4,600,'normal','ما هو الـ "Decathlon" في ألعاب القوى؟','مسابقة تضم 10 فعاليات رياضية مختلفة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',1,5,600,'normal','ما هو اسم الرياضة التي تعتبر "الرياضة الوطنية" في اليابان؟','السومو',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',2,0,200,'normal','ما هي الرياضة التي تُمارس باستخدام المضرب والكرة الصفراء الصغيرة؟','التنس',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',2,1,200,'normal','في أي رياضة يُستخدم "الخاتم" أو "الحلبة"؟','الملاكمة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',2,2,400,'normal','ما هي الرياضة التي تتضمن رمي "القرص" أو "الرمح" أو "الجلة"؟','ألعاب القوى (الميدان)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',2,3,400,'normal','كم عدد الميداليات المتاحة في سباق واحد في الأولمبياد؟','3 (ذهبية، فضية، برونزية)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',2,4,600,'normal','كم عدد القطع على رقعة الشطرنج في بداية المباراة؟','32 قطعة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',2,5,600,'normal','ما هي الرياضة التي تُمارس في الملاعب الرملية وتستخدم كرة صغيرة وتعرف بـ "كرة الطائرة الشاطئية"؟','سؤال مباشر، لكن القوانين تختلف',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',3,0,200,'normal','ما هي المسافة التي يركضها العداء في سباق الماراثون؟','42.195 كيلومتر',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',3,1,200,'normal','ما اسم الرياضة التي تعتمد على السباحة، الدراجات، والجري؟','الترايثلون',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',3,2,400,'normal','ما هو "التايكوندو"؟','رياضة قتالية كورية تعتمد على الركلات',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',3,3,400,'normal','في أي رياضة يُستخدم مصطلح "Birdie" و"Eagle"؟','الغولف',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',3,4,600,'normal','في أي عام بدأت الألعاب الأولمبية الحديثة؟','1896',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',3,5,600,'normal','ما هو "البياتلون" (Biathlon)؟','رياضة تجمع بين التزلج الريفي والرماية',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',4,0,200,'normal','كم عدد الأشواط في مباراة التنس؟','لا يوجد نظام أشواط، بل مجموعات (Sets)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',4,1,200,'normal','ما هي الرياضة التي يرتدي فيها اللاعبون قفازات بيسبول؟','البيسبول',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',4,2,400,'normal','ما هي الرياضة التي تُعرف بـ "فن القتال الياباني" وتعتمد على الرمي والتحكم؟','الجودو',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',4,3,400,'normal','ما هو الدوري الأمريكي للمحترفين في كرة السلة؟','NBA',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',4,4,600,'normal','ما اسم الرياضة التي تُمارس في الجبال وتتضمن تسلق الصخور؟','تسلق الجبال',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',4,5,600,'normal','كم عدد اللاعبين في كل فريق في رياضة "الكيرلنج"؟','4 لاعبين',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',5,0,200,'normal','ما هو "الهدف" في رياضة كرة السلة؟','إدخال الكرة في السلة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',5,1,200,'normal','ما اسم الرياضة التي يستخدم فيها اللاعبون "عصا" و"قرصاً" على الجليد؟','هوكي الجليد',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',5,2,400,'normal','كم مرة تقام الألعاب الأولمبية الصيفية؟','كل 4 سنوات',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',5,3,400,'normal','ما هو الوزن الذي يتم فيه تحديد الفائز في "رفع الأثقال"؟','مجموع الأوزان المرفوعة (الخطف والنتر)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',5,4,600,'normal','ما هي "بطولة ويمبلدون"؟','أقدم وأعرق بطولة في التنس',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',5,5,600,'normal','ماذا يعني مصطلح "Par" في الغولف؟','عدد الضربات المثالي لإتمام الحفرة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',6,0,200,'normal','ما هي الرياضة التي تتضمن "الإرسال" و"الاستقبال" و"الضرب الساحق"؟','الكرة الطائرة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',6,1,200,'normal','ما اسم البطولة الكبرى في كرة المضرب (التنس) التي تقام على ملاعب ترابية؟','رولان غاروس',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',6,2,400,'normal','ما هي الرياضة التي يتم فيها استخدام "المجداف" لتحريك القارب؟','التجديف',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',6,3,400,'normal','ما اسم الرياضة التي تستخدم "اللوح" للتزلج على الأمواج؟','ركوب الأمواج (Surfing)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',6,4,600,'normal','ما هي الرياضة التي تتضمن "التزلج السريع"؟','التزلج على الجليد (Short/Long Track)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',6,5,600,'normal','ما اسم أعلى جائزة في رياضة الملاكمة؟','حزام البطولة العالمية (WBC, WBA, إلخ)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',7,0,200,'normal','كم عدد لاعبي فريق كرة اليد في الملعب؟','7 لاعبين',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',7,1,200,'normal','ما هي الرياضة التي يمارسها "السباحون"؟','السباحة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',7,2,400,'normal','في أي رياضة يُستخدم مصطلح "Touchdown"؟','كرة القدم الأمريكية',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',7,3,400,'normal','ما هي الرياضة التي تعتمد على "الكاراتيه" و"الكونغ فو" و"التايكوندو" كمصطلحات عامة؟','الفنون القتالية',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',7,4,600,'normal','ما هي رياضة "الباليتو"؟','سؤال فخ: لا توجد رياضة بهذا الاسم',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',7,5,600,'normal','ما هو "الخماسي الحديث" (Modern Pentathlon)؟','رياضة تتضمن 5 فعاليات: المبارزة، السباحة، الفروسية، الرماية، والجري',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',8,0,200,'normal','ما اسم الرياضة التي تعتمد على القتال بالسيوف؟','المبارزة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',8,1,200,'normal','ما هي أسرع رياضة في العالم من حيث سرعة الكرة؟','الريشة الطائرة (Badminton)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',8,2,400,'normal','ما اسم أكبر حدث رياضي في العالم؟','الألعاب الأولمبية',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',8,3,400,'normal','في أي رياضة يُستخدم "القفاز" و"الكرة الثقيلة" و"المضرب الخشبي"؟','الكريكيت',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',8,4,600,'normal','ما هي الدولة التي تمتلك أكبر عدد من الميداليات في تاريخ الأولمبياد؟','الولايات المتحدة الأمريكية',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',8,5,600,'normal','كم يبلغ طول ملعب كرة اليد؟','40 متراً',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',9,0,200,'normal','ما هي الرياضة التي تستخدم فيها "الكرات الحديدية" والهدف هو رميها بالقرب من كرة صغيرة؟','البوتشي (أو الكرة الحديدية)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',9,1,200,'normal','ما هو اسم الرياضة التي تقفز فيها فوق "حاجز"؟','ألعاب القوى (سباق الحواجز)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',9,2,400,'normal','ما هي الرياضة التي تتضمن القفز فوق "عارضة" عالية؟','الوثب العالي',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',9,3,400,'normal','كم عدد الفرق التي تشارك في بطولة الدوري الاميركي للمحترفين (NBA)؟','30 فريقاً',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',9,4,600,'normal','ما هي رياضة "اللاكروس" (Lacrosse)؟','رياضة فريق تستخدم عصا ذات شبكة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',9,5,600,'normal','ما هو "الرالي" (Rally)؟','سباق سيارات طويل على طرق متنوعة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',10,0,200,'normal','كم عدد أعمدة المرمى في كرة القدم؟','اثنان',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',10,1,200,'normal','ما هي الرياضة التي تتطلب التوازن على عارضة خشبية؟','الجمباز',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',10,2,400,'normal','ما هو الفرق بين "الجمباز الفني" و"الجمباز الإيقاعي"؟','الفني يستخدم الأجهزة (العارضة)، الإيقاعي يستخدم الأدوات (الشريط، الكرة)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',10,3,400,'normal','ما هي الرياضة التي تُمارس على "حلبة جليدية" بفرشاة خاصة؟','الكيرلنج (Curling)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',10,4,600,'normal','ما هي الرياضة التي تتضمن "رمي القرص" لأطول مسافة؟','قذف القرص',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',10,5,600,'normal','ما هو الفرق بين "الجمباز" و"الجمباز الإيقاعي" في الأولمبياد؟','نوع المسابقات والمعدات',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',11,0,200,'normal','ما اسم الرياضة التي تُمارس على الخيول؟','الفروسية',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',11,1,200,'normal','ما هي الرياضة التي يرتدي فيها المتسابقون ملابس واقية ويقودون سيارات سريعة؟','الفورمولا 1',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',11,2,400,'normal','ما هو مصطلح "Grand Slam" في التنس؟','الفوز بالبطولات الأربع الكبرى في عام واحد',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',11,3,400,'normal','في أي رياضة تُستخدم "السكيت" (Skate)؟','التزلج على الجليد أو الرولر',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',11,4,600,'normal','في أي رياضة يُستخدم "القفاز الثقيل" والهدف هو "ضرب الخصم"؟','الملاكمة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',11,5,600,'normal','ما هي الدولة التي اخترعت رياضة "السومو"؟','اليابان',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',12,0,200,'normal','كم عدد جولات الملاكمة في المباريات الاحترافية الكبرى؟','12 جولة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',12,1,200,'normal','ما هي الرياضة التي تستخدم فيها "القوس والسهم"؟','الرماية',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',12,2,400,'normal','ما هي الرياضة التي تتضمن الغوص بدون أجهزة تنفس؟','الغوص الحر (Free Diving)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',12,3,400,'normal','ما هو "ماراثون"؟','سباق طويل للمسافات',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',12,4,600,'normal','ما هو "الهاتريك" في كرة القدم؟','تسجيل 3 أهداف في مباراة واحدة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',12,5,600,'normal','كم يبلغ ارتفاع حلقة كرة السلة عن الأرض؟','3.05 متراً',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',13,0,200,'normal','ما هي الرياضة التي تُمارس في ملعب عشبي بمضارب خشبية أو معدنية وتتضمن ثقوباً في الأرض؟','الغولف',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',13,1,200,'normal','ما هو اسم الرياضة التي تتضمن القفز في الماء؟','الغطس',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',13,2,400,'normal','ما هي رياضة "السكواش"؟','رياضة مضرب تُلعب في غرفة مغلقة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',13,3,400,'normal','ما هو الفرق بين "الرجبي" و"كرة القدم الأمريكية"؟','اختلاف قوانين اللعب وتجهيزات الحماية',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',13,4,600,'normal','ما هي الرياضة التي تُلعب على "عشب صناعي" وتستخدم كرة صغيرة وعصا منحنية؟','الهوكي الميداني',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',13,5,600,'normal','ما هو "الوثب الثلاثي"؟','قفزة تتكون من ثلاث مراحل: الحجلة، الخطوة، والوثبة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',14,0,200,'normal','ما هي الرياضة التي يستخدم فيها المتسابقون "الزلاجات"؟','التزلج',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',14,1,200,'normal','كم عدد أعضاء فريق الرجبي (Rugby Union) في الملعب؟','15 لاعباً',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',14,2,400,'normal','ما هي الرياضة التي تستخدم "الخيوط" و"الأسلاك" للارتفاع في الهواء؟','القفز بالحبال (Bungee Jumping)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',14,3,400,'normal','ما اسم الرياضة التي تُمارس باستخدام "المظلات"؟','القفز المظلي',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',14,4,600,'normal','ما هي الدولة التي استضافت أول أولمبياد شتوي؟','فرنسا (شاموني 1924)',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',14,5,600,'normal','ما هو مصطلح "Knockout" (KO) في القتال؟','إسقاط الخصم وعدم قدرته على النهوض',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',15,0,200,'normal','ما اسم الرياضة التي يستخدم فيها "الكرات الخشبية" و"الدبابيس"؟','البولينج',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',15,1,200,'normal','ما هو العضو الذي لا يُسمح للاعبي كرة القدم (باستثناء الحارس) باستخدامه؟','اليد',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',15,2,400,'normal','كم يستغرق وقت مباراة الهوكي على الجليد؟','3 أشواط مدة كل منها 20 دقيقة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',15,3,400,'normal','ما هي رياضة "الكيك بوكسينج"؟','مزيج بين الملاكمة والركل',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',15,4,600,'normal','ما هي رياضة "الرماية بالبندقية"؟','رماية دقيقة على أهداف ثابتة',NULL,NULL,NULL,NULL,NULL,NULL),
('sports',15,5,600,'normal','ما هو أطول سباق في الأولمبياد؟','الماراثون (أو سباق 50 كم مشي)',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',1,0,200,'normal','ما هو الشيء الذي يكتب ولا يقرأ؟','القلم',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',1,1,200,'normal','ما هو الشيء الذي له أسنان ولا يعض؟','المشط',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',1,2,400,'normal','ما هو الشيء الذي له عينان ولا يرى، وله أرجل ولا يمشي؟','الجوارب',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',1,3,400,'normal','ابن أمك وابن أبيك، وليس بأختك ولا بأخيك، فمن يكون؟','أنت',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',1,4,600,'normal','رجل حكم عليه بالإعدام، وخُيّر بين ثلاث غرف: الأولى بها نار مشتعلة، والثانية بها قتلة مسلحون، والثالثة بها أسود لم تأكل منذ 3 سنوات، فأي غرفة يختار؟','الثالثة، الأسود ماتت',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',1,5,600,'normal','ما هو الشيء الذي إذا لمسته صرخ؟','الجرس',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',2,0,200,'normal','ما هو الشيء الذي يقرصك ولا تراه؟','الجوع',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',2,1,200,'normal','ما هو الشيء الذي يمشي بلا أرجل ويدخل الأذن ولا يسمع؟','الصوت',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',2,2,400,'normal','ما هو الشيء الذي يملك مدناً بلا بيوت، وجبالاً بلا أشجار، وبحاراً بلا ماء؟','الخريطة',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',2,3,400,'normal','ما هو الشيء الذي يمكنه ملء الغرفة دون أن يشغل حيزاً؟','الضوء',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',2,4,600,'normal','أنا لست حياً، ولكنني أنمو؛ ليس لدي رئتان، ولكنني أحتاج إلى الهواء؛ ليس لدي فم، ولكن الماء يقتلني. فمن أنا؟','النار',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',2,5,600,'normal','أنا ملكٌ بلا عرش، أملك مفاتيحاً لا تفتح الأبواب، وأملك مساحاتٍ شاسعة ولكن لا توجد بيوتٌ لأعيش فيها، ومع ذلك يطوف الناس حولي في كل مكان. فمن أنا؟','الخريطة',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',3,0,200,'normal','ما هو الشيء الذي كلما أخذت منه كبر؟','الحفرة',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',3,1,200,'normal','ما هو الشيء الذي يوجد في وسط باريس؟','حرف الراء',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',3,2,400,'normal','ما هو الشيء الذي يمتلك الكثير من المفاتيح لكنه لا يفتح باباً؟','البيانو',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',3,3,400,'normal','أخت خالك وليست خالتك، فمن تكون؟','أمك',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',3,4,600,'normal','شخص كان عمره 4 سنوات وأخته نصف عمره، والآن هو عمره 100 سنة، كم عمر أخته؟','98 سنة',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',3,5,600,'normal','أنا موجودٌ أمامك دائماً ولكنك لا تراني، أرافقك منذ لحظة ولادتك، وإذا سألتني عن مستقبلك فسأعطيك إجاباتٍ غامضة، وإذا حاولت اللحاق بي سأهرب منك دائماً. فمن أنا؟','المستقبل',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',4,0,200,'normal','ما هو الشيء الذي يملك عيناً واحدة ولا يرى؟','الإبرة',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',4,1,200,'normal','ما هو الشيء الذي إذا غليته جمد؟','البيض',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',4,2,400,'normal','ما هو الشيء الذي يمتلك مدناً وقرى ولكن لا يملك بشراً؟','الخريطة',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',4,3,400,'normal','ما هو الشيء الذي يمر عبر الزجاج ولا يكسره؟','الضوء',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',4,4,600,'normal','ما هو الشيء الذي إذا وضعته في الغسالة يختفي؟','الصابون',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',4,5,600,'normal','رجل لديه 4 بنات، وكل ابنة لديها أخ واحد، كم عدد أبنائه؟','5',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',5,0,200,'normal','ما هو الشيء الذي يوصلك من بيتك إلى عملك دون أن يتحرك؟','الطريق',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',5,1,200,'normal','أنا بداية النهاية ونهاية الزمان والمكان، فمن أنا؟','حرف النون',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',5,2,400,'normal','أملك مفاتيح ولكن لا أفتح أبواباً، أملك مساحة ولكن لا أملك غرفاً، يمكنك الدخول ولكن لا يمكنك الخروج، فمن أنا؟','لوحة مفاتيح الحاسوب',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',5,3,400,'normal','ما هو الشيء الذي يمتلك أوراقاً وليس شجرة، ويحمل فصولاً وليس عاماً؟','الكتاب',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',5,4,600,'normal','شخصٌ يسير في صحراء قاحلة، وجد في طريقه حقيبةً مغلقة، وعندما فتحها وجد بداخلها شيئاً لو لم يلمسه لكان مجهولاً، ولو وجده لكان محظوظاً، ولو فقد حياته بسببه لما عرف قيمته. فماذا كان في الحقيبة؟','خارطة طريق',NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',5,5,600,'normal','ما هو الشيء الذي يتكون من حرفين فقط، ومع ذلك يزن أطناناً؟','لا يوجد',NULL,NULL,NULL,NULL,NULL,NULL)
on conflict(category,version,ord) do update set value=excluded.value,type=excluded.type,q=excluded.q,a=excluded.a,note=excluded.note,flag=excluded.flag,clues=excluded.clues,num=excluded.num,evidence=excluded.evidence,suspects=excluded.suspects;

commit;
