-- FAKKIR seed — part 2 of 9. Generated; do not edit by hand.
-- Run server/sql/schema.sql once, then paste these part files into the Supabase SQL Editor in order (01, 02, ...).
begin;

-- Categories (idempotent; required by the questions foreign key)
insert into categories(slug,name,color,image,sort_order) values
('geo','الجغرافيا','blue','assets/img/categories/geo.png',0),
('history','التاريخ','gold','assets/img/categories/history.png',1),
('palestine','فلسطين','green','assets/img/categories/palestine.png',2),
('seerah','السيرة النبوية','teal','assets/img/categories/seerah.png',3),
('quran','القرآن الكريم','green','assets/img/categories/quran.png',4),
('flags','أعلام الدول','red','assets/img/categories/flags.png',5),
('sports','الرياضة','cyan','assets/img/categories/sports.png',6),
('football','كرة القدم','blue','assets/img/categories/football.png',7),
('riddles','الألغاز','purple','assets/img/categories/riddles.png',8),
('science','العلوم','teal','assets/img/categories/science.png',9),
('tech','التكنولوجيا','cyan','assets/img/categories/tech.png',10),
('animals','عالم الحيوان','gold','assets/img/categories/animals.png',11),
('general','المعلومات العامة','gold','assets/img/categories/general.png',12),
('math','الرياضيات والأرقام','blue','assets/img/categories/math.png',13),
('whoami','احزر ماذا أنا','purple','assets/img/categories/whoami.png',14),
('proverbs','تكملة المثل','teal','assets/img/categories/proverbs.png',15),
('dish','ما هي الأكلة','red','assets/img/categories/dish.png',16),
('crime','الجريمة','red','assets/img/categories/crime.png',17),
('rescue','إنقاذ المتهم','green','assets/img/categories/rescue.png',18),
('closest','الأقرب إلى الرقم','purple','assets/img/categories/closest.png',19),
('capitals','عواصم الدول','blue','assets/img/categories/capitals.png',20),
('currencies','عملات الدول','gold','assets/img/categories/currencies.png',21),
('verse','أكمل الآية','green','assets/img/categories/verse.png',22),
('ordering','الترتيب الصحيح','cyan','assets/img/categories/ordering.png',23)
on conflict(slug) do update set name=excluded.name,color=excluded.color,image=excluded.image,sort_order=excluded.sort_order;

-- Questions 251..500
insert into questions(category,version,ord,value,type,q,a,note,flag,clues,num,evidence,suspects) values
('history',12,4,600,'normal','ما هي الدولة التي كانت تسمى "أرض الشمس المشرقة" تاريخياً؟','اليابان',NULL,NULL,NULL,NULL,NULL,NULL),
('history',12,5,600,'normal','من هو المكتشف الذي وصل إلى الهند بحراً؟','فاسكو دا غاما',NULL,NULL,NULL,NULL,NULL,NULL),
('history',13,0,200,'normal','ما هو اسم الكتاب المقدس عند اليهود؟','التوراة',NULL,NULL,NULL,NULL,NULL,NULL),
('history',13,1,200,'normal','متى بدأت الحرب العالمية الأولى؟','1914',NULL,NULL,NULL,NULL,NULL,NULL),
('history',13,2,400,'normal','ما هو التاريخ الذي يرمز لقيام الأمم المتحدة؟','1945',NULL,NULL,NULL,NULL,NULL,NULL),
('history',13,3,400,'normal','من هو العالم الذي اكتشف الجاذبية الكونية؟','نيوتن',NULL,NULL,NULL,NULL,NULL,NULL),
('history',13,4,600,'normal','ما هي "القرون الوسطى"؟','الفترة بين سقوط روما وعصر النهضة',NULL,NULL,NULL,NULL,NULL,NULL),
('history',13,5,600,'normal','من هو الملك الذي وقع "إعلان الاستقلال" الأمريكي؟','كان بتوقيع ممثلي المستعمرات (جون هانكوك كان أولهم)',NULL,NULL,NULL,NULL,NULL,NULL),
('history',14,0,200,'normal','من هو الإسكندر الأكبر؟','ملك مقدوني غزا معظم العالم القديم',NULL,NULL,NULL,NULL,NULL,NULL),
('history',14,1,200,'normal','ما هي أقدم مدينة مأهولة في العالم؟','دمشق (أو أريحا)',NULL,NULL,NULL,NULL,NULL,NULL),
('history',14,2,400,'normal','ما هي الدولة التي كانت تسيطر على معظم العالم في العصور القديمة؟','روما',NULL,NULL,NULL,NULL,NULL,NULL),
('history',14,3,400,'normal','من هو القائد الذي عبر جبال الألب بالأفيال؟','حنبعل',NULL,NULL,NULL,NULL,NULL,NULL),
('history',14,4,600,'normal','ما هي المعركة التي انتهت فيها القوة العثمانية في البحر؟','معركة ليبانتو',NULL,NULL,NULL,NULL,NULL,NULL),
('history',14,5,600,'normal','من هو مخترع نظام "بريل" للمكفوفين؟','لويس بريل',NULL,NULL,NULL,NULL,NULL,NULL),
('history',15,0,200,'normal','من هو الشخص الذي صعد للقمر لأول مرة؟','نيل أرمسترونج',NULL,NULL,NULL,NULL,NULL,NULL),
('history',15,1,200,'normal','ما هي الدولة التي كانت تسمى بلاد فارس؟','إيران',NULL,NULL,NULL,NULL,NULL,NULL),
('history',15,2,400,'normal','ما هي الحرب التي عرفت بحرب الـ 100 عام؟','حرب بين إنجلترا وفرنسا',NULL,NULL,NULL,NULL,NULL,NULL),
('history',15,3,400,'normal','من هو مكتشف جزيرة أستراليا؟','جيمس كوك',NULL,NULL,NULL,NULL,NULL,NULL),
('history',15,4,600,'normal','ما هي "ثورة البوكسر"؟','ثورة ضد النفوذ الأجنبي في الصين',NULL,NULL,NULL,NULL,NULL,NULL),
('history',15,5,600,'normal','من هو الحاكم الذي بنى مدينة تدمر؟','زنوبيا (كحاكمة للمدينة)',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',1,0,200,'normal','ما هي عاصمة فلسطين التاريخية والروحية؟','القدس',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',1,1,200,'normal','ما هو البحر الذي يحد فلسطين من الغرب؟','البحر الأبيض المتوسط',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',1,2,400,'normal','ما هي المعاهدة التي قسمت فلسطين عام 1947؟','قرار التقسيم رقم 181',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',1,3,400,'normal','متى تأسست جامعة بيرزيت؟','عام 1924 (كنواة لمدرسة)',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',1,4,600,'normal','ما هي الدولة التي كانت تسيطر على فلسطين قبل الانتداب البريطاني؟','الدولة العثمانية',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',1,5,600,'normal','من هو المهندس الفلسطيني الذي صمم العديد من المباني في القدس؟','بولس شحادة (مثال)',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',2,0,200,'normal','ما هي المدينة التي تُعرف بـ "مدينة السلام"؟','القدس',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',2,1,200,'normal','في أي قارة تقع فلسطين؟','قارة آسيا',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',2,2,400,'normal','من هو القائد الفلسطيني الذي قاد ثورة 1936؟','عز الدين القسام (نظم الثورة قبل استشهاده)',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',2,3,400,'normal','ما هي المدينة التي تضم "كنيسة المهد"؟','بيت لحم',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',2,4,600,'normal','ما هو العام الذي أصدرت فيه بريطانيا "وعد بلفور"؟','1917',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',2,5,600,'normal','ما هو الكتاب الذي أرخ فيه وليد الخالدي للقرى الفلسطينية المدمرة؟','كي لا ننسى"',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',3,0,200,'normal','ما هو المسجد الواقع في قلب القدس وتُحيط به الساحات؟','المسجد الأقصى',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',3,1,200,'normal','ما هو أشهر أنواع الزيتون في فلسطين؟','الزيتون النبالي',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',3,2,400,'normal','ماذا تعني كلمة "يافا"؟','الجميلة',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',3,3,400,'normal','في أي عام احتلت القوات الإسرائيلية الضفة الغربية وقطاع غزة؟','1967 (النكسة)',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',3,4,600,'normal','في أي معركة استشهد القائد عبد القادر الحسيني؟','معركة القسطل',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',3,5,600,'normal','ما هي المدينة التي كان مقر "المندوب السامي" البريطاني فيها؟','القدس',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',4,0,200,'normal','ما هي المدينة التي تشتهر بكونها أقدم مدينة في العالم؟','أريحا',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',4,1,200,'normal','بماذا يُلقب الشعب الفلسطيني نظراً لصموده؟','شعب الجبارين',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',4,2,400,'normal','من هو الكاتب الفلسطيني الذي كتب "رجال في الشمس"؟','غسان كنفاني',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',4,3,400,'normal','ما هي المدينة التي تضم ميناء غزة القديم؟','غزة',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',4,4,600,'normal','ما هو اسم الصحيفة التي صدرت في يافا عام 1911 وكانت من أوائل الصحف؟','فلسطين',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',4,5,600,'normal','من هو القائد الفلسطيني الذي قاد "ثورة 1936-1939" وأطلق عليه "شيخ المجاهدين"؟','أمين الحسيني (مفتي القدس)',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',5,0,200,'normal','ما هو النهر الذي يمر بشرق فلسطين؟','نهر الأردن',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',5,1,200,'normal','ما هو العلم الذي يمثل فلسطين؟','علم الثورة العربية (ألوانه: أسود، أبيض، أخضر، أحمر)',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',5,2,400,'normal','في أي عام اندلعت الانتفاضة الفلسطينية الأولى؟','1987',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',5,3,400,'normal','ما هو الجبل الذي تطل منه مدينة نابلس؟','جبل جرزيم وجبل عيبال',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',5,4,600,'normal','ما هي "اتفاقية فيصل-وايزمان"؟','اتفاقية لم تكتمل حول التعاون الصهيوني العربي',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',5,5,600,'normal','ما هو أكبر حي في القدس الشرقية؟','بيت حنينا',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',6,0,200,'normal','ما هي العملة التي يستخدمها الفلسطينيون حالياً في تعاملاتهم؟','الشيكل الإسرائيلي والدينار الأردني والدولار',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',6,1,200,'normal','ما هي المدينة الفلسطينية التي تقع على ساحل البحر المتوسط وتلقب بـ "عروس البحر"؟','يافا',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',6,2,400,'normal','من هو أول رئيس للسلطة الوطنية الفلسطينية؟','ياسر عرفات',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',6,3,400,'normal','ما هي الدولة التي كانت تدير الضفة الغربية قبل عام 1967؟','المملكة الأردنية الهاشمية',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',6,4,600,'normal','في أي عام تم إغلاق "بيت الشرق" في القدس؟','2001',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',6,5,600,'normal','ما هو اسم المعاهدة التي أنهت الحرب بين إسرائيل ومصر (مع تأثيرها على غزة)؟','اتفاقية كامب ديفيد',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',7,0,200,'normal','ما هو النبات الوطني الفلسطيني؟','شجر الزيتون',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',7,1,200,'normal','من هو الشاعر الفلسطيني الذي لُقب بـ "شاعر المقاومة"؟','محمود درويش',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',7,2,400,'normal','ما هي الدولة التي كانت تدير قطاع غزة قبل عام 1967؟','مصر',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',7,3,400,'normal','ما هو اسم الميناء التاريخي في مدينة عكا؟','ميناء عكا',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',7,4,600,'normal','من هو الشخص الذي أطلق عليه "خازن أسرار الثورة"؟','صلاح خلف (أبو إياد)',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',7,5,600,'normal','ما هو الموقع الجغرافي لـ "سهل مرج بن عامر"؟','يقع بين الجليل وجبال نابلس',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',8,0,200,'normal','ما هي المدينة التي يوجد فيها الحرم الإبراهيمي؟','الخليل',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',8,1,200,'normal','ما هو الثوب الذي ترتديه المرأة الفلسطينية كرمز للتراث؟','الثوب المطرز (التطريز الفلسطيني)',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',8,2,400,'normal','بماذا تشتهر مدينة جنين؟','الزراعة (سلة غذاء فلسطين)',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',8,3,400,'normal','ما هي المعركة التي وقعت عام 1948 في مدينة القدس؟','معركة القسطل',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',8,4,600,'normal','ما هي المادة التي كان يتم تصديرها من منطقة البحر الميت قديماً؟','البوتاس',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',8,5,600,'normal','من هو الروائي الذي ألف رواية "الطنطورية" التي تؤرخ لقرية فلسطينية؟','رضوى عاشور',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',9,0,200,'normal','ما هي أكبر مدينة فلسطينية من حيث المساحة والسكان (داخل الضفة)؟','الخليل',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',9,1,200,'normal','بماذا تشتهر مدينة نابلس؟','الكنافة النابلسية',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',9,2,400,'normal','من هو الفنان الفلسطيني الذي رسم لوحات تعبر عن حياة اللاجئين؟','إسماعيل شموط',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',9,3,400,'normal','ما هو الاسم الذي أطلق على جدار الفصل الذي بنته إسرائيل في الضفة؟','جدار الضم والتوسع',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',9,4,600,'normal','ما هي المدينة التي تضم "سجن عكا" الشهير؟','عكا',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',9,5,600,'normal','متى تأسست جامعة بيرزيت كجامعة رسمية؟','1975',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',10,0,200,'normal','ما هو البحر الذي يقع في جنوب فلسطين ويشتهر بملوحته العالية؟','البحر الميت',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',10,1,200,'normal','ما هي المدينة التي شهدت ولادة السيد المسيح؟','بيت لحم',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',10,2,400,'normal','ما هي المدينة التي تضم جامعة النجاح الوطنية؟','نابلس',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',10,3,400,'normal','ما هو النهر الذي يصب في البحر الميت؟','نهر الأردن',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',10,4,600,'normal','ما هي العملة التي تم تداولها في فلسطين خلال فترة الحكم المصري لغزة؟','الجنيه المصري',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',10,5,600,'normal','ما هو اسم المنظمة التي أسسها عز الدين القسام؟','الكف الأسود',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',11,0,200,'normal','ما هي القبة الذهبية الشهيرة في القدس؟','قبة الصخرة',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',11,1,200,'normal','ما هو اليوم الذي يحييه الفلسطينيون في 15 مايو من كل عام؟','ذكرى النكبة',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',11,2,400,'normal','ما هو الموقع الأثري الشهير في مدينة سبسطية؟','آثار المدينة الرومانية والبيزنطية',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',11,3,400,'normal','في أي عام وقعت اتفاقية أوسلو؟','1993',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',11,4,600,'normal','من هو أول وزير خارجية لدولة فلسطين (بشكل رمزي)؟','فاروق قدومي',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',11,5,600,'normal','ما هي القرية التي اشتهرت بصمودها في معارك 1948 (قرية صمود)؟','قرية المالكية',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',12,0,200,'normal','ما هو اليوم الذي يحييه الفلسطينيون في 30 مارس من كل عام؟','يوم الأرض',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',12,1,200,'normal','ما هي العملة التي كانت مستخدمة في فلسطين قبل عام 1948؟','الجنيه الفلسطيني',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',12,2,400,'normal','ما هي القرية التي دمرت تماماً عام 1948 وتعتبر رمزاً للتهجير؟','دير ياسين',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',12,3,400,'normal','من هو الزعيم الفلسطيني الذي اغتيل في بيروت عام 1972 (كاتب)؟','غسان كنفاني',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',12,4,600,'normal','ما هو اسم الممر المائي الطبيعي الذي يربط بين غزة وبقية العالم؟','لا يوجد، غزة محاصرة بحرياً',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',12,5,600,'normal','من هو المؤرخ الفلسطيني الذي ألف كتاب "فلسطين قضية شعب"؟','عصام سخنيني',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',13,0,200,'normal','ما هو أشهر طبق طعام فلسطيني؟','المسخن',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',13,1,200,'normal','ما هي القلعة التاريخية الموجودة في مدينة غزة؟','قلعة برقوق',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',13,2,400,'normal','ما هي المنطقة التي تُعرف بـ "المثلث" في فلسطين؟','منطقة تضم قرى ومدن عربية داخل الخط الأخضر',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',13,3,400,'normal','ما هو الجبل الذي يرتفع عن سطح البحر في الضفة؟','جبل عيبال',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',13,4,600,'normal','ما هي الدولة التي استضافت مقر منظمة التحرير قبل بيروت؟','الأردن',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',13,5,600,'normal','ما هو الاسم القديم لمدينة نابلس في العصر الروماني؟','نيابوليس',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',14,0,200,'normal','كم تبلغ مساحة فلسطين التاريخية؟','حوالي 27 ألف كم²',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',14,1,200,'normal','ما هو المنظمة التي تمثل الفلسطينيين في المحافل الدولية؟','منظمة التحرير الفلسطينية',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',14,2,400,'normal','ما هي المدينة التي تضم "المسجد الكبير" (الجامع العمري الكبير)؟','غزة',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',14,3,400,'normal','بماذا تشتهر مدينة طولكرم؟','الحمضيات',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',14,4,600,'normal','ما هو العام الذي تم فيه تغيير اسم "فلسطين" إلى "سوريا فلسطين" من قبل الرومان؟','135 ميلادي',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',14,5,600,'normal','من هو القائد الذي فتح القدس عام 637م؟','عمر بن الخطاب',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',15,0,200,'normal','ما هي المدينة التي كانت مركزاً للإدارة البريطانية خلال فترة الانتداب؟','القدس',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',15,1,200,'normal','ما هي الدولة التي تحد فلسطين من جهة الشرق؟','الأردن',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',15,2,400,'normal','ما هي المحافظة الفلسطينية التي تضم أكبر عدد من المخيمات؟','نابلس أو بيت لحم (حسب التصنيف)',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',15,3,400,'normal','متى تم الاعتراف بفلسطين كدولة مراقب في الأمم المتحدة؟','2012',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',15,4,600,'normal','ما هي المدينة التي كانت تُعرف بـ "بوابة فلسطين"؟','يافا',NULL,NULL,NULL,NULL,NULL,NULL),
('palestine',15,5,600,'normal','ما هو اسم الكاتب الذي ألف كتاب "التطهير العرقي في فلسطين"؟','إيلان بابيه',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',1,0,200,'normal','ما اسم النبي محمد (ص) كاملاً؟','محمد بن عبد الله بن عبد المطلب',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',1,1,200,'normal','في أي مدينة ولد النبي؟','مكة المكرمة',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',1,2,400,'normal','ما اسم الغار الذي اختبأ فيه النبي وأبو بكر أثناء الهجرة؟','غار ثور',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',1,3,400,'normal','من هو الصحابي الذي لقب بـ "أمين الأمة"؟','أبو عبيدة عامر بن الجراح',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',1,4,600,'normal','ما اسم المرأة التي حاولت تسميم النبي في خيبر؟','زينب بنت الحارث',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',1,5,600,'normal','من هو الصحابي الذي كان يلقب بـ "ساعي بريد الرسول"؟','دحية الكلبي',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',2,0,200,'normal','ما اسم أم النبي؟','آمنة بنت وهب',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',2,1,200,'normal','من هو جد النبي الذي كفله بعد وفاة أبيه وأمه؟','عبد المطلب',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',2,2,400,'normal','ما هو اسم المعاهدة التي عقدت بين المسلمين وقريش عام 6 هجرياً؟','صلح الحديبية',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',2,3,400,'normal','كم كان عدد المسلمين في غزوة بدر؟','حوالي 313 مقاتلاً',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',2,4,600,'normal','ما هو اسم السيف الذي أهداه النبي لعلي بن أبي طالب؟','ذو الفقار',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',2,5,600,'normal','في أي عام توفي ابنه القاسم؟','في مكة (قبل البعثة)',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',3,0,200,'normal','ما اسم عم النبي الذي كفله ودافع عنه؟','أبو طالب',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',3,1,200,'normal','ما هي مهنة النبي قبل البعثة؟','رعي الغنم ثم التجارة',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',3,2,400,'normal','ما هي الغزوة التي حفر فيها المسلمون خندقاً؟','غزوة الخندق (الأحزاب)',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',3,3,400,'normal','من هو القائد الذي قاد المشركين في غزوة أحد؟','أبو سفيان',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',3,4,600,'normal','من هو الصحابي الذي كان يلقب بـ "حبر الأمة"؟','عبد الله بن عباس',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',3,5,600,'normal','ما اسم الغزوة التي لم يشارك فيها الرسول؟','السرايا (العديد منها)',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',4,0,200,'normal','ما لقب النبي قبل البعثة؟','الصادق الأمين',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',4,1,200,'normal','من هي أول زوجة للنبي؟','خديجة بنت خويلد',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',4,2,400,'normal','ما اسم الصحابية التي كانت ترضع الرسول؟','ثويبة مولاة أبي لهب (قبل حليمة)',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',4,3,400,'normal','في أي عام كان فتح مكة؟','8 هجرياً',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',4,4,600,'normal','ما هي القبيلة التي كانت تسكن خيبر وتم إجلاؤها؟','بنو نضير',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',4,5,600,'normal','من هو الصحابي الذي كان يلقب بـ "أسد الله"؟','حمزة بن عبد المطلب',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',5,0,200,'normal','في أي غار نزل الوحي على النبي؟','غار حراء',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',5,1,200,'normal','كم كان عمر النبي عندما نزل عليه الوحي؟','40 سنة',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',5,2,400,'normal','من هو الصحابي الذي أشار بحفر الخندق؟','سلمان الفارسي',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',5,3,400,'normal','ما اسم زوجة النبي التي تزوجها بعد وفاة خديجة وكانت أكبر منه؟','سودة بنت زمعة',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',5,4,600,'normal','ما هو اسم المعركة التي استشهد فيها قادة المسلمين الثلاثة (جعفر، زيد، ابن رواحة)؟','مؤتة',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',5,5,600,'normal','ما اسم الكتاب الذي أرسله النبي إلى كسرى؟','رسالة دعوة إلى الإسلام',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',6,0,200,'normal','من هو الملك الذي نزل بالوحي على النبي؟','جبريل عليه السلام',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',6,1,200,'normal','ما اسم المدينة التي هاجر إليها النبي؟','يثرب (المدينة المنورة)',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',6,2,400,'normal','ما هي الغزوة التي انتهت بنصر المسلمين بعد هزيمة أولية؟','حنين',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',6,3,400,'normal','ما اسم الصحابي الذي لقب بـ "فاروق الأمة"؟','عمر بن الخطاب',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',6,4,600,'normal','من هو الصحابي الذي لقب بـ "أبو هريرة"؟','عبد الرحمن بن صخر الدوسي',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',6,5,600,'normal','في أي معركة حارب النبي بيده للمرة الوحيدة؟','معركة أحد (أو بدر، لكن في الخندق لم يلتحم)',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',7,0,200,'normal','من هو رفيق النبي في الهجرة؟','أبو بكر الصديق',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',7,1,200,'normal','ما اسم ابنة النبي التي لقبت بـ "أم أبيها"؟','فاطمة الزهراء',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',7,2,400,'normal','ما هو اسم العام الذي شهد وفود القبائل للإسلام؟','عام الوفود',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',7,3,400,'normal','من هو الصحابي الذي كان يلقب بـ "سيف الله المسلول"؟','خالد بن الوليد',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',7,4,600,'normal','ما اسم زوجة النبي التي لقبت بـ "الحميراء"؟','عائشة بنت أبي بكر',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',7,5,600,'normal','من هو الصحابي الذي كان يلقب بـ "صاحب سر النبي"؟','حذيفة بن اليمان',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',8,0,200,'normal','ما هي المعجزة الكبرى للنبي؟','القرآن الكريم',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',8,1,200,'normal','كم عدد أبناء النبي الذكور؟','ثلاثة (القاسم، عبد الله، إبراهيم)',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',8,2,400,'normal','في أي عام حدثت معجزة الإسراء والمعراج؟','قبل الهجرة بحوالي سنة ونصف',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',8,3,400,'normal','ما اسم والدة النبي إبراهيم ابن الرسول؟','مارية القبطية',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',8,4,600,'normal','ما اسم الغزوة التي وقعت في السنة الخامسة للهجرة؟','بني المصطلق (أو الخندق)',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',8,5,600,'normal','من هو الرجل الذي كان يلقب بـ "العدس" وكان أول من أسلم من أهل الطائف؟','عداس',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',9,0,200,'normal','ما هي أول غزوة في الإسلام؟','غزوة بدر',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',9,1,200,'normal','ما اسم ناقة النبي التي هاجر عليها؟','القصواء',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',9,2,400,'normal','كم كان عمر النبي عند وفاة أمه آمنة؟','6 سنوات',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',9,3,400,'normal','من هو الذي قال عنه النبي "صدقني حين كذبني الناس"؟','أبو بكر الصديق',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',9,4,600,'normal','في أي عام تم بناء المسجد النبوي؟','1 هجرياً',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',9,5,600,'normal','ما هو اسم الغزوة التي وقعت في السنة الثامنة للهجرة بعد فتح مكة؟','حنين',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',10,0,200,'normal','من هو مؤذن الرسول؟','بلال بن رباح',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',10,1,200,'normal','في أي عام توفي النبي؟','11 هجرياً',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',10,2,400,'normal','ما هو اسم الغزوة التي وقعت بين المسلمين والروم قبل وفاة النبي؟','مؤتة (ثم تبوك)',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',10,3,400,'normal','من هو الصحابي الذي كان يكتب الوحي للنبي؟','زيد بن ثابت',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',10,4,600,'normal','من هو الصحابي الذي كان يلقب بـ "أمين سر النبي في المنافقين"؟','حذيفة بن اليمان',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',10,5,600,'normal','ما هو اسم الصحابي الذي كان يلقب بـ "عاشر العشرة المبشرين بالجنة"؟','سعيد بن زيد',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',11,0,200,'normal','كم سنة مكث النبي في مكة بعد البعثة؟','13 سنة',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',11,1,200,'normal','كم سنة عاش النبي في المدينة؟','10 سنوات',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',11,2,400,'normal','ما اسم بئر زمزم التي حفرها جد النبي؟','بئر زمزم (أعاد حفرها عبد المطلب)',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',11,3,400,'normal','كم عدد زوجات النبي (أمهات المؤمنين)؟','11 زوجة',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',11,4,600,'normal','في أي معركة كُسرت رباعية النبي؟','غزوة أحد',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',11,5,600,'normal','ما اسم المرأة التي أشار عليها الرسول في صلح الحديبية؟','أم سلمة',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',12,0,200,'normal','ما اسم مرضعة النبي؟','حليمة السعدية',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',12,1,200,'normal','من هو الصحابي الذي نام في فراش النبي ليلة الهجرة؟','علي بن أبي طالب',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',12,2,400,'normal','ما هو اسم الصحابي الذي فدى النبي بنفسه يوم أحد؟','طلحة بن عبيد الله',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',12,3,400,'normal','في أي عام تم تغيير القبلة من بيت المقدس إلى الكعبة؟','2 هجرياً',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',12,4,600,'normal','من هو الصحابي الذي لقب بـ "رجل من أهل الجنة"؟','ثابت بن قيس',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',12,5,600,'normal','ما اسم المكان الذي توفي فيه النبي؟','حجرة عائشة',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',13,0,200,'normal','ما هي المعركة التي استشهد فيها حمزة بن عبد المطلب؟','غزوة أحد',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',13,1,200,'normal','ما اسم العام الذي توفيت فيه زوجته خديجة وعمه أبو طالب؟','عام الحزن',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',13,2,400,'normal','من هو الصحابي الذي كان يحمل راية المهاجرين في فتح مكة؟','مصعب بن عمير (في بدر، أما في الفتح كان الزبير)',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',13,3,400,'normal','ما هو اسم الغلام الذي كان يخدم النبي؟','أنس بن مالك',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',13,4,600,'normal','كم كان عمر النبي حين تزوج خديجة؟','25 سنة',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',13,5,600,'normal','ما اسم الصحابي الذي كان يلقب بـ "أبو بكر الصديق"؟','عبد الله بن أبي قحافة',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',14,0,200,'normal','ما اسم القبيلة التي ولد فيها النبي؟','قريش',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',14,1,200,'normal','من هو ابن النبي الذي مات صغيراً؟','إبراهيم',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',14,2,400,'normal','من هو الصحابي الذي لقب بـ "ذو النورين"؟','عثمان بن عفان',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',14,3,400,'normal','ما هي الغزوة التي سميت بـ "الفاضحة" للمنافقين؟','غزوة تبوك',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',14,4,600,'normal','ما هي الغزوة التي سميت بـ "ذات الرقاع"؟','غزوة بني محارب وبني ثعلبة',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',14,5,600,'normal','من هو الذي رماه المشركون بالشوك في مكة؟','الرسول (ص)',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',15,0,200,'normal','ما اسم العام الذي ولد فيه النبي؟','عام الفيل',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',15,1,200,'normal','ما هو المسجد الذي أسسه النبي عند وصوله المدينة؟','مسجد قباء',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',15,2,400,'normal','في أي شهر ولد النبي؟','ربيع الأول',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',15,3,400,'normal','من هو الصحابي الذي كان يلقب بـ "أبو المساكين"؟','جعفر بن أبي طالب',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',15,4,600,'normal','ما اسم الصحابي الذي لقب بـ "مؤذن الرسول"؟','بلال بن رباح',NULL,NULL,NULL,NULL,NULL,NULL),
('seerah',15,5,600,'normal','في أي معركة استشهد مصعب بن عمير؟','غزوة أحد',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',1,0,200,'normal','ما هو الكتاب المقدس عند المسلمين؟','القرآن الكريم',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',1,1,200,'normal','على من أنزل القرآن الكريم؟','على النبي محمد ﷺ',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',1,2,400,'normal','ما الفرق بين السور المكية والمدنية؟','المكية نزلت قبل الهجرة، والمدنية بعدها',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',1,3,400,'normal','ما هي أول سورة نزلت في القرآن؟','سورة العلق (أول 5 آيات)',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',1,4,600,'normal','ما هو عدد القراءات الصحيحة للقرآن الكريم؟','10 قراءات',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',1,5,600,'normal','ما هو الرسم العثماني للقرآن؟','الرسم الذي كتب به الصحابة المصاحف في عهد عثمان',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',2,0,200,'normal','ما هو اسم الملك الذي نزل بالقرآن على النبي؟','جبريل عليه السلام',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',2,1,200,'normal','كم عدد سور القرآن الكريم؟','114 سورة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',2,2,400,'normal','ما هي آخر سورة نزلت في القرآن؟','سورة النصر (أو آيات الربا في البقرة)',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',2,3,400,'normal','من هو الصحابي الذي أمر بجمع القرآن في مصحف واحد في عهد عثمان؟','عثمان بن عفان رضي الله عنه',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',2,4,600,'normal','كم عدد سجدات التلاوة في القرآن؟','15 سجدة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',2,5,600,'normal','ما هي السورة التي ورد فيها ذكر "ذو القرنين"؟','سورة الكهف',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',3,0,200,'normal','ما هي أطول سورة في القرآن الكريم؟','سورة البقرة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',3,1,200,'normal','ما هي أقصر سورة في القرآن الكريم؟','سورة الكوثر',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',3,2,400,'normal','ما هي السورة التي تسمى "الفاضحة"؟','سورة التوبة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',3,3,400,'normal','كم مرة ذكر اسم النبي محمد ﷺ في القرآن؟','4 مرات',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',3,4,600,'normal','من هو القارئ الذي تنسب إليه رواية "حفص عن عاصم"؟','عاصم بن أبي النجود',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',3,5,600,'normal','ما هو "الإدغام بغنة"؟','دمج النون الساكنة أو التنوين في حروف "ينمو"',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',4,0,200,'normal','ما هي السورة التي تسمى "قلب القرآن"؟','سورة يس',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',4,1,200,'normal','ما هي السورة التي تسمى "عروس القرآن"؟','سورة الرحمن',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',4,2,400,'normal','ما هو عدد الأحزاب في القرآن الكريم؟','60 حزباً',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',4,3,400,'normal','ما هي السورة التي تحث على قراءتها يوم الجمعة؟','سورة الكهف',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',4,4,600,'normal','ما هي السورة التي تسمى "سورة الشورى"؟','سورة الشورى',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',4,5,600,'normal','كم عدد السور التي تبدأ بالحروف المقطعة؟','29 سورة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',5,0,200,'normal','ما هي السورة التي تعدل ثلث القرآن؟','سورة الإخلاص',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',5,1,200,'normal','في أي شهر أنزل القرآن؟','شهر رمضان',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',5,2,400,'normal','ما هي السورة التي تسمى "بني إسرائيل"؟','سورة الإسراء',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',5,3,400,'normal','من هو النبي الذي ذكر اسمه أكثر من غيره في القرآن؟','موسى عليه السلام',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',5,4,600,'normal','ما هي السورة التي ذكرت فيها صلاة الوسطى؟','سورة البقرة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',5,5,600,'normal','ما هي "أسباب النزول"؟','الوقائع التي نزلت بسببها آية معينة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',6,0,200,'normal','ما هي السورة التي بدأت بـ "بسم الله الرحمن الرحيم" وانتهت بـ "سورة"؟','الفاتحة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',6,1,200,'normal','ما هي السورة التي لا تبدأ بـ "بسم الله الرحمن الرحيم"؟','سورة التوبة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',6,2,400,'normal','ما هي السورة التي تتحدث عن يوم القيامة بالتفصيل؟','سورة القيامة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',6,3,400,'normal','ما هو السجدة الواجبة في القرآن؟','لا توجد سجدة "واجبة" بلفظ الوجوب، بل هي سجدات تلاوة (سنة)',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',6,4,600,'normal','ما هي السورة التي تسمى "الحاقة"؟','سورة الحاقة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',6,5,600,'normal','ما هو "الإخفاء" في أحكام التجويد؟','النطق بالنون الساكنة بصفة بين الإظهار والإدغام',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',7,0,200,'normal','ما هي السورة التي تسمى "أم الكتاب"؟','سورة الفاتحة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',7,1,200,'normal','كم عدد أجزاء القرآن الكريم؟','30 جزءاً',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',7,2,400,'normal','ما معنى "المتشابهات" في القرآن؟','آيات تتطلب تأويلاً أو علمًا خاصًا',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',7,3,400,'normal','ما هي السورة التي تسمى "مجادلة"؟','سورة المجادلة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',7,4,600,'normal','ما هي السورة التي تسمى "الواقعة"؟','سورة الواقعة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',7,5,600,'normal','ما هو عدد سور القرآن التي سميت بأسماء الأنبياء؟','6 سور (يونس، هود، يوسف، إبراهيم، محمد، نوح)',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',8,0,200,'normal','ما هي السورة التي ذكر فيها "الكرسي"؟','سورة البقرة (آية الكرسي)',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',8,1,200,'normal','ما هو الحرف الذي كرر كثيراً في سورة الكوثر؟','حرف الكاف',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',8,2,400,'normal','من هو الصحابي الملقب بـ "جامع القرآن"؟','زيد بن ثابت',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',8,3,400,'normal','ما هي السورة التي تسمى "الأنعام"؟','سورة الأنعام',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',8,4,600,'normal','ما هي السورة التي تسمى "سورة الطور"؟','سورة الطور',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',8,5,600,'normal','ما هو حكم "النون المشددة"؟','الغنة',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',9,0,200,'normal','ما هي السورة التي ذكرت فيها البسملة مرتين؟','سورة النمل',NULL,NULL,NULL,NULL,NULL,NULL),
('quran',9,1,200,'normal','هل القرآن كلام الله أم كلام النبي؟','كلام الله',NULL,NULL,NULL,NULL,NULL,NULL)
on conflict(category,version,ord) do update set value=excluded.value,type=excluded.type,q=excluded.q,a=excluded.a,note=excluded.note,flag=excluded.flag,clues=excluded.clues,num=excluded.num,evidence=excluded.evidence,suspects=excluded.suspects;

commit;
