-- FAKKIR seed — part 7 of 9. Generated; do not edit by hand.
-- Run server/sql/schema.sql once, then paste these part files into the Supabase SQL Editor in order (01, 02, ...).
begin;

-- Categories (idempotent; required by the questions foreign key)
insert into categories(slug,name,color,image,sort_order) values
('geo','الجغرافيا','blue','assets/img/categories/geo.png',0),
('history','التاريخ','gold','assets/img/categories/history.png',1),
('palestine','فلسطين','green','assets/img/categories/palestine.png',2),
('seerah','السيرة النبوية','teal','assets/img/categories/seerah.png',3),
('quran','القرآن الكريم','green','assets/img/categories/quran.png',4),
('flags','أعلام الدول','red','assets/img/categories/flags.png',5),
('sports','الرياضة','cyan','assets/img/categories/sports.png',6),
('football','كرة القدم','blue','assets/img/categories/football.png',7),
('riddles','الألغاز','purple','assets/img/categories/riddles.png',8),
('science','العلوم','teal','assets/img/categories/science.png',9),
('tech','التكنولوجيا','cyan','assets/img/categories/tech.png',10),
('animals','عالم الحيوان','gold','assets/img/categories/animals.png',11),
('general','المعلومات العامة','gold','assets/img/categories/general.png',12),
('math','الرياضيات والأرقام','blue','assets/img/categories/math.png',13),
('whoami','احزر ماذا أنا','purple','assets/img/categories/whoami.png',14),
('proverbs','تكملة المثل','teal','assets/img/categories/proverbs.png',15),
('dish','ما هي الأكلة','red','assets/img/categories/dish.png',16),
('crime','الجريمة','red','assets/img/categories/crime.png',17),
('rescue','إنقاذ المتهم','green','assets/img/categories/rescue.png',18),
('closest','الأقرب إلى الرقم','purple','assets/img/categories/closest.png',19),
('capitals','عواصم الدول','blue','assets/img/categories/capitals.png',20),
('currencies','عملات الدول','gold','assets/img/categories/currencies.png',21),
('verse','أكمل الآية','green','assets/img/categories/verse.png',22),
('ordering','الترتيب الصحيح','cyan','assets/img/categories/ordering.png',23)
on conflict(slug) do update set name=excluded.name,color=excluded.color,image=excluded.image,sort_order=excluded.sort_order;

-- Questions 1501..1750
insert into questions(category,version,ord,value,type,q,a,note,flag,clues,num,evidence,suspects) values
('dish',11,0,200,'normal','ما هي الأكلة التي تتكون من عجينة رقيقة ومحشوة خضار؟','السمبوسة',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',11,1,200,'normal','ما هو الطبق العربي المكون من ورق عنب محشو أرز؟','اليبرق أو ورق العنب',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',11,2,400,'normal','ما هي الأكلة المكونة من خضار بصلصة؟','خضار سوتيه',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',11,3,400,'normal','ما هو الطبق المكون من لحم بقر مجفف؟','بسطرمة',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',11,4,600,'normal','ما هي الأكلة التي تتكون من دجاج بالكريمة؟','دجاج ألفريدو',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',11,5,600,'normal','ما هو الطبق المكون من لحم مطبوخ بالحليب؟','شاكرية',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',12,0,200,'normal','ما هي الأكلة التي تقدم في العيد وتكون من كعك محشو تمر؟','المعمول',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',12,1,200,'normal','ما هو الطبق المكون من بطاطس مقلية مع مرق وجبن؟','البوتين - Poutine',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',12,2,400,'normal','ما هي الأكلة المكونة من أرز ولبن؟','أرز بحليب',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',12,3,400,'normal','ما هو الطبق المكون من سميد وسكر؟','البسبوسة',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',12,4,600,'normal','ما هي الأكلة التي تتكون من أرز بصلصة الفاصوليا؟','فاصوليا بالمرق',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',12,5,600,'normal','ما هو الطبق المكون من خبز وفول؟','فول مدمس',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',13,0,200,'normal','ما هي الأكلة الألمانية المكونة من عجين مسلوق؟','السباتزل',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',13,1,200,'normal','ما هو الطبق اللبناني المكون من خضار مقلية ومرق طماطم؟','المسقعة اللبنانية',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',13,2,400,'normal','ما هي الأكلة المكونة من طحين وحليب؟','البان كيك',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',13,3,400,'normal','ما هو الطبق المكون من بيض ومسلوق؟','بيض مسلوق',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',13,4,600,'normal','ما هي الأكلة التي تتكون من سمك بصلصة حمراء؟','صيادية حمراء',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',13,5,600,'normal','ما هو الطبق المكون من دجاج بالزعفران؟','دجاج بالزعفران',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',14,0,200,'normal','ما هي الأكلة السريعة المكونة من عجين مقلي ومحشو جبن؟','البيتزا المقلية',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',14,1,200,'normal','ما هو الطبق الكوري المكون من خضار مخمرة؟','الكيمتشي',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',14,2,400,'normal','ما هي الأكلة المكونة من خضار ولحم؟','محاشي',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',14,3,400,'normal','ما هو الطبق المكون من جبن وزيتون؟','فطور',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',14,4,600,'normal','ما هي الأكلة التي تتكون من خضار بصلصة الثوم؟','خضار بالثوم',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',14,5,600,'normal','ما هو الطبق المكون من لحم بصلصة المشروم؟','لحم بالمشروم',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',15,0,200,'normal','ما هي الأكلة البريطانية المكونة من سمك وبطاطس؟','فيش أند شيبس',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',15,1,200,'normal','ما هو الطبق العربي المكون من دجاج وأرز ومكسرات؟','الكبسة',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',15,2,400,'normal','ما هي الأكلة المكونة من عجين وشوكولاتة؟','كيك',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',15,3,400,'normal','ما هو الطبق المكون من لحم غنم؟','خروف محشي',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',15,4,600,'normal','ما هي الأكلة التي تتكون من عجينة مطبوخة بالماء؟','نودلز',NULL,NULL,NULL,NULL,NULL,NULL),
('dish',15,5,600,'normal','ما هو الطبق المكون من أرز بنكهة البهارات؟','مندي',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',1,0,200,'normal','كم عدد الأمتار في 5 كيلومترات؟','5000 متر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',1,1,200,'normal','كم عدد الثواني في 10 دقائق؟','600 ثانية',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',1,2,400,'normal','كم عدد الدرجات في ربع دائرة؟','90 درجة',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',1,3,400,'normal','ما هو محيط دائرة نصف قطرها 7 سم (π=22/7)؟','44 سم',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',1,4,600,'normal','إذا كانت سرعة التفاعل 2 مول/لتر/ثانية، فما التركيز المستهلك في 10 ثوانٍ؟','20 مول/لتر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',1,5,600,'normal','كم عدد الذرات في 2 مول (أفوجادرو $6 \times 10^{23}$)؟','$12 \times 10^{23}$ ذرة',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',2,0,200,'normal','كم عدد الجرامات في 2 كيلوجرام؟','2000 جرام',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',2,1,200,'normal','كم عدد السنتيمترات في 3 أمتار؟','300 سنتيمتر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',2,2,400,'normal','إذا كان ضغط غاز 2 باسكال في مساحة 5 متر مربع، فكم القوة بالنيوتن؟','10 نيوتن',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',2,3,400,'normal','كم عدد السنتيمترات المكعبة في 1 لتر؟','1000 سم³',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',2,4,600,'normal','ما هو ناتج قسمة 500 واط على 220 فولت؟','2.27 أمبير',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',2,5,600,'normal','إذا كان ثابت النابض 5 نيوتن/متر، فما القوة لضغط نابض 0.2 متر؟','1 نيوتن',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',3,0,200,'normal','كم عدد المليلترات في 4 لترات؟','4000 مليلتر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',3,1,200,'normal','إذا تحرك جسم بسرعة 10 متر/ثانية لمدة 5 ثوانٍ، فما المسافة المقطوعة؟','50 متراً',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',3,2,400,'normal','إذا كانت سرعة الضوء $3 \times 10^8$ متر/ثانية، فكم يقطع في 1 نانوثانية؟','0.3 متر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',3,3,400,'normal','كم عدد الراديان في 180 درجة؟','π راديان',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',3,4,600,'normal','كم عدد الراديان في 360 درجة؟','2π راديان',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',3,5,600,'normal','إذا كانت السرعة الزاوية 10 راديان/ثانية، فما التردد الزاوي؟','10 راديان/ثانية',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',4,0,200,'normal','ما هو مجموع 50 درجة مئوية + 20 درجة مئوية؟','70 درجة مئوية',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',4,1,200,'normal','كم عدد الواط في 3 كيلوواط؟','3000 واط',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',4,2,400,'normal','إذا كانت طاقة جسم 100 جول، فكم تصبح إذا تضاعفت السرعة 4 مرات؟','1600 جول',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',4,3,400,'normal','كم عدد الكيلوبايت في 1 ميجابايت؟','1024 كيلوبايت',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',4,4,600,'normal','كم عدد الكيلو واط/ساعة في 3.6 مليون جول؟','1 كيلوواط/ساعة',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',4,5,600,'normal','إذا كانت طاقة الفوتون بالتردد $10^{15}$ هيرتز ($h=6.6 \times 10^{-34}$)، فما الطاقة؟','$6.6 \times 10^{-19}$ جول',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',5,0,200,'normal','إذا كان وزن صندوق 50 نيوتن، فما كتلته التقريبية بالكيلوجرام (الجاذبية 10 م/ث²؟)','5 كيلوجرام',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',5,1,200,'normal','كم عدد الدقائق في 4 ساعات؟','240 دقيقة',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',5,2,400,'normal','كم عدد الجرامات في 1 مول من الهيدروجين؟','1 جرام',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',5,3,400,'normal','كم عدد المترات في 1 ميل بحري؟','1852 متراً',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',5,4,600,'normal','كم عدد الإلكترون فولت في 1 جول؟','$6.24 \times 10^{18}$ إلكترون فولت',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',5,5,600,'normal','إذا كانت الكثافة 1000 كجم/متر³، فما كتلة 2 متر مكعب بالكجم؟','2000 كجم',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',6,0,200,'normal','كم عدد الميكرومترات في 1 مليمتر؟','1000 ميكرومتر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',6,1,200,'normal','إذا كانت كثافة مادة 2 جرام/سم³، فما كتلة 10 سم³ منها؟','20 جراماً',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',6,2,400,'normal','إذا كان التيار 5 أمبير والمقاومة 10 أوم، فما الجهد بالفولت؟','50 فولت',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',6,3,400,'normal','كم عدد الثواني في 1 يوم؟','86400 ثانية',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',6,4,600,'normal','كم عدد الميكروثانية في 1 ثانية؟','1,000,000 ميكروثانية',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',6,5,600,'normal','إذا كان نصف قطر الأرض 6400 كيلومتر، فما محيطها؟','40212 كيلومتر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',7,0,200,'normal','كم عدد الأميال في 32.18 كيلومتر تقريباً (1 ميل = 1.609 كم)؟','20 ميلاً',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',7,1,200,'normal','كم عدد النيوتن اللازمة لتحريك كتلة 5 كيلوجرام بتسارع 2 متر/ثانية²؟','10 نيوتن',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',7,2,400,'normal','إذا كانت مساحة المربع 16 سم²، فكم طول ضلعه بالسم؟','4 سم',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',7,3,400,'normal','كم عدد الملليجرام في 5 جرامات؟','5000 ملليجرام',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',7,4,600,'normal','كم عدد النيوتن في 1 كيلوجرام ثقلي؟','9.8 نيوتن',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',7,5,600,'normal','إذا كان الجهد 12 فولت والتيار 2 أمبير، فما القدرة؟','24 واط',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',8,0,200,'normal','إذا كان طول مستطيل 10 سم وعرضه 5 سم، فكم مساحته بالسم²؟','50 سم²',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',8,1,200,'normal','كم عدد الهيرتز في 2 كيلوهيرتز؟','2000 هيرتز',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',8,2,400,'normal','كم عدد الأميال في 10 كيلومتر (1 ميل = 1.6 كم)؟','6.25 ميل',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',8,3,400,'normal','إذا كانت شدة المجال الكهربائي 5 نيوتن/كولوم، فما القوة المؤثرة على شحنة 2 كولوم؟','10 نيوتن',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',8,4,600,'normal','كم عدد المترات المكعبة في 1000 لتر؟','1 متر مكعب',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',8,5,600,'normal','إذا كانت الكتلة 10 جرام (0.01 كجم) والسرعة 2 متر/ثانية، فما الزخم؟','0.02 كجم.متر/ثانية',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',9,0,200,'normal','ما هو ناتج قسمة 100 جول على 5 ثوانٍ؟','20 واط',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',9,1,200,'normal','كم عدد البايت في 2 كيلوبايت (حسابياً 1024)؟','2048 بايت',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',9,2,400,'normal','كم عدد الدقائق في 0.25 ساعة؟','15 دقيقة',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',9,3,400,'normal','كم عدد الهكتارات في 20000 متر مربع؟','2 هكتار',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',9,4,600,'normal','كم عدد النانومتر في 1 ميكرومتر؟','1000 نانومتر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',9,5,600,'normal','إذا كان التردد 50 هيرتز، فما الزمن الدوري؟','0.02 ثانية',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',10,0,200,'normal','إذا كانت درجة حرارة غاز 300 كلفن، فكم تعادل بالسيلزيوس؟','26.85 درجة مئوية',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',10,1,200,'normal','كم عدد الساعات في 120 دقيقة؟','ساعتان',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',10,2,400,'normal','إذا كان حجم مكعب 27 سم³، فكم طول حرفه بالسم؟','3 سم',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',10,3,400,'normal','كم عدد الكيلوجول في 5000 جول؟','5 كيلوجول',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',10,4,600,'normal','كم عدد الكولوم في تيار 10 أمبير لمدة 5 ثوانٍ؟','50 كولوم',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',10,5,600,'normal','إذا كان عزم الدوران 20 نيوتن.متر، فما القوة على ذراع 2 متر؟','10 نيوتن',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',11,0,200,'normal','إذا كانت سرعة الصوت 340 متر/ثانية، فكم يقطع في 2 ثانية؟','680 متراً',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',11,1,200,'normal','كم عدد الجرامات في 0.5 كيلوجرام؟','500 جرام',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',11,2,400,'normal','إذا كان التسارع 2 متر/ثانية²، فكم تصبح السرعة بعد 10 ثوانٍ؟','20 متر/ثانية',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',11,3,400,'normal','كم عدد السنوات في 3650 يوم؟','10 سنوات',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',11,4,600,'normal','كم عدد الجرام/لتر في محلول 0.5 مول/لتر (كتلة مولية 40)؟','20 جرام/لتر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',11,5,600,'normal','إذا كانت طاقة الحركة 50 جول والكتلة 4 كجم، فما السرعة؟','5 متر/ثانية',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',12,0,200,'normal','كم عدد الأمتار في 500 سم؟','5 أمتار',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',12,1,200,'normal','كم عدد الديسيبل الذي يعتبر ضعف شدة 10 ديسيبل؟','13 ديسيبل',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',12,2,400,'normal','إذا كانت الشحنة 10 كولوم والزمن 2 ثانية، فما التيار بالأمبير؟','5 أمبير',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',12,3,400,'normal','كم عدد المترات في 0.5 كيلومتر؟','500 متر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',12,4,600,'normal','كم عدد الجيجابايت في 2048 ميجابايت؟','2 جيجابايت',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',12,5,600,'normal','إذا كانت شدة الصوت 10⁻¹² واط/متر²، فكم تعادل بالديسيبل؟','0 ديسيبل',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',13,0,200,'normal','كم عدد اللترات في 2000 مليلتر؟','2 لتر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',13,1,200,'normal','إذا كانت قدرة مصباح 60 واط، فكم يستهلك من الكيلوواط/ساعة في 10 ساعات؟','0.6 كيلوواط/ساعة',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',13,2,400,'normal','كم عدد الجرامات في 3 كيلوجرام؟','3000 جرام',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',13,3,400,'normal','كم عدد الواط في 0.5 كيلوواط؟','500 واط',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',13,4,600,'normal','كم عدد المترات في 10 كيلومتر؟','10000 متر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',13,5,600,'normal','إذا كان ضغط الماء 10000 باسكال، فكم يعادل بالنيوتن/متر²؟','10000 نيوتن/متر²',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',14,0,200,'normal','كم عدد النيوتن في 10 كيلوجرام (الجاذبية 9.8 م/ث²)؟','98 نيوتن',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',14,1,200,'normal','كم عدد الثواني في نصف ساعة؟','1800 ثانية',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',14,2,400,'normal','إذا كان الضغط 100 باسكال، فكم يعادل بالكيلو باسكال؟','0.1 كيلوباسكال',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',14,3,400,'normal','كم عدد السنتيمترات في 0.1 متر؟','10 سنتيمتر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',14,4,600,'normal','كم عدد الديسي متر المكعب في 1 لتر؟','1 ديسي متر مكعب',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',14,5,600,'normal','إذا كانت الحرارة النوعية 4.2 جول/جرام.درجة، لتسخين 10 جرام بمقدار 10 درجات؟','420 جول',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',15,0,200,'normal','كم عدد المليمترات في 2 متر؟','2000 مليمتر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',15,1,200,'normal','إذا تحركت سيارة 100 كيلومتر في ساعتين، فما سرعتها بالكيلومتر/ساعة؟','50 كم/ساعة',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',15,2,400,'normal','كم عدد المليمترات في 5 سنتيمتر؟','50 مليمتر',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',15,3,400,'normal','إذا كانت الإزاحة 50 متر في 10 ثوانٍ، فما السرعة بالمتر/ثانية؟','5 متر/ثانية',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',15,4,600,'normal','كم عدد الثواني في 1 سنة؟','31,536,000 ثانية',NULL,NULL,NULL,NULL,NULL,NULL),
('closest',15,5,600,'normal','إذا كانت القدرة 1 كيلوواط والزمن 1 ساعة، فما الطاقة؟','1 كيلوواط.ساعة',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',1,0,200,'normal','ما عاصمة فرنسا؟','باريس',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',1,1,200,'normal','ما عاصمة المملكة المتحدة؟','لندن',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',1,2,400,'normal','ما عاصمة البرتغال؟','لشبونة',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',1,3,400,'normal','ما عاصمة النمسا؟','فيينا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',1,4,600,'normal','ما عاصمة كازاخستان؟','أستانا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',1,5,600,'normal','ما عاصمة أوزبكستان؟','طشقند',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',2,0,200,'normal','ما عاصمة المملكة العربية السعودية؟','الرياض',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',2,1,200,'normal','ما عاصمة الولايات المتحدة؟','واشنطن',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',2,2,400,'normal','ما عاصمة كوريا الجنوبية؟','سول',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',2,3,400,'normal','ما عاصمة ماليزيا؟','كوالالمبور',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',2,4,600,'normal','ما عاصمة منغوليا؟','أولان باتور',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',2,5,600,'normal','ما عاصمة نيبال؟','كاتماندو',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',3,0,200,'normal','ما عاصمة مصر؟','القاهرة',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',3,1,200,'normal','ما عاصمة اليابان؟','طوكيو',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',3,2,400,'normal','ما عاصمة تايلاند؟','بانكوك',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',3,3,400,'normal','ما عاصمة إندونيسيا؟','جاكرتا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',3,4,600,'normal','ما عاصمة الفلبين؟','مانيلا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',3,5,600,'normal','ما عاصمة فيتنام؟','هانوي',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',4,0,200,'normal','ما عاصمة ألمانيا؟','برلين',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',4,1,200,'normal','ما عاصمة إيطاليا؟','روما',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',4,2,400,'normal','ما عاصمة الأرجنتين؟','بوينس آيرس',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',4,3,400,'normal','ما عاصمة المكسيك؟','مكسيكو سيتي',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',4,4,600,'normal','ما عاصمة سنغافورة؟','سنغافورة',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',4,5,600,'normal','ما عاصمة أفغانستان؟','كابول',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',5,0,200,'normal','ما عاصمة الصين؟','بكين',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',5,1,200,'normal','ما عاصمة إسبانيا؟','مدريد',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',5,2,400,'normal','ما عاصمة باكستان؟','إسلام آباد',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',5,3,400,'normal','ما عاصمة إيران؟','طهران',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',5,4,600,'normal','ما عاصمة آيسلندا؟','ريكيافيك',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',5,5,600,'normal','ما عاصمة بلغاريا؟','صوفيا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',6,0,200,'normal','ما عاصمة روسيا؟','موسكو',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',6,1,200,'normal','ما عاصمة الإمارات؟','أبوظبي',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',6,2,400,'normal','ما عاصمة سوريا؟','دمشق',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',6,3,400,'normal','ما عاصمة فلسطين؟','القدس',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',6,4,600,'normal','ما عاصمة إثيوبيا؟','أديس أبابا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',6,5,600,'normal','ما عاصمة نيجيريا؟','أبوجا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',7,0,200,'normal','ما عاصمة لبنان؟','بيروت',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',7,1,200,'normal','ما عاصمة الأردن؟','عمّان',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',7,2,400,'normal','ما عاصمة ليبيا؟','طرابلس',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',7,3,400,'normal','ما عاصمة السودان؟','الخرطوم',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',7,4,600,'normal','ما عاصمة كينيا؟','نيروبي',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',7,5,600,'normal','ما عاصمة غانا؟','أكرا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',8,0,200,'normal','ما عاصمة المغرب؟','الرباط',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',8,1,200,'normal','ما عاصمة تونس؟','تونس',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',8,2,400,'normal','ما عاصمة عُمان؟','مسقط',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',8,3,400,'normal','ما عاصمة البحرين؟','المنامة',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',8,4,600,'normal','ما عاصمة السنغال؟','داكار',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',8,5,600,'normal','ما عاصمة تنزانيا؟','دودوما',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',9,0,200,'normal','ما عاصمة الجزائر؟','الجزائر',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',9,1,200,'normal','ما عاصمة العراق؟','بغداد',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',9,2,400,'normal','ما عاصمة اليمن؟','صنعاء',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',9,3,400,'normal','ما عاصمة النرويج؟','أوسلو',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',9,4,600,'normal','ما عاصمة مدغشقر؟','أنتاناناريفو',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',9,5,600,'normal','ما عاصمة الصومال؟','مقديشو',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',10,0,200,'normal','ما عاصمة الكويت؟','الكويت',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',10,1,200,'normal','ما عاصمة قطر؟','الدوحة',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',10,2,400,'normal','ما عاصمة الدنمارك؟','كوبنهاغن',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',10,3,400,'normal','ما عاصمة فنلندا؟','هلسنكي',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',10,4,600,'normal','ما عاصمة جيبوتي؟','جيبوتي',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',10,5,600,'normal','ما عاصمة موريتانيا؟','نواكشوط',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',11,0,200,'normal','ما عاصمة تركيا؟','أنقرة',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',11,1,200,'normal','ما عاصمة كندا؟','أوتاوا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',11,2,400,'normal','ما عاصمة بولندا؟','وارسو',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',11,3,400,'normal','ما عاصمة التشيك؟','براغ',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',11,4,600,'normal','ما عاصمة جورجيا؟','تبليسي',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',11,5,600,'normal','ما عاصمة أرمينيا؟','يريفان',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',12,0,200,'normal','ما عاصمة أستراليا؟','كانبيرا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',12,1,200,'normal','ما عاصمة الهند؟','نيودلهي',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',12,2,400,'normal','ما عاصمة المجر؟','بودابست',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',12,3,400,'normal','ما عاصمة رومانيا؟','بوخارست',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',12,4,600,'normal','ما عاصمة أذربيجان؟','باكو',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',12,5,600,'normal','ما عاصمة قبرص؟','نيقوسيا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',13,0,200,'normal','ما عاصمة البرازيل؟','برازيليا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',13,1,200,'normal','ما عاصمة اليونان؟','أثينا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',13,2,400,'normal','ما عاصمة أوكرانيا؟','كييف',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',13,3,400,'normal','ما عاصمة أيرلندا؟','دبلن',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',13,4,600,'normal','ما عاصمة مالطا؟','فاليتا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',13,5,600,'normal','ما عاصمة جزر القمر؟','موروني',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',14,0,200,'normal','ما عاصمة سويسرا؟','بيرن',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',14,1,200,'normal','ما عاصمة السويد؟','ستوكهولم',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',14,2,400,'normal','ما عاصمة نيوزيلندا؟','ويلينغتون',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',14,3,400,'normal','ما عاصمة كولومبيا؟','بوغوتا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',14,4,600,'normal','ما عاصمة جامايكا؟','كينغستون',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',14,5,600,'normal','ما عاصمة كوبا؟','هافانا',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',15,0,200,'normal','ما عاصمة هولندا؟','أمستردام',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',15,1,200,'normal','ما عاصمة بلجيكا؟','بروكسل',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',15,2,400,'normal','ما عاصمة تشيلي؟','سانتياغو',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',15,3,400,'normal','ما عاصمة بيرو؟','ليما',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',15,4,600,'normal','ما عاصمة الفاتيكان؟','الفاتيكان',NULL,NULL,NULL,NULL,NULL,NULL),
('capitals',15,5,600,'normal','ما عاصمة جنوب أفريقيا؟','بريتوريا/كيب تاون/بلومفونتين',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',1,0,200,'normal','ما هي العملة الرسمية في الولايات المتحدة؟','الدولار الأمريكي',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',1,1,200,'normal','ما هي العملة الرسمية في الاتحاد الأوروبي؟','اليورو',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',1,2,400,'normal','ما هي العملة الرسمية في ليبيا؟','الدينار الليبي',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',1,3,400,'normal','ما هي العملة الرسمية في سوريا؟','الليرة السورية',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',1,4,600,'normal','ما هي العملة الرسمية في كازاخستان؟','التنغي',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',1,5,600,'normal','ما هي العملة الرسمية في أوزبكستان؟','السوم',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',2,0,200,'normal','ما هي العملة الرسمية في المملكة العربية السعودية؟','الريال السعودي',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',2,1,200,'normal','ما هي العملة الرسمية في اليابان؟','الين الياباني',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',2,2,400,'normal','ما هي العملة الرسمية في اليمن؟','الريال اليمني',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',2,3,400,'normal','ما هي العملة الرسمية في البحرين؟','الدينار البحريني',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',2,4,600,'normal','ما هي العملة الرسمية في منغوليا؟','التوغروغ',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',2,5,600,'normal','ما هي العملة الرسمية في نيبال؟','الروبية النيبالية',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',3,0,200,'normal','ما هي العملة الرسمية في المملكة المتحدة؟','الجنيه الإسترليني',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',3,1,200,'normal','ما هي العملة الرسمية في الصين؟','اليوان',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',3,2,400,'normal','ما هي العملة الرسمية في باكستان؟','الروبية الباكستانية',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',3,3,400,'normal','ما هي العملة الرسمية في إندونيسيا؟','الروبية الإندونيسية',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',3,4,600,'normal','ما هي العملة الرسمية في أفغانستان؟','الأفغاني',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',3,5,600,'normal','ما هي العملة الرسمية في بلغاريا؟','الليف',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',4,0,200,'normal','ما هي العملة الرسمية في مصر؟','الجنيه المصري',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',4,1,200,'normal','ما هي العملة الرسمية في تركيا؟','الليرة التركية',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',4,2,400,'normal','ما هي العملة الرسمية في الفلبين؟','البيزو الفلبيني',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',4,3,400,'normal','ما هي العملة الرسمية في تايلاند؟','البات',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',4,4,600,'normal','ما هي العملة الرسمية في إثيوبيا؟','البير',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',4,5,600,'normal','ما هي العملة الرسمية في جنوب أفريقيا؟','الراند',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',5,0,200,'normal','ما هي العملة الرسمية في الإمارات؟','الدرهم الإماراتي',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',5,1,200,'normal','ما هي العملة الرسمية في الكويت؟','الدينار الكويتي',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',5,2,400,'normal','ما هي العملة الرسمية في فيتنام؟','الدونغ',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',5,3,400,'normal','ما هي العملة الرسمية في سنغافورة؟','الدولار السنغافوري',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',5,4,600,'normal','ما هي العملة الرسمية في جورجيا؟','اللاري',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',5,5,600,'normal','ما هي العملة الرسمية في أرمينيا؟','الدرام',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',6,0,200,'normal','ما هي العملة الرسمية في لبنان؟','الليرة اللبنانية',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',6,1,200,'normal','ما هي العملة الرسمية في قطر؟','الريال القطري',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',6,2,400,'normal','ما هي العملة الرسمية في الأرجنتين؟','البيزو الأرجنتيني',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',6,3,400,'normal','ما هي العملة الرسمية في تشيلي؟','البيزو التشيلي',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',6,4,600,'normal','ما هي العملة الرسمية في أذربيجان؟','المانات',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',6,5,600,'normal','ما هي العملة الرسمية في قبرص؟','اليورو',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',7,0,200,'normal','ما هي العملة الرسمية في الأردن؟','الدينار الأردني',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',7,1,200,'normal','ما هي العملة الرسمية في كندا؟','الدولار الكندي',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',7,2,400,'normal','ما هي العملة الرسمية في كولومبيا؟','البيزو الكولومبي',NULL,NULL,NULL,NULL,NULL,NULL),
('currencies',7,3,400,'normal','ما هي العملة الرسمية في بولندا؟','الزلوتي',NULL,NULL,NULL,NULL,NULL,NULL)
on conflict(category,version,ord) do update set value=excluded.value,type=excluded.type,q=excluded.q,a=excluded.a,note=excluded.note,flag=excluded.flag,clues=excluded.clues,num=excluded.num,evidence=excluded.evidence,suspects=excluded.suspects;

commit;
