-- FAKKIR seed — part 6 of 9. Generated; do not edit by hand.
-- Run server/sql/schema.sql once, then paste these part files into the Supabase SQL Editor in order (01, 02, ...).
begin;

-- Categories (idempotent; required by the questions foreign key)
insert into categories(slug,name,color,image,sort_order) values
('geo','الجغرافيا','blue','assets/img/categories/geo.png',0),
('history','التاريخ','gold','assets/img/categories/history.png',1),
('palestine','فلسطين','green','assets/img/categories/palestine.png',2),
('seerah','السيرة النبوية','teal','assets/img/categories/seerah.png',3),
('quran','القرآن الكريم','green','assets/img/categories/quran.png',4),
('flags','أعلام الدول','red','assets/img/categories/flags.png',5),
('sports','الرياضة','cyan','assets/img/categories/sports.png',6),
('football','كرة القدم','blue','assets/img/categories/football.png',7),
('riddles','الألغاز','purple','assets/img/categories/riddles.png',8),
('science','العلوم','teal','assets/img/categories/science.png',9),
('tech','التكنولوجيا','cyan','assets/img/categories/tech.png',10),
('animals','عالم الحيوان','gold','assets/img/categories/animals.png',11),
('general','المعلومات العامة','gold','assets/img/categories/general.png',12),
('math','الرياضيات والأرقام','blue','assets/img/categories/math.png',13),
('whoami','احزر ماذا أنا','purple','assets/img/categories/whoami.png',14),
('proverbs','تكملة المثل','teal','assets/img/categories/proverbs.png',15),
('dish','ما هي الأكلة','red','assets/img/categories/dish.png',16),
('crime','الجريمة','red','assets/img/categories/crime.png',17),
('rescue','إنقاذ المتهم','green','assets/img/categories/rescue.png',18),
('closest','الأقرب إلى الرقم','purple','assets/img/categories/closest.png',19),
('capitals','عواصم الدول','blue','assets/img/categories/capitals.png',20),
('currencies','عملات الدول','gold','assets/img/categories/currencies.png',21),
('verse','أكمل الآية','green','assets/img/categories/verse.png',22),
('ordering','الترتيب الصحيح','cyan','assets/img/categories/ordering.png',23),
('players','احزر اللاعب','cyan','assets/img/categories/players.png',24)
on conflict(slug) do update set name=excluded.name,color=excluded.color,image=excluded.image,sort_order=excluded.sort_order;

-- Questions 1251..1500
insert into questions(category,version,ord,value,type,q,a,note,flag,clues,num,evidence,suspects,image) values
('math',14,2,400,'normal','ما هو ناتج $4^2 + 3^2$؟','25',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',14,3,400,'normal','كم يساوي 1 طن بالكيلوغرام؟','1000',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',14,4,600,'normal','ماذا يسمى المثلث الذي ليس له أضلاع متساوية؟','مختلف الأضلاع',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',14,5,600,'normal','ما هو ناتج قسمة أي عدد على نفسه (غير الصفر)؟','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',15,0,200,'normal','ما هو الرقم المكتوب بـ "V" في الأرقام الرومانية؟','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',15,1,200,'normal','كم نصف الـ 50؟','25',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',15,2,400,'normal','ما هو المتوسط الحسابي للأعداد 2، 4، 6؟','4',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',15,3,400,'normal','ما هو ناتج $5!$ (مضروب الـ 5)؟','120',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',15,4,600,'normal','ما هو حجم الهرم؟','$1/3 \times \text{المساحة} \times \text{الارتفاع}$',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',15,5,600,'normal','ما هو العدد الذي يسمى "العدد المثالي" الأول؟','6 (مجموع قواسمه: 1+2+3 = 6)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',1,0,200,'normal','أنا ملك الغابة وأزأر بقوة، من أنا؟','الأسد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',1,1,200,'normal','أنا أطول حيوان في العالم، وعنقي يصل للسحاب، من أنا؟','الزرافة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',1,2,400,'normal','أنا أكبر قارة في العالم، من أنا؟','آسيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',1,3,400,'normal','أنا أصغر قارة في العالم، من أنا؟','أستراليا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',1,4,600,'normal','أنا بئر في الفضاء لا يهرب مني الضوء، من أنا؟','الثقب الأسود',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',1,5,600,'normal','أنا سرعة لا يمكن تجاوزها في الكون، من أنا؟','سرعة الضوء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',2,0,200,'normal','أنا لي خرطوم طويل وجسم ضخم، من أنا؟','الفيل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',2,1,200,'normal','أنا أعيش في الصحراء وأصبر على العطش، من أنا؟','الجمل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',2,2,400,'normal','أنا أطول نهر في العالم، من أنا؟','النيل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',2,3,400,'normal','أنا أكبر محيط في الكرة الأرضية، من أنا؟','المحيط الهادئ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',2,4,600,'normal','أنا أصغر جسيم في الذرة يحمل شحنة سالبة، من أنا؟','الإلكترون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',2,5,600,'normal','أنا لغة البرمجة التي تتكون من أصفار وآحاد، من أنا؟','لغة الآلة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',3,0,200,'normal','أنا أطير في السماء ولكن ليس لدي ريش، وأعيش في الكهوف، من أنا؟','الخفاش',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',3,1,200,'normal','أنا لي ثماني أرجل وأغزل خيوطاً دقيقة، من أنا؟','العنكبوت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',3,2,400,'normal','أنا كوكب أحمر، من أنا؟','المريخ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',3,3,400,'normal','أنا الغاز الذي تتنفسه، من أنا؟','الأكسجين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',3,4,600,'normal','أنا الجزء الذي يعالج البيانات في الحاسوب، من أنا؟','المعالج CPU',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',3,5,600,'normal','أنا السجل الرقمي الذي لا يمكن تعديله، من أنا؟','البلوكشين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',4,0,200,'normal','أنا أتنفس الماء ولا أملك رئتين، من أنا؟','السمك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',4,1,200,'normal','أنا أضع البيض ولكن لست طائراً، من أنا؟','السلحفاة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',4,2,400,'normal','أنا المادة التي تعطي النبات لونه الأخضر، من أنا؟','الكلوروفيل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',4,3,400,'normal','أنا رمز للسلام في العالم، من أنا؟','الحمامة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',4,4,600,'normal','أنا قوة تجذب الأجسام لمركز الأرض، من أنا؟','الجاذبية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',4,5,600,'normal','أنا المادة التي تشكل معظم كتلة الكون ولا تُرى، من أنا؟','المادة المظلمة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',5,0,200,'normal','أنا أمتلك مئات الأرجل، من أنا؟','أم أربعة وأربعين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',5,1,200,'normal','أنا أتحول لجمال رائع بعد أن كنت دودة، من أنا؟','الفراشة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',5,2,400,'normal','أنا أصغر وحدة في المادة، من أنا؟','الذرة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',5,3,400,'normal','أنا أسرع شيء في الكون، من أنا؟','الضوء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',5,4,600,'normal','أنا النتيجة الحتمية لزيادة الفوضى في أي نظام، من أنا؟','الإنتروبيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',5,5,600,'normal','أنا الحالة الرابعة للمادة، من أنا؟','البلازما',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',6,0,200,'normal','أنا أضيء في الليل وأنا جسم سماوي، من أنا؟','القمر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',6,1,200,'normal','أنا أضيء النهار وأنا نجم كبير، من أنا؟','الشمس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',6,2,400,'normal','أنا علم يدرس النجوم والكواكب، من أنا؟','علم الفلك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',6,3,400,'normal','أنا العضو الذي يضخ الدم، من أنا؟','القلب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',6,4,600,'normal','أنا العملية التي تجعل النبات يصنع طعامه، من أنا؟','البناء الضوئي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',6,5,600,'normal','أنا الخريطة الجينية للإنسان، من أنا؟','DNA',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',7,0,200,'normal','أنا أكتب كل شيء ولكن ليس لدي أصابع، من أنا؟','القلم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',7,1,200,'normal','أنا أحمل الناس عبر البحار والمحيطات، من أنا؟','السفينة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',7,2,400,'normal','أنا المسؤول عن التفكير، من أنا؟','المخ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',7,3,400,'normal','أنا أسرع حيوان في العالم، من أنا؟','الفهد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',7,4,600,'normal','أنا التغير في التردد بسبب الحركة، من أنا؟','تأثير دوبلر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',7,5,600,'normal','أنا الجسيم المسؤول عن منح المادة كتلتها، من أنا؟','بوزون هيغز',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',8,0,200,'normal','أنا أطير في السماء ولكن محركي حديدي، من أنا؟','الطائرة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',8,1,200,'normal','أنا موجود في كل مكان وأنت لا تراني، من أنا؟','الهواء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',8,2,400,'normal','أنا أضخم كوكب في المجموعة الشمسية، من أنا؟','المشتري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',8,3,400,'normal','أنا وحدة قياس الحرارة، من أنا؟','السيليزيوس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',8,4,600,'normal','أنا العملية التي تحول السائل لغاز، من أنا؟','التبخر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',8,5,600,'normal','أنا القانون الذي يربط القوة بالكتلة والتسارع، من أنا؟','قانون نيوتن الثاني',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',9,0,200,'normal','أنا أملك مفاتيح كثيرة ولا أفتح أبواباً، من أنا؟','البيانو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',9,1,200,'normal','أنا أملك وجهاً ولكن بلا عيون، من أنا؟','الساعة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',9,2,400,'normal','أنا أرقام لا تقبل القسمة إلا على نفسها، من أنا؟','الأعداد الأولية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',9,3,400,'normal','أنا الزاوية التي قياسها 90 درجة، من أنا؟','الزاوية القائمة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',9,4,600,'normal','أنا المسافة التي يقطعها الضوء في سنة، من أنا؟','السنة الضوئية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',9,5,600,'normal','أنا الحالة التي ترتبط فيها الجسيمات لحظياً عبر المسافات، من أنا؟','التشابك الكمي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',10,0,200,'normal','أنا لي أسنان كثيرة ولكن لا أعض، من أنا؟','المشط',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',10,1,200,'normal','أنا أرتفع للسماء ولكن لا أطير، من أنا؟','الدخان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',10,2,400,'normal','أنا الشكل الذي له 4 أضلاع متساوية، من أنا؟','المربع',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',10,3,400,'normal','أنا حاصل ضرب 8 في 8، من أنا؟','64',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',10,4,600,'normal','أنا ظاهرة ابتعاد المجرات عنا، من أنا؟','الانزياح نحو الأحمر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',10,5,600,'normal','أنا الجهاز الذي يحول الإشارات الكهربائية لبيانات رقمية، من أنا؟','المودم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',11,0,200,'normal','أنا أعطيك الحليب، من أنا؟','البقرة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',11,1,200,'normal','أنا أضع العسل، من أنا؟','النحلة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',11,2,400,'normal','أنا الغاز الذي يطرده النبات، من أنا؟','الأكسجين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',11,3,400,'normal','أنا المادة الصلبة للماء، من أنا؟','الثلج',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',11,4,600,'normal','أنا الثغرة التي لا يعرفها المبرمجون، من أنا؟','Zero-day',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',11,5,600,'normal','أنا تقنية تحاكي التفكير البشري، من أنا؟','الذكاء الاصطناعي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',12,0,200,'normal','أنا أقفز كثيراً ولي جراب، من أنا؟','الكنغر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',12,1,200,'normal','أنا أعيش في الماء وأنا أذكى الحيوانات، من أنا؟','الدلفين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',12,2,400,'normal','أنا العاصمة التي تسمى مدينة الأنوار، من أنا؟','باريس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',12,3,400,'normal','أنا الدولة التي تمتلك أكبر مساحة، من أنا؟','روسيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',12,4,600,'normal','أنا الشكل الذي يكرر نفسه في الطبيعة، من أنا؟','الكسيريات Fractals',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',12,5,600,'normal','أنا العضو الذي يوازن جسمك، من أنا؟','الأذن الداخلية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',13,0,200,'normal','أنا لي قشرة صلبة وأحمي نفسي بها، من أنا؟','السلحفاة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',13,1,200,'normal','أنا أتلون حسب المكان الذي أقف عليه، من أنا؟','الحرباء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',13,2,400,'normal','أنا رمز للعملة الأوروبية، من أنا؟','اليورو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',13,3,400,'normal','أنا مخترع المصباح، من أنا؟','أديسون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',13,4,600,'normal','أنا الكائن الذي يملك 3 قلوب، من أنا؟','الأخطبوط',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',13,5,600,'normal','أنا الطريقة التي تتواصل بها النحل، من أنا؟','الرقص',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',14,0,200,'normal','أنا لي أجنحة ولا أطير، من أنا؟','النعامة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',14,1,200,'normal','أنا أحفظ ذكرياتك في صور، من أنا؟','الكاميرا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',14,2,400,'normal','أنا مكتشف الجاذبية، من أنا؟','نيوتن',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',14,3,400,'normal','أنا اللغة الأكثر انتشاراً، من أنا؟','الإنجليزية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',14,4,600,'normal','أنا البروتين الذي يحمي أظافرك، من أنا؟','الكيراتين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',14,5,600,'normal','أنا الذي يمتلك دمًا أزرق، من أنا؟','سرطان حدوة الحصان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',15,0,200,'normal','أنا أنقل صوتك عبر المسافات، من أنا؟','الهاتف',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',15,1,200,'normal','أنا أحل مشاكلك الرياضية، من أنا؟','الحاسبة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',15,2,400,'normal','أنا العضو الذي يتنفس به الإنسان، من أنا؟','الرئة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',15,3,400,'normal','أنا علم يدرس الكائنات الحية، من أنا؟','الأحياء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',15,4,600,'normal','أنا التوزيع الذي يأخذ شكل الجرس، من أنا؟','التوزيع الطبيعي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('whoami',15,5,600,'normal','أنا المعادلة التي تعتبر أجمل معادلة في الرياضيات، من أنا؟','متطابقة أويلر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',1,0,200,'normal','"الجار قبل..."؟','الدار',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',1,1,200,'normal','"الوقت كالسيف إن لم تقطعه..."؟','قطعك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',1,2,400,'normal','"عصفور في اليد خير من..."؟','عشرة على الشجرة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',1,3,400,'normal','"يسمع جعجعة ولا يرى..."؟','طحناً',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',1,4,600,'normal','"أنجز حر ما..."؟','وعد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',1,5,600,'normal','"أعطِ القوس..."؟','باريها',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',2,0,200,'normal','"العقل السليم في..."؟','الجسم السليم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',2,1,200,'normal','"في التأني السلامة وفي العجلة..."؟','الندامة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',2,2,400,'normal','"رجعت حليمة لعادتها..."؟','القديمة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',2,3,400,'normal','"مصائب قوم عند قوم..."؟','فوائد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',2,4,600,'normal','"بلغ السيل..."؟','الزبى',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',2,5,600,'normal','"أشأم من..."؟','البسوس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',3,0,200,'normal','"من جد وجد ومن..."؟','زرع حصد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',3,1,200,'normal','"الصبر مفتاح..."؟','الفرج',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',3,2,400,'normal','"من استعجل الشيء قبل أوانه..."؟','عوقب بحرمانه',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',3,3,400,'normal','"لا تمدح قبل التجربة ولا تذم قبل..."؟','المشورة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',3,4,600,'normal','"سبق السيف..."؟','العذل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',3,5,600,'normal','"إن كنت ريحاً فقد لاقيت..."؟','إعصاراً',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',4,0,200,'normal','"اليد الواحدة لا..."؟','تصفق',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',4,1,200,'normal','"خير الكلام ما..."؟','قل ودل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',4,2,400,'normal','"يداك أوكتا وفوك..."؟','نفخ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',4,3,400,'normal','"على أهلها تجني..."؟','براقش',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',4,4,600,'normal','"الصيف ضيعتِ..."؟','اللبن',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',4,5,600,'normal','"لا ناقة لي فيها ولا..."؟','جمل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',5,0,200,'normal','"رب ضارة..."؟','نافعة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',5,1,200,'normal','"على نفسها جنت..."؟','براقش',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',5,2,400,'normal','"أسمع جعجعة ولا أرى..."؟','طحناً',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',5,3,400,'normal','"لا يلدغ المؤمن من جحر..."؟','مرتين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',5,4,600,'normal','"مقتل الرجل بين..."؟','فكيه',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',5,5,600,'normal','"أوردها سعد وسعد مشتمل..."؟','ما هكذا يا سعد تورد الإبل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',6,0,200,'normal','"الوقاية خير من..."؟','العلاج',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',6,1,200,'normal','"ليس كل ما يلمع..."؟','ذهباً',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',6,2,400,'normal','"رب أخ لك لم تلده..."؟','أمك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',6,3,400,'normal','"البعرة تدل على البعير والأثر يدل على..."؟','المسير',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',6,4,600,'normal','"أسمع منك أتعجب.. أنظر إليك..."؟','أصدق',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',6,5,600,'normal','"جزاء مِمار..."؟','قيل في الغدر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',7,0,200,'normal','"من طمع في الكل..."؟','ضيع الكل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',7,1,200,'normal','"اتقِ شر من..."؟','أحسنت إليه',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',7,2,400,'normal','"أشارت بطرف العين خيفة أهلها..."؟','إشارة محزون ولم تتكلم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',7,3,400,'normal','"خالف تُعرف..."؟','وتشتهر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',7,4,600,'normal','"أسمع جعجعةً ولا أرى..."؟','طحناً',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',7,5,600,'normal','"أخلف من وعد..."؟','العرقوب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',8,0,200,'normal','"الباب الذي يأتيك منه الريح..."؟','سده واستريح',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',8,1,200,'normal','"الاعتراف بالحق..."؟','فضيلة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',8,2,400,'normal','"السكوت علامة..."؟','الرضا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',8,3,400,'normal','"بين حانا ومانا ضيعنا..."؟','لحانا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',8,4,600,'normal','"أذل من..."؟','وتد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',8,5,600,'normal','"أصدق من..."؟','قُس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',9,0,200,'normal','"حبل الكذب..."؟','قصير',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',9,1,200,'normal','"لا تؤجل عمل اليوم إلى..."؟','الغد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',9,2,400,'normal','"وافق شن طبقة..."؟','فاعتنقا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',9,3,400,'normal','"جزاء سنمار..."؟','القتل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',9,4,600,'normal','"أغنى من..."؟','قارون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',9,5,600,'normal','"أحمق من..."؟','هبنقة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',10,0,200,'normal','"طولك طول نخلة وعقلك..."؟','عقل صخلة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',10,1,200,'normal','"القناعة كنز..."؟','لا يفنى',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',10,2,400,'normal','"أنا ومن بعدي..."؟','الطوفان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',10,3,400,'normal','"تيتي تيتي مثل ما رحتي مثل ما..."؟','جيتي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',10,4,600,'normal','"أشبه من..."؟','النعل بالنعل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',10,5,600,'normal','"أبصر من..."؟','زرقاء اليمامة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',11,0,200,'normal','"إذا كان الكلام من فضة فالسكوت من..."؟','ذهب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',11,1,200,'normal','"يأكل مع الذئب ويبكي مع..."؟','الراعي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',11,2,400,'normal','"من حفر حفرة لأخيه..."؟','وقع فيها',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',11,3,400,'normal','"اللي ما يعرف الصقر..."؟','يشويه',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',11,4,600,'normal','"أمنع من..."؟','عقر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',11,5,600,'normal','"أشقى من..."؟','عاقر ناقة صالح',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',12,0,200,'normal','"مكره أخاك..."؟','لا بطل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',12,1,200,'normal','"من خرج من داره..."؟','قل مقداره',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',12,2,400,'normal','"كل فولة ولها..."؟','كيال',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',12,3,400,'normal','"اقلب القدرة على فمها تطلع البنت..."؟','لأمها',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',12,4,600,'normal','"أجود من..."؟','حاتم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',12,5,600,'normal','"أعدل من..."؟','عمر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',13,0,200,'normal','"الطيور على أشكالها..."؟','تقع',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',13,1,200,'normal','"لا تضع البيض كله في..."؟','سلة واحدة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',13,2,400,'normal','"اللي ما يطول العنب حامضاً عنه..."؟','يقول',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',13,3,400,'normal','"لا حياة مع اليأس ولا يأس مع..."؟','الحياة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',13,4,600,'normal','"أدعى من..."؟','هند',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',13,5,600,'normal','"أسرع من..."؟','لمح البصر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',14,0,200,'normal','"من راقب الناس..."؟','مات هماً',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',14,1,200,'normal','"أهل مكة أدرى..."؟','بشعابها',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',14,2,400,'normal','"عند الامتحان يكرم المرء أو..."؟','يهان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',14,3,400,'normal','"من كثر كلامه كثر..."؟','خطؤه',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',14,4,600,'normal','"أبخل من..."؟','مادر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',14,5,600,'normal','"أكذب من..."؟','مسيلمة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',15,0,200,'normal','"إن غداً لناظره..."؟','قريب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',15,1,200,'normal','"تجري الرياح بما لا تشتهي..."؟','السفن',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',15,2,400,'normal','"الظلم ظلمات..."؟','يوم القيامة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',15,3,400,'normal','"إذا جاء الشتاء فأين المفر..."؟','من البرد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',15,4,600,'normal','"أوفى من..."؟','السموال',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('proverbs',15,5,600,'normal','"أبصر من..."؟','الغراب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',1,0,200,'normal','ما هي الأكلة الإيطالية المكونة من عجينة وعليها صلصة وجبن؟','البيتزا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',1,1,200,'normal','ما هو الطبق الياباني المكون من أرز وسمك نيئ؟','السوشي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',1,2,400,'normal','ما هي الأكلة التي تتكون من لحم مطبوخ مع بطاطس في قدر؟','اليخنة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',1,3,400,'normal','ما هو الطبق المكون من بيض مخفوق؟','الأومليت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',1,4,600,'normal','ما هي الأكلة التي تتطلب تخمير العجين لأيام؟','عجينة السوردو - Sourdough',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',1,5,600,'normal','ما هو الطبق المكون من طيور صغيرة محشوة؟','سمان محشي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',2,0,200,'normal','ما هي الأكلة العربية الشهيرة المكونة من بقدونس وبرغل؟','التبولة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',2,1,200,'normal','ما هو الطبق المكسيكي المكون من خبز التورتيلا واللحم؟','التاكو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',2,2,400,'normal','ما هي الأكلة المكونة من عجينة هشة ومحشوة بالتفاح؟','فطيرة التفاح',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',2,3,400,'normal','ما هو الطبق الإيطالي الذي يتكون من طبقات مكرونة وجبن؟','اللازانيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',2,4,600,'normal','ما هي الأكلة التي تحتوي على 7 أنواع من التوابل؟','السبع بهارات - تُستخدم في معظم الأطباق العربية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',2,5,600,'normal','ما هو الطبق الذي يُطهى في قدر فخاري؟','الطاجن',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',3,0,200,'normal','ما هي الأكلة الشعبية في مصر المكونة من عدس وأرز ومكرونة؟','الكشري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',3,1,200,'normal','ما هو الطبق الذي يُعرف بـ "ملك المائدة" في الهند؟','البرياني',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',3,2,400,'normal','ما هي الأكلة التي تتكون من عجينة محشوة بجبن وتُخبز؟','المناقيش',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',3,3,400,'normal','ما هو الطبق المكون من أرز وسمك؟','الصيادية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',3,4,600,'normal','ما هي الأكلة التي تُصنع من دهن الحيوان؟','القاورما',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',3,5,600,'normal','ما هو الطبق المكون من أمعاء الحيوان المحشوة؟','الممبار',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',4,0,200,'normal','ما هي الأكلة الإيطالية المكونة من عجين مسلوق مع صلصة؟','المكرونة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',4,1,200,'normal','ما هو الطبق الإسباني الشهير المكون من أرز ومأكولات بحرية؟','الباييلا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',4,2,400,'normal','ما هي الأكلة المكونة من خضار مشوية ومهروسة مع طحينة؟','بابا غنوج',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',4,3,400,'normal','ما هو الطبق المكون من كرات من اللحم بصلصة طماطم؟','داوود باشا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',4,4,600,'normal','ما هي الأكلة التي تتكون من أقدام حيوان؟','الكوارع',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',4,5,600,'normal','ما هو الطبق الذي يُعد من الفاكهة المطبوخة بالسكر؟','المربى',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',5,0,200,'normal','ما هي الأكلة الأمريكية المكونة من خبز ولحم وجبن؟','البرجر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',5,1,200,'normal','ما هو الطبق اللبناني المصنوع من لحم وبرغل؟','الكبة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',5,2,400,'normal','ما هي الأكلة التي تتكون من شرائح لحم بصلصة الفطر؟','ستيك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',5,3,400,'normal','ما هو الطبق المكون من دجاج مشوي على الفحم؟','مشاوي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',5,4,600,'normal','ما هي الأكلة التي تتكون من عجينة مخبوزة على الصاج؟','الخبز',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',5,5,600,'normal','ما هو الطبق الذي يوضع فيه اللحم ليطبخ على البخار؟','قدر بخاري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',6,0,200,'normal','ما هي الأكلة التركية التي تتكون من لحم مشوي على سيخ؟','الشاورما',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',6,1,200,'normal','ما هو الطبق الفرنسي المكون من خضار مطبوخة؟','راتاتوي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',6,2,400,'normal','ما هي الأكلة المكونة من أرز وعدس؟','المجدرة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',6,3,400,'normal','ما هو الطبق المكون من عجينة مقلية وعليها قطر؟','العوامة أو اللقيمات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',6,4,600,'normal','ما هي الأكلة التي تتكون من سمك مطبوخ مع طحينة؟','سمك بالطحينة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',6,5,600,'normal','ما هو الطبق المكون من أرز يُسقى بالمرق؟','فتة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',7,0,200,'normal','ما هي الأكلة التي تشتهر بها الصين وتُطهى على البخار؟','الدمبلينغ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',7,1,200,'normal','ما هو الطبق العربي المكون من أرز ولحم ولبن؟','المنسف',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',7,2,400,'normal','ما هي الأكلة المكونة من خضار مسلوقة ومقطعة؟','سلطة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',7,3,400,'normal','ما هو الطبق المكون من كبدة مقلية؟','كبدة مشوية أو مقلية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',7,4,600,'normal','ما هي الأكلة التي تتكون من كرات العجين المحشوة جبن؟','رافيولي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',7,5,600,'normal','ما هو الطبق المكون من كبدة وطحال؟','حلويات المدبح',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',8,0,200,'normal','ما هي الأكلة المكونة من عجين محشو باللحم ومطبوخ باللبن؟','الشيش برك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',8,1,200,'normal','ما هو الطبق الفرنسي المشهور والمصنوع من عجينة رقيقة؟','الكريب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',8,2,400,'normal','ما هي الأكلة المكونة من سمك مشوي؟','سمك مشوي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',8,3,400,'normal','ما هو الطبق المكون من عجينة محشوة لحم ومخبوزة؟','اللحم بعجين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',8,4,600,'normal','ما هي الأكلة التي تتكون من طبقات خبز وبصل ولحم؟','مسخن',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',8,5,600,'normal','ما هو الطبق الذي يُعد من الحبوب المسلوقة؟','البليلة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',9,0,200,'normal','ما هي الأكلة اليونانية المكونة من باذنجان ولحم مفروم؟','المسقعة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',9,1,200,'normal','ما هو الطبق الإيطالي المكون من أرز مطبوخ بمرق؟','الريزوتو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',9,2,400,'normal','ما هي الأكلة المكونة من دجاج مقلي؟','البروستد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',9,3,400,'normal','ما هو الطبق المكون من أرز وبازلاء وجزر؟','أرز بالخضار',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',9,4,600,'normal','ما هي الأكلة التي تتكون من عجينة مقلية ومحشوة بحلو؟','القطايف',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',9,5,600,'normal','ما هو الطبق الذي يُعد من عجينة ومكسرات؟','بقلاوة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',10,0,200,'normal','ما هي الأكلة الشعبية في بلاد الشام والمصنوعة من الحمص؟','الحمص بالطحينة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',10,1,200,'normal','ما هو الطبق التايلاندي المكون من نودلز وفول سوداني؟','باد تاي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',10,2,400,'normal','ما هي الأكلة المكونة من عجينة ومربى؟','تارت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',10,3,400,'normal','ما هو الطبق المكون من عدس مطحون؟','شوربة عدس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',10,4,600,'normal','ما هي الأكلة التي تتكون من أرز وجمبري؟','أرز بالجمبري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('dish',10,5,600,'normal','ما هو الطبق المكون من خضار مخبوزة؟','غراتان',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
on conflict(category,version,ord) do update set value=excluded.value,type=excluded.type,q=excluded.q,a=excluded.a,note=excluded.note,flag=excluded.flag,clues=excluded.clues,num=excluded.num,evidence=excluded.evidence,suspects=excluded.suspects,image=excluded.image;

commit;
