-- FAKKIR seed — part 5 of 9. Generated; do not edit by hand.
-- Run server/sql/schema.sql once, then paste these part files into the Supabase SQL Editor in order (01, 02, ...).
begin;

-- Categories (idempotent; required by the questions foreign key)
insert into categories(slug,name,color,image,sort_order) values
('geo','الجغرافيا','blue','assets/img/categories/geo.png',0),
('history','التاريخ','gold','assets/img/categories/history.png',1),
('palestine','فلسطين','green','assets/img/categories/palestine.png',2),
('seerah','السيرة النبوية','teal','assets/img/categories/seerah.png',3),
('quran','القرآن الكريم','green','assets/img/categories/quran.png',4),
('flags','أعلام الدول','red','assets/img/categories/flags.png',5),
('sports','الرياضة','cyan','assets/img/categories/sports.png',6),
('football','كرة القدم','blue','assets/img/categories/football.png',7),
('riddles','الألغاز','purple','assets/img/categories/riddles.png',8),
('science','العلوم','teal','assets/img/categories/science.png',9),
('tech','التكنولوجيا','cyan','assets/img/categories/tech.png',10),
('animals','عالم الحيوان','gold','assets/img/categories/animals.png',11),
('general','المعلومات العامة','gold','assets/img/categories/general.png',12),
('math','الرياضيات والأرقام','blue','assets/img/categories/math.png',13),
('whoami','احزر ماذا أنا','purple','assets/img/categories/whoami.png',14),
('proverbs','تكملة المثل','teal','assets/img/categories/proverbs.png',15),
('dish','ما هي الأكلة','red','assets/img/categories/dish.png',16),
('crime','الجريمة','red','assets/img/categories/crime.png',17),
('rescue','إنقاذ المتهم','green','assets/img/categories/rescue.png',18),
('closest','الأقرب إلى الرقم','purple','assets/img/categories/closest.png',19),
('capitals','عواصم الدول','blue','assets/img/categories/capitals.png',20),
('currencies','عملات الدول','gold','assets/img/categories/currencies.png',21),
('verse','أكمل الآية','green','assets/img/categories/verse.png',22),
('ordering','الترتيب الصحيح','cyan','assets/img/categories/ordering.png',23),
('players','احزر اللاعب','cyan','assets/img/categories/players.png',24)
on conflict(slug) do update set name=excluded.name,color=excluded.color,image=excluded.image,sort_order=excluded.sort_order;

-- Questions 1001..1250
insert into questions(category,version,ord,value,type,q,a,note,flag,clues,num,evidence,suspects,image) values
('animals',2,4,600,'normal','ما هو الحيوان الذي يلقب بـ "الوشق"؟','الوشق',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',2,5,600,'normal','ما هو الحيوان الذي يمتلك عيناً واحدة في الحقيقة (كائنات دقيقة)؟','مجدافيات الأرجل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',3,0,200,'normal','ما الحيوان الذي يحمل صغيره في جراب على بطنه؟','الكنغر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',3,1,200,'normal','ما الحيوان الذي يغير لونه حسب البيئة؟','الحرباء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',3,2,400,'normal','ما هو الحيوان الذي يمتلك أقوى عضة في عالم الحيوان؟','التمساح',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',3,3,400,'normal','ما هو الحيوان الذي يلقب بـ "أبو مقص"؟','السرطان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',3,4,600,'normal','ما هو الحيوان الذي يمتلك أقوى حاسة بصر؟','النسر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',3,5,600,'normal','ما هو الحيوان الذي يتنفس عن طريق الجلد؟','الضفدع',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',4,0,200,'normal','ما هو أسرع حيوان بري في العالم؟','الفهد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',4,1,200,'normal','ما الحيوان الذي ينام مقلوباً؟','الخفاش',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',4,2,400,'normal','ما هو الحيوان الذي يرضع صغاره وهو كائن بحري؟','الحوت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',4,3,400,'normal','ما هو الحيوان الذي يمتلك طويلاً جداً ويشبه الثعبان؟','ثعبان البحر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',4,4,600,'normal','ما هو الحيوان الذي يمتلك أكثر من 1000 قدم؟','أم أربعة وأربعين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',4,5,600,'normal','ما هو الحيوان الذي يمتلك فراءً أبيض في الشتاء وبنياً في الصيف؟','الأرنب القطبي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',5,0,200,'normal','ما هو الحيوان الذي يغطي جسمه الشوك؟','القنفذ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',5,1,200,'normal','ما الحيوان الذي يمتلك قرناً واحداً على أنفه؟','وحيد القرن',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',5,2,400,'normal','ما هو الحيوان الذي يعيش في مجموعات تسمى "مستعمرات"؟','النمل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',5,3,400,'normal','ما هو الحيوان الذي يشبه الفأر لكنه يعيش في الأشجار؟','السنجاب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',5,4,600,'normal','ما هو الحيوان الذي يعيش في أعماق البحار ويصدر ضوءاً؟','سمكة أبو الشص',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',5,5,600,'normal','ما هو الحيوان الذي لديه القدرة على إطلاق الكهرباء للصيد؟','الرعاد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',6,0,200,'normal','ما هو أبطأ حيوان ثديي؟','الكسلان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',6,1,200,'normal','ما الحيوان الذي يضرب به المثل في الصبر والتحمل؟','الحمار',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',6,2,400,'normal','ما هو الحيوان الذي يغير جلده بانتظام؟','الثعبان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',6,3,400,'normal','ما هو الحيوان الذي يمتلك القدرة على الطيران وهو من الثدييات؟','الخفاش',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',6,4,600,'normal','ما هو الحيوان الذي يمتلك "حويصلة" لهضم الطعام؟','الدجاجة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',6,5,600,'normal','ما هو الحيوان الذي يمتلك أطول فترة حمل؟','الفيل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',7,0,200,'normal','ما هو الحيوان الذي يصنف من القوارض ويحب الجبن؟','الفأر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',7,1,200,'normal','ما الحيوان الذي يلقب بـ "الرجل الخفي" في الغابة؟','النمر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',7,2,400,'normal','ما هو الحيوان الذي يسمى "ملك" في المحيطات؟','القرش',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',7,3,400,'normal','ما هو الحيوان الذي يعيش في الصحراء ويخزن الماء في سنامه؟','الجمل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',7,4,600,'normal','ما هو الحيوان الذي لا يمتلك معدة على الإطلاق؟','خيار البحر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',7,5,600,'normal','ما هو الحيوان الذي يمتلك دمًا أزرق اللون؟','سرطان حدوة الحصان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',8,0,200,'normal','ما هو الحيوان الذي تراه في الأفلام يجمع الموز؟','القرد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',8,1,200,'normal','ما الحيوان الذي لديه حاسة شم قوية ويساعد الشرطة؟','الكلب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',8,2,400,'normal','ما هو الحيوان الذي يمتلك أطول لسان؟','آكل النمل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',8,3,400,'normal','ما هو الحيوان الذي يمتلك ريشاً لكنه لا يطير؟','النعامة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',8,4,600,'normal','ما هو الحيوان الذي ينام وهو واقف؟','الحصان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',8,5,600,'normal','ما هو الحيوان الذي يمتلك حاسة السمع في أرجله؟','الجرادة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',9,0,200,'normal','ما الحيوان الذي لديه خرطوم طويل؟','الفيل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',9,1,200,'normal','ما الحيوان الذي يغطي جسمه الصوف ونأخذ منه الحليب؟','الخروف',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',9,2,400,'normal','ما هو الحيوان الذي يرتدي "فراءً" مضاداً للماء؟','ثعلب الماء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',9,3,400,'normal','ما هو الحيوان الذي لديه قدرة عالية على القفز؟','الكنغر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',9,4,600,'normal','ما هو الحيوان الذي يمتلك القدرة على تحويل الملح إلى مياه عذبة؟','طيور البحر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',9,5,600,'normal','ما هو الحيوان الذي يمتلك أسناناً تنمو باستمرار؟','القندس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',10,0,200,'normal','ما هو أذكى حيوان بحري؟','الدلفين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',10,1,200,'normal','ما الحيوان الذي يلقب بالحيوان الوديع ونأخذ منه اللبن؟','البقرة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',10,2,400,'normal','ما هو الحيوان الذي يمتلك أنياباً طويلة (أنياب عاجية)؟','الفيل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',10,3,400,'normal','ما هو الحيوان الذي يمتلك جسماً انسيابياً ويشبه السمك؟','التونة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',10,4,600,'normal','ما هو الحيوان الذي يمتلك قلباً يزن 180 كيلوغراماً؟','الحوت الأزرق',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',10,5,600,'normal','ما هو الحيوان الذي يمتلك عيوناً لا تتحرك في محجرها؟','البومة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',11,0,200,'normal','ما الحيوان الذي يرتدي "بيجامة" مخططة بالأبيض والأسود؟','حمار وحشي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',11,1,200,'normal','ما الحيوان الذي يمتلك بصمات أصابع تشبه الإنسان؟','الكوالا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',11,2,400,'normal','ما هو الحيوان الذي يمتلك عيوناً واسعة للرؤية الليلية؟','البومة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',11,3,400,'normal','ما هو الحيوان الذي يمتلك أرجلاً تشبه أذرع العنكبوت؟','العنكبوت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',11,4,600,'normal','ما هو الحيوان الذي يمتلك غددًا سامة في أطرافه؟','الخلد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',11,5,600,'normal','ما هو الحيوان الذي يمكنه العيش بدون رأس لعدة أيام؟','الصراصير',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',12,0,200,'normal','ما هو الحيوان الذي يتغذى على الخيزران؟','الباندا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',12,1,200,'normal','ما الحيوان الذي يمتلك حوافر ويستخدم في السباق؟','الحصان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',12,2,400,'normal','ما هو الحيوان الذي يلقب بـ "سيد الأنهار"؟','التمساح',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',12,3,400,'normal','ما هو الحيوان الذي يمتلك صدفة قاسية؟','السلحفاة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',12,4,600,'normal','ما هو الحيوان الذي يمتلك أغلى أنواع الفراء؟','الشنشيلة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',12,5,600,'normal','ما هو الحيوان الذي يمتلك جهازاً تنفسياً يعتمد على "الكتاب الرئوي"؟','العنكبوت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',13,0,200,'normal','ما الحيوان الذي يسبح في الماء بجسم ضخم ويغطي جسمه الجلد السميك؟','فرس النهر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',13,1,200,'normal','ما هو الحيوان الذي يشبه القط ولكن حجمه أكبر بكثير؟','الأسد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',13,2,400,'normal','ما هو الحيوان الذي يشبه الخنزير لكنه يعيش في الغابة؟','الخنزير البري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',13,3,400,'normal','ما هو الحيوان الذي يشبه الغزال ولكن قرونه ثابتة؟','الظبي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',13,4,600,'normal','ما هو الحيوان الذي يمكنه سماع أصوات لا يسمعها الإنسان؟','الخفاش',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',13,5,600,'normal','ما هو الحيوان الذي يمتلك غشاءً في عينه لرؤية الماء؟','التمساح',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',14,0,200,'normal','ما هو الحيوان الذي تراه دائماً في القطبين وسط الثلج؟','الدب القطبي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',14,1,200,'normal','ما الحيوان الذي يمتلك ذيلاً طويلاً جداً ويقفز بين الأشجار؟','السنجاب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',14,2,400,'normal','ما هو الحيوان الذي يلقب بـ "ابن آوى"؟','الثعلب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',14,3,400,'normal','ما هو الحيوان الذي يتغذى على النمل الأبيض؟','آكل النمل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',14,4,600,'normal','ما هو الحيوان الذي يمتلك أقوى قوة دفع في الماء؟','القرش',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',14,5,600,'normal','ما هو الحيوان الذي يمتلك قدرة على الرؤية في الظلام الدامس؟','البومة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',15,0,200,'normal','ما هو الحيوان الذي يعيش في جحور؟','الأرنب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',15,1,200,'normal','ما هو الحيوان الذي يمتلك أصغر حجم بين الحيوانات الأليفة في البيت؟','الهامستر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',15,2,400,'normal','ما هو الحيوان الذي يمتلك عنقاً قصيراً وجسماً ضخماً؟','فرس النهر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',15,3,400,'normal','ما هو الحيوان الذي يمتلك حوافر ويعيش في الجبال؟','الماعز الجبلي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',15,4,600,'normal','ما هو الحيوان الذي يمتلك أذرعاً لا تنتهي؟','الأخطبوط',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',15,5,600,'normal','ما هو الحيوان الذي يغير لون دمه حسب نوع الغذاء؟','دودة الأرض',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',1,0,200,'normal','ما هي عاصمة فرنسا؟','باريس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',1,1,200,'normal','ما هو أكبر محيط في العالم؟','المحيط الهادئ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',1,2,400,'normal','ما هو العنصر الكيميائي الذي يرمز له بـ O؟','الأكسجين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',1,3,400,'normal','في أي عام بدأت الحرب العالمية الأولى؟','1914',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',1,4,600,'normal','ما هو اسم أول حاسوب إلكتروني في العالم؟','إينياك (ENIAC)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',1,5,600,'normal','ما هي الدولة التي لديها أكبر عدد من الجزر في العالم؟','السويد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',2,0,200,'normal','كم عدد قارات العالم؟','سبع قارات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',2,1,200,'normal','ما هو أطول نهر في العالم؟','نهر النيل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',2,2,400,'normal','ما هي المدينة التي تُعرف بمدينة الضباب؟','لندن',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',2,3,400,'normal','من هو العالم الذي اكتشف الجاذبية؟','إسحاق نيوتن',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',2,4,600,'normal','ما هو القانون العلمي الذي يربط بين الكتلة والطاقة (E=mc²)؟','قانون أينشتاين (النسبية)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',2,5,600,'normal','ما اسم أعمق نقطة في محيطات العالم؟','خندق ماريانا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',3,0,200,'normal','في أي دولة تقع الأهرامات؟','مصر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',3,1,200,'normal','ما هي العملة الرسمية في اليابان؟','الين الياباني',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',3,2,400,'normal','ما هي الدولة التي تمتلك أكبر عدد من السكان في العالم؟','الهند',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',3,3,400,'normal','ماذا تعني كلمة "سيكولوجية"؟','علم النفس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',3,4,600,'normal','من هو المهندس المعماري الذي صمم برج إيفل؟','غوستاف إيفل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',3,5,600,'normal','ما هي الدولة التي كانت تُعرف سابقاً باسم "فارس"؟','إيران',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',4,0,200,'normal','من هو مخترع المصباح الكهربائي؟','توماس أديسون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',4,1,200,'normal','ما هو لون العلم الذي يرمز للسلام؟','الأبيض',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',4,2,400,'normal','ما هو أطول سلسلة جبال في العالم؟','جبال الأنديز',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',4,3,400,'normal','ما اسم القناة التي تربط البحر الأحمر بالبحر المتوسط؟','قناة السويس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',4,4,600,'normal','ما هي المادة الأكثر صلابة في الطبيعة؟','الألماس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',4,5,600,'normal','في أي مدينة يقع مقر الأمم المتحدة الرئيسي؟','نيويورك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',5,0,200,'normal','كم يوماً في السنة الكبيسة؟','366 يوماً',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',5,1,200,'normal','ما هي أكبر دولة في العالم من حيث المساحة؟','روسيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',5,2,400,'normal','من هو مؤلف رواية "البؤساء"؟','فيكتور هوغو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',5,3,400,'normal','ما هو الرمز الكيميائي للماء؟','H2O',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',5,4,600,'normal','ما هو اسم أكبر كوكب في المجموعة الشمسية؟','المشتري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',5,5,600,'normal','ماذا تعني كلمة "تكنوقراط"؟','الحكم بواسطة الخبراء والتقنيين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',6,0,200,'normal','ما هي اللغة الأكثر تحدثاً في العالم؟','الإنجليزية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',6,1,200,'normal','من هو الرسام الذي رسم لوحة الموناليزا؟','ليوناردو دا فينشي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',6,2,400,'normal','كم عدد ولايات الولايات المتحدة الأمريكية؟','50 ولاية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',6,3,400,'normal','ما هي أصغر دولة في العالم؟','الفاتيكان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',6,4,600,'normal','ما هي الدولة التي تمتلك أكبر احتياطي من النفط في العالم؟','فنزويلا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',6,5,600,'normal','ما هو اسم العالم الذي وضع قوانين الوراثة؟','غريغور مندل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',7,0,200,'normal','في أي قارة تقع دولة البرازيل؟','أمريكا الجنوبية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',7,1,200,'normal','ما هو أضخم كوكب في المجموعة الشمسية؟','المشتري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',7,2,400,'normal','ما هو اسم الغاز الذي يستخدم في إطفاء الحرائق؟','ثاني أكسيد الكربون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',7,3,400,'normal','في أي بلد تقع مدينة "ماتشو بيتشو"؟','بيرو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',7,4,600,'normal','ما هو اسم البروتين الموجود في الشعر والأظافر؟','الكيراتين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',7,5,600,'normal','ما هي الدولة التي تُعرف بـ "أرض الشمس المشرقة"؟','اليابان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',8,0,200,'normal','ما هي عاصمة المملكة العربية السعودية؟','الرياض',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',8,1,200,'normal','ما هو الغاز الذي نستخدمه في التنفس؟','الأكسجين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',8,2,400,'normal','من هو مخترع الهاتف؟','ألكسندر غراهام بيل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',8,3,400,'normal','ما هو العضو الوحيد الذي لا يتوقف عن النمو في جسم الإنسان؟','الأنف والأذنان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',8,4,600,'normal','ما هو أطول جسر معلق في العالم حالياً؟','جسر "تشاناكالي 1915" (تركيا)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',8,5,600,'normal','من هي المرأة التي حصلت على جائزة نوبل مرتين في مجالين مختلفين؟','ماري كوري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',9,0,200,'normal','كم عدد أصابع اليد الواحدة للإنسان؟','خمسة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',9,1,200,'normal','ما هو الكتاب السماوي الذي أنزل على المسلمين؟','القرآن الكريم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',9,2,400,'normal','كم تبلغ سرعة الضوء التقريبية؟','300,000 كم/ثانية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',9,3,400,'normal','ما هي الدولة التي تسمى "بلد المليون شهيد"؟','الجزائر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',9,4,600,'normal','ما هي الدولة التي كانت تحكم الهند قبل الاستقلال؟','بريطانيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',9,5,600,'normal','ما هو اسم أكبر بحيرة عذبة في العالم من حيث الحجم؟','بحيرة بايكال',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',10,0,200,'normal','ما اسم الكوكب الذي نعيش عليه؟','الأرض',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',10,1,200,'normal','ما هو أسرع حيوان بري؟','الفهد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',10,2,400,'normal','ماذا نسمي الغابة التي تقع في حوض نهر الأمازون؟','غابات الأمازون المطيرة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',10,3,400,'normal','ما اسم الآلة الموسيقية التي تتكون من 88 مفتاحاً؟','البيانو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',10,4,600,'normal','ماذا نسمي دراسة الأحافير والكائنات القديمة؟','علم الحفريات (Paleontology)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',10,5,600,'normal','ما هي الدولة التي تمتلك أكبر مساحة من الغابات الاستوائية؟','البرازيل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',11,0,200,'normal','كم عدد كواكب المجموعة الشمسية؟','ثمانية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',11,1,200,'normal','ما هو العضو المسؤول عن التفكير لدى الإنسان؟','المخ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',11,2,400,'normal','ما هو الاسم القديم لمدينة إسطنبول؟','القسطنطينية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',11,3,400,'normal','في أي قارة تقع الصحراء الكبرى؟','أفريقيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',11,4,600,'normal','ما هو اسم الغاز الذي يستخدم في مصابيح النيون؟','غاز النيون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',11,5,600,'normal','في أي عام سقط جدار برلين؟','1989',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',12,0,200,'normal','ما هي أكبر حاسة عند الإنسان؟','اللمس (الجلد)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',12,1,200,'normal','من هو مؤسس الدولة السعودية الأولى؟','الإمام محمد بن سعود',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',12,2,400,'normal','ما هو الغاز الذي يشكل الجزء الأكبر من الغلاف الجوي؟','النيتروجين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',12,3,400,'normal','من هو أول رائد فضاء في التاريخ؟','يوري غاغارين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',12,4,600,'normal','ما هو اسم أقدم مدينة مأهولة بالسكان في العالم؟','دمشق (أو أريحا حسب بعض المصادر)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',12,5,600,'normal','ما هو اسم العضلة الأقوى في جسم الإنسان بالنسبة لحجمها؟','عضلة الفك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',13,0,200,'normal','ما هي عاصمة لبنان؟','بيروت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',13,1,200,'normal','كم عدد فصول السنة؟','أربعة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',13,2,400,'normal','ما هي أكبر جزيرة في العالم؟','غرينلاند',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',13,3,400,'normal','ماذا نسمي عملية تحول السائل إلى غاز؟','التبخر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',13,4,600,'normal','ماذا يعني مصطلح "التضخم" في الاقتصاد؟','انخفاض القوة الشرائية للعملة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',13,5,600,'normal','ما هو اسم الطائر الوحيد الذي يستطيع الطيران للخلف؟','طائر الطنان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',14,0,200,'normal','ما هو المعدن الذي يكون سائلاً في درجة الحرارة العادية؟','الزئبق',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',14,1,200,'normal','ما هو الطائر الذي يرمز للحكمة؟','البومة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',14,2,400,'normal','من هو الشاعر الملقب بـ "أمير الشعراء"؟','أحمد شوقي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',14,3,400,'normal','ما هي الدولة التي تقع فيها مدينة مراكش؟','المغرب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',14,4,600,'normal','ما هي الدولة التي يمر بها خط الاستواء وتعتبر من دول أمريكا الجنوبية؟','الإكوادور',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',14,5,600,'normal','من هو الفيلسوف اليوناني الذي كان معلم الإسكندر الأكبر؟','أرسطو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',15,0,200,'normal','ما هو اسم العملة التي تستخدم في الاتحاد الأوروبي؟','اليورو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',15,1,200,'normal','ماذا نسمي صغار الضفادع؟','أبو ذنيبة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',15,2,400,'normal','كم عدد حروف اللغة العربية؟','28 حرفاً',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',15,3,400,'normal','ما هي الوحدة المستخدمة لقياس شدة الصوت؟','الديسيبل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',15,4,600,'normal','ما هو اسم المادة الكيميائية التي تجعل الفلفل حاراً؟','الكابسيسين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('general',15,5,600,'normal','ما هي الدولة العربية التي لا يمر بها أي نهر؟','السعودية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',1,0,200,'normal','ما هو ناتج 5 + 7؟','12',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',1,1,200,'normal','ما هو ناتج 9 × 8؟','72',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',1,2,400,'normal','ما هو مجموع زوايا المثلث؟','180 درجة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',1,3,400,'normal','ما هو ناتج (-5) + 8؟','3',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',1,4,600,'normal','ما هي متتالية فيبوناتشي؟','متتالية كل حد فيها هو مجموع الحدين السابقين (0، 1، 1، 2، 3، 5...)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',1,5,600,'normal','ما هو ناتج $\int 2x \, dx$؟','$x^2 + C$',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',2,0,200,'normal','كم تساوي قيمة الزاوية القائمة؟','90 درجة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',2,1,200,'normal','ما هو العدد الأولي الوحيد الزوجي؟','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',2,2,400,'normal','إذا كان $x + 5 = 12$، فما قيمة $x$؟','7',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',2,3,400,'normal','ما هو مساحة المستطيل الذي طوله 5 وعرضه 4؟','20',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',2,4,600,'normal','ما هي قيمة $i^2$ (حيث $i$ الوحدة التخيلية)؟','-1',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',2,5,600,'normal','ما هو العدد الذهبي ($\phi$)؟','حوالي 1.618',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',3,0,200,'normal','كم عدد أضلاع الشكل السداسي؟','6',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',3,1,200,'normal','ما هو ناتج 100 ÷ 4؟','25',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',3,2,400,'normal','ما هو العدد الكسري 1/2 كنسبة مئوية؟','50%',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',3,3,400,'normal','كم يساوي $3^3$؟','27',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',3,4,600,'normal','ما هو القانون الذي يربط أضلاع المثلث القائم؟','نظرية فيثاغورس ($a^2 + b^2 = c^2$)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',3,5,600,'normal','ما هو ناتج $\sin^2(x) + \cos^2(x)$؟','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',4,0,200,'normal','كم يساوي 15% من 100؟','15',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',4,1,200,'normal','ما هو العدد التالي في المتتالية: 2، 4، 6، 8، ...؟','10',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',4,2,400,'normal','ما هو القانون لحساب محيط الدائرة؟','$2 \pi r$',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',4,3,400,'normal','ما هو العدد الذي إذا ضاعفته وأضفت إليه 5 يصبح 15؟','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',4,4,600,'normal','ما هي مشتقة الدالة $\ln(x)$؟','$1/x$',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',4,5,600,'normal','كم عدد الثواني في اليوم الواحد؟','86400',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',5,0,200,'normal','كم يوماً في 3 أسابيع؟','21',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',5,1,200,'normal','ما هو الجذر التربيعي للعدد 16؟','4',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',5,2,400,'normal','كم عدد الأيام في السنة العادية؟','365',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',5,3,400,'normal','ما هو ناتج $64 \times 0.5$؟','32',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',5,4,600,'normal','ماذا تعني نظرية "بايز"؟','نظرية في الاحتمالات تربط بين الاحتمالات الشرطية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',5,5,600,'normal','ما هو ناتج الضرب الاتجاهي لمتجهين متوازيين؟','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',6,0,200,'normal','ما هي قيمة $π$ (باي) التقريبية؟','3.14',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',6,1,200,'normal','ما هو أصغر عدد طبيعي؟','1 (أو 0 حسب النظام المتبع)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',6,2,400,'normal','ماذا يسمى المثلث الذي جميع أضلاعه متساوية؟','متساوي الأضلاع',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',6,3,400,'normal','ما هو ناتج 15% من 200؟','30',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',6,4,600,'normal','ما هو عدد الجوانب في "الإيكوساهيدرون" (عشروني الأوجه)؟','20',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',6,5,600,'normal','ما هو ناتج $x^0$ (حيث $x \neq 0$)؟','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',7,0,200,'normal','كم عدد الثواني في الدقيقة الواحدة؟','60',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',7,1,200,'normal','ما هو ناتج 50 - 17؟','33',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',7,2,400,'normal','إذا كان $2x = 20$، فما قيمة $x$؟','10',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',7,3,400,'normal','ما هو الجذر التكعيبي لـ 8؟','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',7,4,600,'normal','ما هو التوزيع الطبيعي (توزيع غاوس)؟','توزيع احتمالي متماثل يأخذ شكل الجرس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',7,5,600,'normal','ما هي نهاية الدالة $\sin(x)/x$ عندما تقترب $x$ من 0؟','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',8,0,200,'normal','ما هو الشكل الهندسي الذي له 3 أضلاع؟','المثلث',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',8,1,200,'normal','كم يساوي 1 كيلومتر بالمتر؟','1000 متر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',8,2,400,'normal','ما هو الرقم الذي إذا ضربته في نفسه كان الناتج 121؟','11',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',8,3,400,'normal','كم عدد الساعات في اليومين؟','48',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',8,4,600,'normal','ماذا يعني مصطلح "الكسيريات" (Fractals)؟','أشكال هندسية تكرر نمطها عند أي مقياس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',8,5,600,'normal','كم يساوي مجموع متسلسلة هندسية لا نهائية حدها الأول $a$ ونسبتها $r$ (حيث $|r|<1$)؟','$a / (1-r)$',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',9,0,200,'normal','ما هو العدد الذي إذا ضربته في أي رقم كان الناتج صفراً؟','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',9,1,200,'normal','كم عدد السنتيمترات في المتر الواحد؟','100',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',9,2,400,'normal','ما هو ناتج $10^2$؟','100',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',9,3,400,'normal','ما هو مجموع الزوايا المتجمعة حول نقطة؟','360 درجة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',9,4,600,'normal','ما هو عدد أضلاع "الهيبتاغون" (سباعي الأضلاع)؟','7',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',9,5,600,'normal','ما هو محدد المصفوفة $2 \times 2$ التالية: $[a, b; c, d]$؟','$ad - bc$',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',10,0,200,'normal','ما هو ناتج 12 × 12؟','144',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',10,1,200,'normal','ما هو نصف المئة؟','50',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',10,2,400,'normal','ماذا تسمى المصفوفة التي عناصرها جميعاً أصفار؟','المصفوفة الصفرية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',10,3,400,'normal','كم هو 3/4 من 100؟','75',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',10,4,600,'normal','ما هي قيمة $e$ (عدد أويلر) التقريبية؟','2.718',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',10,5,600,'normal','ماذا نسمي الدالة التي يساوي فيها $f(-x) = f(x)$؟','دالة زوجية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',11,0,200,'normal','كم زاوية للمربع؟','4',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',11,1,200,'normal','ما هو الرقم الذي يأتي قبل 1000؟','999',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',11,2,400,'normal','ما هو ناتج $12 - (-4)$؟','16',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',11,3,400,'normal','ما هو تعريف العدد الأولي؟','عدد لا يقبل القسمة إلا على نفسه وعلى الواحد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',11,4,600,'normal','ما هي مساحة سطح الكرة؟','$4 \pi r^2$',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',11,5,600,'normal','ما هو عدد الأعداد الأولية الأقل من 10؟','4 (2، 3، 5، 7)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',12,0,200,'normal','كم دقيقة في الساعة ونصف؟','90 دقيقة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',12,1,200,'normal','ما هو ناتج 8 × 7؟','56',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',12,2,400,'normal','ما هي مساحة الدائرة التي نصف قطرها 3؟','$9\pi$',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',12,3,400,'normal','ما هو ناتج $0.1 \times 0.1$؟','0.01',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',12,4,600,'normal','ما هو ناتج الضرب في المصفوفات: هل هو تبديلي؟','لا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',12,5,600,'normal','ما هو المعنى الهندسي للمشتقة الأولى؟','ميل المماس للمنحنى',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',13,0,200,'normal','أي عدد يسمى "محايداً ضربياً"؟','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',13,1,200,'normal','كم عدد أضلاع الخماسي؟','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',13,2,400,'normal','إذا كان اليوم هو الأربعاء، فماذا سيكون بعد 7 أيام؟','الأربعاء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',13,3,400,'normal','ماذا نسمي المستقيم الذي يقطع الدائرة في نقطتين؟','قاطع الدائرة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',13,4,600,'normal','كم عدد الوجوه في المكعب؟','6',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',13,5,600,'normal','ما هي متطابقة أويلر؟','$e^{i\pi} + 1 = 0$',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',14,0,200,'normal','ما هو ناتج 25 + 25 + 25؟','75',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('math',14,1,200,'normal','ماذا نسمي مجموع أطوال أضلاع الشكل؟','المحيط',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
on conflict(category,version,ord) do update set value=excluded.value,type=excluded.type,q=excluded.q,a=excluded.a,note=excluded.note,flag=excluded.flag,clues=excluded.clues,num=excluded.num,evidence=excluded.evidence,suspects=excluded.suspects,image=excluded.image;

commit;
