-- FAKKIR seed — part 1 of 9. Generated; do not edit by hand.
-- Run server/sql/schema.sql once, then paste these part files into the Supabase SQL Editor in order (01, 02, ...).
begin;

-- ensure the per-question image column exists (players photos etc.)
alter table questions add column if not exists image text;

-- Replace all game content: versions A–O fully replace any previous data.
delete from questions;
delete from flags;

-- Categories (idempotent; required by the questions foreign key)
insert into categories(slug,name,color,image,sort_order) values
('geo','الجغرافيا','blue','assets/img/categories/geo.png',0),
('history','التاريخ','gold','assets/img/categories/history.png',1),
('palestine','فلسطين','green','assets/img/categories/palestine.png',2),
('seerah','السيرة النبوية','teal','assets/img/categories/seerah.png',3),
('quran','القرآن الكريم','green','assets/img/categories/quran.png',4),
('flags','أعلام الدول','red','assets/img/categories/flags.png',5),
('sports','الرياضة','cyan','assets/img/categories/sports.png',6),
('football','كرة القدم','blue','assets/img/categories/football.png',7),
('riddles','الألغاز','purple','assets/img/categories/riddles.png',8),
('science','العلوم','teal','assets/img/categories/science.png',9),
('tech','التكنولوجيا','cyan','assets/img/categories/tech.png',10),
('animals','عالم الحيوان','gold','assets/img/categories/animals.png',11),
('general','المعلومات العامة','gold','assets/img/categories/general.png',12),
('math','الرياضيات والأرقام','blue','assets/img/categories/math.png',13),
('whoami','احزر ماذا أنا','purple','assets/img/categories/whoami.png',14),
('proverbs','تكملة المثل','teal','assets/img/categories/proverbs.png',15),
('dish','ما هي الأكلة','red','assets/img/categories/dish.png',16),
('crime','الجريمة','red','assets/img/categories/crime.png',17),
('rescue','إنقاذ المتهم','green','assets/img/categories/rescue.png',18),
('closest','الأقرب إلى الرقم','purple','assets/img/categories/closest.png',19),
('capitals','عواصم الدول','blue','assets/img/categories/capitals.png',20),
('currencies','عملات الدول','gold','assets/img/categories/currencies.png',21),
('verse','أكمل الآية','green','assets/img/categories/verse.png',22),
('ordering','الترتيب الصحيح','cyan','assets/img/categories/ordering.png',23),
('players','احزر اللاعب','cyan','assets/img/categories/players.png',24)
on conflict(slug) do update set name=excluded.name,color=excluded.color,image=excluded.image,sort_order=excluded.sort_order;

insert into flags(key,image) values
('sa','assets/img/flags/sa.png'),
('eg','assets/img/flags/eg.png'),
('za','assets/img/flags/za.png'),
('kr','assets/img/flags/kr.png'),
('bt','assets/img/flags/bt.png'),
('np','assets/img/flags/np.png'),
('ae','assets/img/flags/ae.png'),
('ps','assets/img/flags/ps.png'),
('be','assets/img/flags/be.png'),
('se','assets/img/flags/se.png'),
('kz','assets/img/flags/kz.png'),
('uz','assets/img/flags/uz.png'),
('lb','assets/img/flags/lb.png'),
('ma','assets/img/flags/ma.png'),
('no','assets/img/flags/no.png'),
('at','assets/img/flags/at.png'),
('kg','assets/img/flags/kg.png'),
('tj','assets/img/flags/tj.png'),
('qa','assets/img/flags/qa.png'),
('kw','assets/img/flags/kw.png'),
('dk','assets/img/flags/dk.png'),
('pl','assets/img/flags/pl.png'),
('tm','assets/img/flags/tm.png'),
('az','assets/img/flags/az.png'),
('dz','assets/img/flags/dz.png'),
('tn','assets/img/flags/tn.png'),
('cz','assets/img/flags/cz.png'),
('hu','assets/img/flags/hu.png'),
('ge','assets/img/flags/ge.png'),
('am','assets/img/flags/am.png'),
('us','assets/img/flags/us.png'),
('gb','assets/img/flags/gb.png'),
('co','assets/img/flags/co.png'),
('cl','assets/img/flags/cl.png'),
('ee','assets/img/flags/ee.png'),
('lv','assets/img/flags/lv.png'),
('fr','assets/img/flags/fr.png'),
('de','assets/img/flags/de.png'),
('mx','assets/img/flags/mx.png'),
('vn','assets/img/flags/vn.png'),
('lt','assets/img/flags/lt.png'),
('fi','assets/img/flags/fi.png'),
('it','assets/img/flags/it.png'),
('es','assets/img/flags/es.png'),
('my','assets/img/flags/my.png'),
('id','assets/img/flags/id.png'),
('is','assets/img/flags/is.png'),
('ie','assets/img/flags/ie.png'),
('br','assets/img/flags/br.png'),
('ar','assets/img/flags/ar.png'),
('sg','assets/img/flags/sg.png'),
('th','assets/img/flags/th.png'),
('hr','assets/img/flags/hr.png'),
('rs','assets/img/flags/rs.png'),
('jp','assets/img/flags/jp.png'),
('cn','assets/img/flags/cn.png'),
('ph','assets/img/flags/ph.png'),
('ir','assets/img/flags/ir.png'),
('si','assets/img/flags/si.png'),
('sk','assets/img/flags/sk.png'),
('ca','assets/img/flags/ca.png'),
('tr','assets/img/flags/tr.png'),
('iq','assets/img/flags/iq.png'),
('jo','assets/img/flags/jo.png'),
('bg','assets/img/flags/bg.png'),
('ro','assets/img/flags/ro.png'),
('ru','assets/img/flags/ru.png'),
('in','assets/img/flags/in.png'),
('om','assets/img/flags/om.png'),
('ye','assets/img/flags/ye.png'),
('md','assets/img/flags/md.png'),
('by','assets/img/flags/by.png'),
('au','assets/img/flags/au.png'),
('ly','assets/img/flags/ly.png'),
('sd','assets/img/flags/sd.png'),
('ua','assets/img/flags/ua.png'),
('mg','assets/img/flags/mg.png'),
('nl','assets/img/flags/nl.png'),
('pt','assets/img/flags/pt.png'),
('mr','assets/img/flags/mr.png'),
('ng','assets/img/flags/ng.png'),
('mu','assets/img/flags/mu.png'),
('sc','assets/img/flags/sc.png'),
('gr','assets/img/flags/gr.png'),
('ch','assets/img/flags/ch.png'),
('ke','assets/img/flags/ke.png'),
('gh','assets/img/flags/gh.png'),
('jm','assets/img/flags/jm.png'),
('py','assets/img/flags/py.png')
on conflict(key) do update set image=excluded.image;

-- Questions 1..250
insert into questions(category,version,ord,value,type,q,a,note,flag,clues,num,evidence,suspects,image) values
('geo',1,0,200,'normal','ما هي أكبر قارة في العالم من حيث المساحة؟','آسيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',1,1,200,'normal','ما هو أطول نهر في العالم؟','نهر النيل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',1,2,400,'normal','ما هي الدولة التي تمتلك أكبر عدد من الجزر في العالم؟','السويد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',1,3,400,'normal','ما هي عاصمة كازاخستان الحالية؟','أستانا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',1,4,600,'normal','ما هي الدولة التي تمتلك أطول حدود برية مشتركة مع دولة واحدة فقط؟','كندا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',1,5,600,'normal','ما هي العاصمة التي تقع على أعلى ارتفاع عن سطح البحر في العالم؟','لاباز (بوليفيا)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',2,0,200,'normal','ما هي عاصمة فرنسا؟','باريس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',2,1,200,'normal','في أي قارة تقع دولة البرازيل؟','أمريكا الجنوبية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',2,2,400,'normal','في أي دولة تقع مدينة "ماتشو بيتشو"؟','بيرو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',2,3,400,'normal','ما هو أعمق نقطة في محيطات العالم؟','خندق ماريانا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',2,4,600,'normal','ما هو الاسم القديم لدولة إثيوبيا؟','الحبشة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',2,5,600,'normal','في أي بحر يقع "حقل غاز ظهر"؟','البحر الأبيض المتوسط',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',3,0,200,'normal','ما هو المحيط الذي يقع بين أمريكا وأوروبا؟','المحيط الأطلسي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',3,1,200,'normal','ما هو أكبر بلد في العالم من حيث المساحة؟','روسيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',3,2,400,'normal','ما هو اسم المضيق الذي يفصل بين روسيا وألاسكا؟','مضيق بيرنغ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',3,3,400,'normal','ما هي الدولة التي تمتلك أكبر عدد من الحدود البرية مع دول أخرى؟','الصين (تشاركها روسيا)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',3,4,600,'normal','ما هو اسم الممر المائي الذي يربط بين بحر قزوين والبحر الأسود؟','قناة فولغا-دون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',3,5,600,'normal','ما هي الدولة التي كانت تسمى "فولتا العليا"؟','بوركينا فاسو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',4,0,200,'normal','ما هو الجبل الأعلى ارتفاعاً في العالم؟','جبل إيفرست',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',4,1,200,'normal','في أي دولة تقع أهرامات الجيزة؟','مصر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',4,2,400,'normal','ما هي العاصمة الأسترالية؟','كانبرا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',4,3,400,'normal','في أي قارة تقع دولة مدغشقر؟','أفريقيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',4,4,600,'normal','ما هي المدينة التي تقع في قارتين مختلفتين؟','إسطنبول',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',4,5,600,'normal','ما هو أطول سلسلة جبال تحت الماء في العالم؟','حيد وسط المحيط',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',5,0,200,'normal','ما هي القارة التي تسمى "القارة القطبية الجنوبية"؟','أنتاركتيكا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',5,1,200,'normal','ما هي أكبر صحراء حارة في العالم؟','الصحراء الكبرى',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',5,2,400,'normal','ما هو النهر الذي يمر في مدينة لندن؟','نهر التايمز',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',5,3,400,'normal','ما هو اسم الصحراء الموجودة في جنوب أفريقيا؟','صحراء كالاهاري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',5,4,600,'normal','ما هي الدولة التي يمر بها خط "جرينتش" وخط "الاستواء" معاً؟','لا توجد (يتقاطعان في المحيط الأطلسي)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',5,5,600,'normal','ما هو اسم أضيق مضيق في العالم؟','مضيق البوسفور',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',6,0,200,'normal','ما هو البحر الذي يفصل بين أوروبا وأفريقيا؟','البحر الأبيض المتوسط',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',6,1,200,'normal','ما هي الدولة التي تُعرف بـ "بلد المليون شهيد"؟','الجزائر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',6,2,400,'normal','ما هي أصغر دولة في العالم من حيث المساحة؟','الفاتيكان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',6,3,400,'normal','ما هي الدولة التي تسمى "أرض الشمس المشرقة"؟','اليابان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',6,4,600,'normal','ما هي العاصمة التي تقع في أقصى الشمال في العالم؟','ريكيافيك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',6,5,600,'normal','في أي دولة يوجد "صحراء أتاكاما"؟','تشيلي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',7,0,200,'normal','ما هي عاصمة اليابان؟','طوكيو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',7,1,200,'normal','في أي قارة توجد دولة أستراليا؟','أوقيانوسيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',7,2,400,'normal','ما هو الجبل الذي يقع على الحدود بين فرنسا وإيطاليا؟','جبل مون بلان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',7,3,400,'normal','ما هي أكبر بحيرة مياه عذبة في العالم من حيث المساحة؟','بحيرة سوبيريور',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',7,4,600,'normal','ما هو النهر الذي يغير اتجاه تدفقه موسمياً؟','نهر أورينوكو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',7,5,600,'normal','ما هي الدولة التي كانت تعرف بـ "سيلان"؟','سريلانكا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',8,0,200,'normal','ما هو أكبر محيط في العالم؟','المحيط الهادئ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',8,1,200,'normal','ما هي الدولة التي تمتلك أطول ساحل في العالم؟','كندا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',8,2,400,'normal','ما هي العاصمة السويسرية؟','برن',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',8,3,400,'normal','في أي دولة يوجد "برج خليفة"؟','الإمارات العربية المتحدة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',8,4,600,'normal','ما هو اسم المضيق الذي يفصل بين جزيرة سولاويزي وجزيرة بورنيو؟','مضيق ماكاسار',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',8,5,600,'normal','ما هي الدولة التي لديها أكبر عدد من المناطق الزمنية؟','فرنسا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',9,0,200,'normal','ما هو الخط الذي يقسم الأرض إلى نصفين شمالي وجنوبي؟','خط الاستواء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',9,1,200,'normal','ما هي القارة التي تضم معظم دول العالم؟','أفريقيا (من حيث عدد الدول)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',9,2,400,'normal','ما هو اسم البحر الذي لا يوجد به أي شاطئ؟','بحر سارجاسو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',9,3,400,'normal','ما هي الدولة التي يطلق عليها اسم "أرض الألف بحيرة"؟','فنلندا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',9,4,600,'normal','ما هو اسم الجبل الذي يعتبر أعلى نقطة في القارة القطبية الجنوبية؟','جبل فينسون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',9,5,600,'normal','ما هي الدولة التي تقع في أقصى شرق قارة أفريقيا؟','الصومال',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',10,0,200,'normal','ما هي عاصمة إيطاليا؟','روما',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',10,1,200,'normal','ما هي الدولة التي يمر بها خط الاستواء وتسمى باسمه؟','الإكوادور',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',10,2,400,'normal','ما هو أكبر أرخبيل في العالم؟','أرخبيل الملايو (إندونيسيا)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',10,3,400,'normal','ما هي عاصمة دولة فيتنام؟','هانوي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',10,4,600,'normal','ما هو أكبر حوض نهر في العالم من حيث التصريف المائي؟','نهر الأمازون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',10,5,600,'normal','ما هو اسم الخليج الذي يقع بين شبه جزيرة القرم وأوكرانيا؟','بحر آزوف',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',11,0,200,'normal','في أي قارة توجد جبال الأنديز؟','أمريكا الجنوبية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',11,1,200,'normal','ما هو المضيق الذي يربط بين المحيط الأطلسي والبحر المتوسط؟','مضيق جبل طارق',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',11,2,400,'normal','في أي قارة يقع نهر النيجر؟','أفريقيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',11,3,400,'normal','ما هو المضيق الذي يفصل بين إنجلترا وفرنسا؟','مضيق دوفر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',11,4,600,'normal','ما هي العاصمة التي تقع على أكبر بحيرة في العالم؟','كمبالا (أوغندا)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',11,5,600,'normal','ما هي الدولة التي لا تمتلك أي جيش نظامي؟','كوستاريكا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',12,0,200,'normal','ما هي الدولة العربية التي تقع في قارتي آسيا وأفريقيا؟','مصر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',12,1,200,'normal','ما هو أكبر خليج في العالم؟','خليج البنغال',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',12,2,400,'normal','ما هي الدولة التي تحدها كل من ألمانيا وفرنسا وسويسرا؟','فرنسا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',12,3,400,'normal','ما هو اسم أعلى قمة في أفريقيا؟','جبل كليمنجارو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',12,4,600,'normal','ما هو اسم المنخفض الذي يعتبر أخفض نقطة على اليابسة؟','غور الأردن (البحر الميت)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',12,5,600,'normal','في أي دولة يوجد "صحراء لوب نور"؟','الصين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',13,0,200,'normal','ما هي عاصمة روسيا؟','موسكو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',13,1,200,'normal','في أي قارة تقع دولة الهند؟','آسيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',13,2,400,'normal','ما هي الدولة التي تقع بالكامل داخل دولة أخرى؟','ليسوتو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',13,3,400,'normal','ما هو النهر الذي يعتبر شريان الحياة في جنوب شرق آسيا؟','نهر ميكونغ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',13,4,600,'normal','ما هو اسم أقدم دولة في العالم من حيث التاريخ المستمر؟','مصر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',13,5,600,'normal','ما هو المضيق الذي يربط بين بحر اليابان وبحر أوخوتسك؟','مضيق لا بيروز',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',14,0,200,'normal','ما هو النهر الذي يمر عبر وسط أوروبا ويصب في البحر الأسود؟','نهر الدانوب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',14,1,200,'normal','ما هو البحر الذي يحيط به قارات العالم القديم؟','البحر الأبيض المتوسط',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',14,2,400,'normal','ما هي عاصمة دولة الأرجنتين؟','بوينس آيرس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',14,3,400,'normal','ما هو اسم الهضبة التي تسمى "سقف العالم"؟','هضبة التبت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',14,4,600,'normal','ما هي الدولة التي تسمى "سويسرا أفريقيا"؟','ليسوتو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',14,5,600,'normal','ما هو اسم الهضبة التي تقع في وسط تركيا؟','هضبة الأناضول',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',15,0,200,'normal','ما هي عاصمة كندا؟','أوتاوا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',15,1,200,'normal','ما هو الاسم الذي يطلق على الجزء اليابس من الأرض؟','القارات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',15,2,400,'normal','ما هو البحر الذي تطل عليه كل من الأردن وفلسطين؟','البحر الميت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',15,3,400,'normal','ما هي أكبر جزيرة في العالم (غير القارات)؟','غرينلاند',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',15,4,600,'normal','ما هو اسم أطول نفق في العالم؟','نفق غوتهارد الأساسي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('geo',15,5,600,'normal','ما هي الدولة الحبيسة التي تقع في أمريكا الجنوبية؟','بوليفيا وباراغواي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',1,0,200,'normal','ما هو عدد لاعبي كل فريق في الملعب عند بداية المباراة؟','11 لاعباً',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',1,1,200,'normal','كم مدة الشوط الواحد في المباراة الرسمية؟','45 دقيقة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',1,2,400,'normal','من هو الهداف التاريخي لبطولة دوري أبطال أوروبا؟','كريستيانو رونالدو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',1,3,400,'normal','ما هو النادي الذي يطلق عليه "السيدة العجوز"؟','يوفنتوس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',1,4,600,'normal','ما هو المنتخب الذي فاز بكأس العالم دون أن يستقبل أي هدف في البطولة؟','سويسرا (في بطولة 2006 خرجت دون استقبال أهداف في الوقت الأصلي)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',1,5,600,'normal','من هو اللاعب الذي سجل أكبر عدد من الأهداف في مباراة واحدة في كأس العالم؟','أوليغ سالينكو (5 أهداف)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',2,0,200,'normal','ما اسم الكرة التي تُحرز بها الأهداف؟','كرة القدم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',2,1,200,'normal','ماذا يسمى اللاعب الذي يحرس المرمى ويمنع الأهداف؟','حارس المرمى',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',2,2,400,'normal','في أي سنة أقيمت أول بطولة كأس عالم للسيدات؟','1991',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',2,3,400,'normal','ما هو اسم الملعب الوطني لمنتخب إنجلترا؟','ويمبلي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',2,4,600,'normal','ما هو النادي الذي فاز بأكبر عدد من الألقاب القارية في أفريقيا؟','الأهلي المصري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',2,5,600,'normal','من هو الحكم الذي قاد أكبر عدد من نهائيات كأس العالم؟','لا يوجد حكم قاد أكثر من نهائي واحد (قاعدة الفيفا)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',3,0,200,'normal','ما هو لون البطاقة التي تعني الطرد المباشر؟','الحمراء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',3,1,200,'normal','ما الفريق الذي يلقب بـ "المرينجي"؟','ريال مدريد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',3,2,400,'normal','من هو اللاعب الذي فاز بأكبر عدد من الكرات الذهبية؟','ليونيل ميسي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',3,3,400,'normal','ما هو المنتخب الملقب بـ "الطواحين"؟','هولندا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',3,4,600,'normal','ما هو المنتخب الذي لم يتأهل لكأس العالم منذ عام 1958 حتى 2018؟','مصر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',3,5,600,'normal','من هو اللاعب الذي سجل أهدافاً في 4 نسخ مختلفة من كأس العالم؟','كريستيانو رونالدو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',4,0,200,'normal','من هو اللاعب الملقب بـ "البرغوث"؟','ليونيل ميسي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',4,1,200,'normal','ما الدولة التي فازت بأول كأس عالم عام 1930؟','الأوروغواي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',4,2,400,'normal','كم عدد البطولات التي فاز بها منتخب إيطاليا في كأس العالم؟','4 مرات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',4,3,400,'normal','ما اسم القاعدة التي تعاقب اللاعب إذا كان خلف المدافعين عند التمرير؟','التسلل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',4,4,600,'normal','ما هو النادي الذي فاز بالدوري الإسباني 5 مرات متتالية في بدايات الدوري؟','ريال مدريد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',4,5,600,'normal','من هو اللاعب الذي لعب لأكبر عدد من الأندية في مسيرته الاحترافية؟','سيباستيان أبريو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',5,0,200,'normal','ما اسم البطولة الأقوى للأندية في أوروبا؟','دوري أبطال أوروبا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',5,1,200,'normal','كم عدد الأشواط في المباراة العادية؟','شوطان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',5,2,400,'normal','من هو مدرب منتخب فرنسا الذي فاز بكأس العالم كلاعب ومدرب؟','ديديه ديشامب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',5,3,400,'normal','ما هو الفريق الذي حقق "الثلاثية التاريخية" في إنجلترا عام 1999؟','مانشستر يونايتد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',5,4,600,'normal','ما هو الملعب الذي شهد أكبر عدد من الحضور الجماهيري في مباراة كرة قدم؟','ماراكانا (نهائي 1950)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',5,5,600,'normal','من هو المدرب الذي قاد ثلاثة منتخبات مختلفة في نهائيات كأس العالم؟','بورا ميلوتينوفيتش',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',6,0,200,'normal','ماذا يحدث إذا انتهت المباراة بالتعادل في الأدوار الإقصائية؟','يتم اللجوء لأشواط إضافية ثم ركلات ترجيح',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',6,1,200,'normal','من هو اللاعب الذي يرتدي القفازات؟','حارس المرمى',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',6,2,400,'normal','ما هو النادي الذي يلقب بـ "الريدز"؟','ليفربول',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',6,3,400,'normal','من هو اللاعب الذي سجل هدف "يد الرب"؟','دييغو مارادونا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',6,4,600,'normal','ما هي الدولة التي استضافت كأس العالم ولم تكن عضواً في فيفا وقتها؟','لم يحدث (سؤال استدلالي)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',6,5,600,'normal','من هو اللاعب الذي سجل الهدف رقم 1000 في تاريخ كأس العالم؟','روب رينسينبرينك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',7,0,200,'normal','أين تقام عادةً المباريات النهائية لكؤوس العالم؟','في ملعب يتم اختياره مسبقاً (غالباً الملعب الأكبر)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',7,1,200,'normal','ماذا تعني البطاقة الصفراء؟','إنذار للاعب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',7,2,400,'normal','ما هي الدولة التي استضافت كأس العالم 2010؟','جنوب أفريقيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',7,3,400,'normal','كم عدد المرات التي فازت فيها البرازيل بكأس العالم؟','5 مرات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',7,4,600,'normal','ما هو النادي الذي لديه أقدم ملعب كرة قدم مستخدم في إنجلترا؟','شيفيلد إف سي (ملعب سانديجيت)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',7,5,600,'normal','ما هو المنتخب الذي فاز بلقب "كوبا أمريكا" 15 مرة؟','الأوروغواي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',8,0,200,'normal','من هو المنتخب صاحب الرقم القياسي في الفوز بكأس العالم؟','البرازيل (5 مرات)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',8,1,200,'normal','ما اسم المنطقة التي يقف فيها حارس المرمى؟','منطقة الجزاء (أو منطقة الـ 18)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',8,2,400,'normal','ما هو الفريق الألماني المعروف بلقب "البافاري"؟','بايرن ميونخ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',8,3,400,'normal','من هو الحارس الذي لقب بـ "الأخطبوط"؟','ليف ياشين (أو تيبو كورتوا في سياقات حديثة)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',8,4,600,'normal','من هو اللاعب الذي شارك في 5 نسخ من كأس العالم؟','عدة لاعبين منهم ميسي ورونالدو وماتيوس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',8,5,600,'normal','ما هو الفريق الذي فاز بلقب دوري أبطال أوروبا دون الفوز في الأدوار الإقصائية؟','النجم الأحمر بلغراد (1991)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',9,0,200,'normal','ما اسم الضربة التي تُحتسب من نقطة الجزاء؟','ركلة جزاء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',9,1,200,'normal','ما الفريق الذي يلعب في ملعب "سانتياغو برنابيو"؟','ريال مدريد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',9,2,400,'normal','ما هو الفريق الذي فاز بلقب الدوري الإنجليزي دون أي خسارة؟','أرسنال (2003-2004)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',9,3,400,'normal','من هو أصغر لاعب شارك في تاريخ كأس العالم؟','نورمان وايتسايد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',9,4,600,'normal','من هو الحارس الذي حافظ على نظافة شباكه لأطول فترة في تاريخ الدوري الإنجليزي؟','إدوين فان در سار',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',9,5,600,'normal','ما هو المنتخب الذي استطاع هزيمة البرازيل في نهائي كأس العالم على أرضها؟','الأوروغواي (1950)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',10,0,200,'normal','ما هو النادي الإنجليزي المعروف بـ "الشياطين الحمر"؟','مانشستر يونايتد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',10,1,200,'normal','كم مرة فازت الأرجنتين بكأس العالم؟','3 مرات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',10,2,400,'normal','ما اسم الجائزة التي تقدم لأفضل لاعب في البطولة؟','الكرة الذهبية (Golden Ball)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',10,3,400,'normal','ما هي الدولة التي فازت بأول لقب لكأس أمم أوروبا؟','الاتحاد السوفيتي (1960)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',10,4,600,'normal','من هو اللاعب الذي لقب بـ "القيصر"؟','فرانز بيكنباور',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',10,5,600,'normal','ما هو النادي الذي يلقب بـ "البيانكونيري"؟','يوفنتوس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',11,0,200,'normal','ما هو الدوري الذي يسمى "الليغا"؟','الدوري الإسباني',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',11,1,200,'normal','ما اسم الأداة التي يستخدمها الحكم للتنبيه؟','الصافرة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',11,2,400,'normal','من هو اللاعب الذي سجل أسرع هدف في تاريخ نهائيات كأس العالم؟','هاكان شوكور',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',11,3,400,'normal','ما هو النادي الذي يلقب بـ "البلوز"؟','تشيلسي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',11,4,600,'normal','في أي عام تم إدخال قانون التسلل لأول مرة؟','1863',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',11,5,600,'normal','من هو اللاعب الذي سجل هدفاً من مسافة أبعد من 50 متراً في نهائي دوري أبطال أوروبا؟','لم يحدث',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',12,0,200,'normal','ماذا يسمى اللاعب الذي يسجل الأهداف عادةً؟','المهاجم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',12,1,200,'normal','ما هو النادي الذي يلعب في ملعب "الكامب نو"؟','برشلونة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',12,2,400,'normal','كم مرة فازت إسبانيا بكأس العالم؟','مرة واحدة (2010)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',12,3,400,'normal','من هو الهداف التاريخي للمنتخب البرازيلي؟','نيمار (تجاوز بيليه)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',12,4,600,'normal','ما هو المنتخب الآسيوي الذي وصل لنصف نهائي كأس العالم 2002؟','كوريا الجنوبية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',12,5,600,'normal','من هو اللاعب الوحيد الذي سجل "هاتريك" في نهائي كأس العالم؟','جيف هيرست (1966)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',13,0,200,'normal','من هو قائد الفريق في العادة؟','اللاعب الذي يرتدي شارة القيادة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',13,1,200,'normal','كم عدد الحكام المساعدين الموجودين على الخطوط؟','اثنان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',13,2,400,'normal','ما اسم الدوري الذي يطلق عليه "الكالتشيو"؟','الدوري الإيطالي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',13,3,400,'normal','من هو اللاعب الذي فاز بكأس العالم مع منتخبين مختلفين؟','لا يوجد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',13,4,600,'normal','ما هو النادي الذي فاز بلقب الدوري الأوروبي لأول مرة باسمه الجديد؟','بورتو (2003)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',13,5,600,'normal','كم عدد الأهداف التي سجلها بيليه في مسيرته الرسمية؟','757 هدفاً (رسمياً)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',14,0,200,'normal','ما اسم الضربة التي تُلعب من زاوية الملعب؟','الركلة الركنية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',14,1,200,'normal','في أي قارة تقام بطولة كأس أمم أفريقيا؟','أفريقيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',14,2,400,'normal','ما هو النادي الذي يلقب بـ "المدفعجية"؟','أرسنال',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',14,3,400,'normal','من هو المدرب صاحب الرقم القياسي في الفوز بدوري أبطال أوروبا؟','كارلو أنشيلوتي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',14,4,600,'normal','من هو المدرب الذي حقق لقب الدوري في 4 دول مختلفة من الدوريات الخمس الكبرى؟','كارلو أنشيلوتي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',14,5,600,'normal','ما هو المنتخب الذي فاز بأول بطولة كأس أمم آسيا؟','كوريا الجنوبية (1956)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',15,0,200,'normal','ماذا يطلق على الفترة الإضافية التي تضاف نهاية الشوط؟','الوقت بدل الضائع',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',15,1,200,'normal','ما هو الفريق الذي فاز بكأس العالم 2022؟','الأرجنتين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',15,2,400,'normal','ما اسم الكرة الرسمية المستخدمة في كأس العالم 2022؟','الرحلة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',15,3,400,'normal','ما هو المنتخب الذي خسر نهائي كأس العالم 1950 في "الماراكانازو"؟','البرازيل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',15,4,600,'normal','ما هو النادي الذي يلقب بـ "فريق الأحلام" في التسعينات؟','برشلونة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('football',15,5,600,'normal','من هو اللاعب الذي سجل هدف الفوز في نهائي كأس العالم 2010؟','أندريس إنييستا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',1,0,200,'normal','ما هي القارة التي تُلقب بـ "القارة العجوز"؟','أوروبا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',1,1,200,'normal','من هو مكتشف أمريكا عام 1492؟','كريستوفر كولومبوس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',1,2,400,'normal','ما هي "الحرب الباردة"؟','صراع سياسي وعسكري غير مباشر بين أمريكا والاتحاد السوفيتي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',1,3,400,'normal','من هو السلطان الأيوبي الذي استعاد القدس من الصليبيين؟','صلاح الدين الأيوبي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',1,4,600,'normal','ما هي "اتفاقية سايكس بيكو"؟','اتفاقية سرية لتقسيم التركة العثمانية بين بريطانيا وفرنسا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',1,5,600,'normal','من هو آخر إمبراطور لروما؟','رومولوس أوغستولوس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',2,0,200,'normal','في أي دولة بنيت الأهرامات؟','مصر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',2,1,200,'normal','من هو مؤسس الإمبراطورية المغولية؟','جنكيز خان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',2,2,400,'normal','ما هي الحضارة التي بنته "ماشو بيتشو" في بيرو؟','حضارة الإنكا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',2,3,400,'normal','متى وقعت معركة حطين؟','1187 ميلادي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',2,4,600,'normal','ما هي "حرب الوردتين"؟','صراع على العرش الإنجليزي بين عائلتي لانكاستر ويورك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',2,5,600,'normal','في أي معركة خسر فيها الإسكندر الأكبر لأول مرة؟','لم يخسر معركة قط في حياته',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',3,0,200,'normal','ما هي الحضارة التي اشتهرت بـ "حدائق بابل المعلقة"؟','الحضارة البابلية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',3,1,200,'normal','من هو القائد المسلم الذي فتح القسطنطينية؟','محمد الفاتح',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',3,2,400,'normal','من هي الملكة المصرية التي حكمت كفرعون؟','حتشبسوت (أو كليوباترا)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',3,3,400,'normal','ما هو "عصر النهضة"؟','فترة انتقالية من العصور الوسطى إلى الحديثة في أوروبا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',3,4,600,'normal','من هو المخترع العربي الذي وضع تصميمات مبكرة للطيران؟','عباس بن فرناس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',3,5,600,'normal','ما هي "الثورة المجيدة" في تاريخ إنجلترا؟','انتقال السلطة لوليام أورنج عام 1688',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',4,0,200,'normal','في أي قرن بدأت الثورة الصناعية؟','القرن الثامن عشر (18)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',4,1,200,'normal','من هو مخترع المصباح الكهربائي؟','توماس أديسون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',4,2,400,'normal','من هو الرسام الذي رسم "الموناليزا"؟','ليوناردو دا فينشي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',4,3,400,'normal','ما هي الدولة التي كانت تعرف بـ "الإمبراطورية التي لا تغيب عنها الشمس"؟','الإمبراطورية البريطانية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',4,4,600,'normal','من هو الإمبراطور الذي جعل المسيحية ديانة رسمية لروما؟','قسطنطين العظيم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',4,5,600,'normal','ما هي معركة "موهاتش"؟','معركة انتصر فيها العثمانيون على المجر عام 1526',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',5,0,200,'normal','ما هي المدينة التي كانت عاصمة الإمبراطورية الرومانية الغربية؟','روما',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',5,1,200,'normal','من هو أول رئيس للولايات المتحدة الأمريكية؟','جورج واشنطن',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',5,2,400,'normal','في أي عام تم توقيع "الماجنا كارتا" (الميثاق الأعظم)؟','1215',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',5,3,400,'normal','من هو الإمبراطور الذي قسم الإمبراطورية الرومانية إلى شرقية وغربية؟','ديوكلتيانوس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',5,4,600,'normal','من هو الفيلسوف الذي قال "أنا أفكر، إذاً أنا موجود"؟','رينيه ديكارت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',5,5,600,'normal','ما هو "العهد القديم" في التاريخ؟','العصر الذي يسبق ظهور الإسلام',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',6,0,200,'normal','ما هو الحدث الذي أنهى الحرب العالمية الثانية؟','استسلام اليابان بعد قصف هيروشيما وناجازاكي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',6,1,200,'normal','ما هي أطول حضارة في التاريخ البشري؟','الحضارة المصرية القديمة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',6,2,400,'normal','ما هي المعركة التي أوقف فيها المسلمون زحف الفرنجة إلى أوروبا؟','معركة بلاط الشهداء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',6,3,400,'normal','من هو العالم الذي وضع أساسيات علم الجبر؟','الخوارزمي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',6,4,600,'normal','من هو الملك الذي أعدم خلال الثورة الفرنسية؟','لويس السادس عشر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',6,5,600,'normal','ما هي الحرب التي بدأت بسبب "أذن جنكينز"؟','حرب بين بريطانيا وإسبانيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',7,0,200,'normal','من هو العالم الذي وضع قانون الجاذبية؟','إسحاق نيوتن',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',7,1,200,'normal','في أي دولة قامت الثورة الفرنسية؟','فرنسا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',7,2,400,'normal','في أي حرب استخدمت الغازات السامة لأول مرة؟','الحرب العالمية الأولى',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',7,3,400,'normal','من هو مؤسس علم الاجتماع؟','ابن خلدون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',7,4,600,'normal','من هو مكتشف فيروس السل؟','روبرت كوخ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',7,5,600,'normal','ما هو "مؤتمر فيينا"؟','مؤتمر لإعادة رسم خريطة أوروبا بعد هزيمة نابليون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',8,0,200,'normal','من هو النبي الذي بنى السفينة؟','نوح عليه السلام',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',8,1,200,'normal','ما هي اللغة التي كان يتحدث بها الرومان؟','اللاتينية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',8,2,400,'normal','ما هي المدينة التي أصبحت عاصمة الإمبراطورية البيزنطية؟','القسطنطينية (إسطنبول)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',8,3,400,'normal','متى سقطت الأندلس؟','1492',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',8,4,600,'normal','من هو الملك الإنجليزي الذي تزوج 6 مرات؟','هنري الثامن',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',8,5,600,'normal','ما هي "حرب الثلاثين عاماً"؟','صراع ديني وسياسي في أوروبا (1618-1648)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',9,0,200,'normal','من هو القائد العسكري الفرنسي الذي وصل إلى مصر؟','نابليون بونابرت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',9,1,200,'normal','ما هو جدار برلين؟','جدار فصل برلين الشرقية عن الغربية خلال الحرب الباردة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',9,2,400,'normal','من هو الملك الذي وحد القبائل العربية؟','النبي محمد (ص) (أو الملك عبد العزيز في العصر الحديث)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',9,3,400,'normal','ما هو "الكسر العظيم" (الانشقاق الكبير) في الكنيسة؟','انقسام الكنيسة بين الكاثوليك والأرثوذكس (1054)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',9,4,600,'normal','من هو المهندس الذي صمم قبة الصخرة؟','بناها عبد الملك بن مروان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',9,5,600,'normal','ما هي "المملكة الوسطى" في التاريخ المصري؟','عصر ازدهار الفنون والأدب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',10,0,200,'normal','من هو الفيلسوف اليوناني الذي كان معلم الإسكندر الأكبر؟','أرسطو',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',10,1,200,'normal','ما هي الحضارة التي اخترعت الكتابة المسمارية؟','السومرية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',10,2,400,'normal','من هو الزعيم النازي الذي حكم ألمانيا؟','أدولف هتلر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',10,3,400,'normal','ما هي الحضارة التي اشتهرت بحضارة "المايا"؟','حضارة وسط أمريكا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',10,4,600,'normal','من هو الزعيم الذي قاد "المسيرة الطويلة" في الصين؟','ماو تسي تونغ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',10,5,600,'normal','ما هي "حرب الاستنزاف"؟','حرب دارت بين مصر وإسرائيل (1967-1970)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',11,0,200,'normal','في أي عام سقطت الدولة العثمانية؟','1924 (إلغاء الخلافة)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',11,1,200,'normal','من هو مكتشف الدورة الدموية الصغرى؟','ابن النفيس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',11,2,400,'normal','متى تم اختراع المطبعة؟','1440 (على يد جوتنبرج)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',11,3,400,'normal','من هو "بطل الشعوب" الذي حرر دول أمريكا الجنوبية من إسبانيا؟','سيمون بوليفار',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',11,4,600,'normal','في أي عام تم تحطيم جدار برلين؟','1989',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',11,5,600,'normal','من هو القائد المسلم الذي فتح السند؟','محمد بن القاسم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',12,0,200,'normal','ما هي المعركة التي وقعت بين المسلمين والفرس؟','معركة القادسية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',12,1,200,'normal','من هو الزعيم الهندي الذي نادى بالاستقلال السلمي؟','المهاتما غاندي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',12,2,400,'normal','ما هي معركة "واترلو"؟','آخر معركة لنابليون بونابرت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('history',12,3,400,'normal','من هو الملك الذي بنى حدائق بابل؟','نبوخذ نصر الثاني',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
on conflict(category,version,ord) do update set value=excluded.value,type=excluded.type,q=excluded.q,a=excluded.a,note=excluded.note,flag=excluded.flag,clues=excluded.clues,num=excluded.num,evidence=excluded.evidence,suspects=excluded.suspects,image=excluded.image;

commit;
