-- FAKKIR seed — part 4 of 9. Generated; do not edit by hand.
-- Run server/sql/schema.sql once, then paste these part files into the Supabase SQL Editor in order (01, 02, ...).
begin;

-- Categories (idempotent; required by the questions foreign key)
insert into categories(slug,name,color,image,sort_order) values
('geo','الجغرافيا','blue','assets/img/categories/geo.png',0),
('history','التاريخ','gold','assets/img/categories/history.png',1),
('palestine','فلسطين','green','assets/img/categories/palestine.png',2),
('seerah','السيرة النبوية','teal','assets/img/categories/seerah.png',3),
('quran','القرآن الكريم','green','assets/img/categories/quran.png',4),
('flags','أعلام الدول','red','assets/img/categories/flags.png',5),
('sports','الرياضة','cyan','assets/img/categories/sports.png',6),
('football','كرة القدم','blue','assets/img/categories/football.png',7),
('riddles','الألغاز','purple','assets/img/categories/riddles.png',8),
('science','العلوم','teal','assets/img/categories/science.png',9),
('tech','التكنولوجيا','cyan','assets/img/categories/tech.png',10),
('animals','عالم الحيوان','gold','assets/img/categories/animals.png',11),
('general','المعلومات العامة','gold','assets/img/categories/general.png',12),
('math','الرياضيات والأرقام','blue','assets/img/categories/math.png',13),
('whoami','احزر ماذا أنا','purple','assets/img/categories/whoami.png',14),
('proverbs','تكملة المثل','teal','assets/img/categories/proverbs.png',15),
('dish','ما هي الأكلة','red','assets/img/categories/dish.png',16),
('crime','الجريمة','red','assets/img/categories/crime.png',17),
('rescue','إنقاذ المتهم','green','assets/img/categories/rescue.png',18),
('closest','الأقرب إلى الرقم','purple','assets/img/categories/closest.png',19),
('capitals','عواصم الدول','blue','assets/img/categories/capitals.png',20),
('currencies','عملات الدول','gold','assets/img/categories/currencies.png',21),
('verse','أكمل الآية','green','assets/img/categories/verse.png',22),
('ordering','الترتيب الصحيح','cyan','assets/img/categories/ordering.png',23),
('players','احزر اللاعب','cyan','assets/img/categories/players.png',24)
on conflict(slug) do update set name=excluded.name,color=excluded.color,image=excluded.image,sort_order=excluded.sort_order;

-- Questions 751..1000
insert into questions(category,version,ord,value,type,q,a,note,flag,clues,num,evidence,suspects,image) values
('riddles',6,0,200,'normal','ما هو الشيء الذي له أرجل ولا يمشي؟','الطاولة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',6,1,200,'normal','ما هو الشيء الذي يرفع أثقالاً ولا يستطيع رفع مسمار؟','البحر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',6,2,400,'normal','ما هو الشيء الذي يمتلك قلباً لا ينبض؟','الخرشوف',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',6,3,400,'normal','ما هو الشيء الذي تضعه في الثلاجة ولا يبرد؟','الفلفل الحار',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',6,4,600,'normal','أنا طويل عندما أكون شاباً، وقصير عندما أكون عجوزاً، فمن أنا؟','الشمعة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',6,5,600,'normal','ما هو الشيء الذي له وجهان ولا يملك رأساً؟','العملة المعدنية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',7,0,200,'normal','ما هو الشيء الذي يتكلم كل لغات العالم؟','صدى الصوت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',7,1,200,'normal','ما هو الشيء الذي يقرصك دون أن تراه؟','الهواء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',7,2,400,'normal','ما هو الشيء الذي يمتلك ساقاً واحدة وثلاث عيون؟','إشارة المرور',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',7,3,400,'normal','ما هو الشيء الذي يمتلك أسناناً ولا يعض؟','المشط',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',7,4,600,'normal','ما هو الشيء الذي إذا وضعته في الماء لا يبتل؟','الظل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',7,5,600,'normal','ما هو الشيء الذي إذا ناديت باسمه كسرته؟','الصمت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',8,0,200,'normal','ما هو الشيء الذي يكسو الناس وهو عارٍ؟','الإبرة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',8,1,200,'normal','ما هو الشيء الذي تراه في الليل ثلاث مرات وفي النهار مرة واحدة؟','حرف اللام',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',8,2,400,'normal','ما هو الشيء الذي إذا أطعمته عاش، وإذا سقيته مات؟','النار',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',8,3,400,'normal','ما هو الشيء الذي يملك أذنين ولا يسمع؟','القبعة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',8,4,600,'normal','ما هو الشيء الذي يوجد في الدقيقة مرتين وفي القرن مرة واحدة ولا يوجد في السنة؟','حرف القاف',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',8,5,600,'normal','أملك مدناً ولكن لا أملك بيوتاً، وأملك جبالاً ولكن لا أملك أشجاراً، فمن أنا؟','الخريطة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',9,0,200,'normal','ما هو الشيء الذي يدق بلا قلب؟','الساعة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',9,1,200,'normal','ما هو الشيء الذي لا يبتل حتى لو دخل الماء؟','الضوء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',9,2,400,'normal','ما هو الشيء الذي إذا قمت بقلبه نقصت قيمته؟','رقم 9',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',9,3,400,'normal','ما هو الشيء الذي كلما زاد الطباخ زاد سوءاً؟','الملح',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',9,4,600,'normal','ما هو الشيء الذي يمتلك 13 قلباً في أوراق اللعب؟','ملك القلوب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',9,5,600,'normal','شيء له أربع أرجل في الصباح، واثنتان في الظهيرة، وثلاث في المساء؟','الإنسان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',10,0,200,'normal','ما هو الشيء الذي يأكل ولا يشبع؟','النار',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',10,1,200,'normal','ما هو الشيء الذي يرى كل شيء وليس له عيون؟','المرآة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',10,2,400,'normal','أبدأ بـ "ط" وأنتهي بـ "ب" وأسكن في بطنك، فمن أنا؟','طعام',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',10,3,400,'normal','ما هو الشيء الذي يمتلك أصابع ولا يملك يداً؟','القفاز',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',10,4,600,'normal','ما هو الشيء الذي تراه في دقيقة مرتين؟','حرف القاف',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',10,5,600,'normal','ما هو الشيء الذي يمتلك لسانًا ولا يتكلم؟','الحذاء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',11,0,200,'normal','ما هو الشيء الذي إذا قطعته أصبح أطول؟','الخندق',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',11,1,200,'normal','ما هو الشيء الذي تملكه أنت ويستخدمه الآخرون أكثر منك؟','اسمك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',11,2,400,'normal','ما هو الشيء الذي يملك ثقوباً ومع ذلك يحفظ الماء؟','الإسفنج',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',11,3,400,'normal','ما هو الشيء الذي يدخل صلباً ويخرج سائلاً؟','الثلج',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',11,4,600,'normal','ما هو الشيء الذي يمتلك سرعة الضوء ومع ذلك لا يتحرك؟','لا شيء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',11,5,600,'normal','أخت خالك ولكن لست خالتك، فمن أنا؟','أمك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',12,0,200,'normal','ما هو الشيء الذي يمتلك ريشاً ولا يطير؟','الوسادة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',12,1,200,'normal','ما هو الشيء الذي لا يغلق أبداً؟','الباب المفتوح',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',12,2,400,'normal','ما هو الشيء الذي يمتلك قدماً واحدة ولا يملك جسداً؟','الفطر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',12,3,400,'normal','ما هو الشيء الذي يملك رأساً ولا يملك عقلاً؟','الدبوس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',12,4,600,'normal','ما هو الشيء الذي يحمل الماء ويصرف الماء؟','الإسفنج',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',12,5,600,'normal','ما هو الشيء الذي له القدرة على الرؤية بلا أعين؟','المرآة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',13,0,200,'normal','ما هو الشيء الذي له رأس ولا عين له؟','الدبوس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',13,1,200,'normal','ما هو الشيء الذي يسير أمامك ولا تراه؟','المستقبل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',13,2,400,'normal','ما هو الشيء الذي لا يملك صوتاً ومع ذلك يخبرك بكل شيء؟','الكتاب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',13,3,400,'normal','ما هو الشيء الذي تراه ولا يراك؟','الظل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',13,4,600,'normal','ما هو الشيء الذي يمتلك فماً ولا يأكل؟','النهر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',13,5,600,'normal','ما هو الشيء الذي يمتلك أسناناً ولا يعض؟','المشط',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',14,0,200,'normal','ما هو الشيء الذي إذا أكلته كله نفعك، وإذا أكلت نصفه قتلك؟','السمسم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',14,1,200,'normal','ما هو الشيء الذي يولد في كل شهر مرة؟','القمر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',14,2,400,'normal','ما هو الشيء الذي يرتفع ولا ينزل؟','العمر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',14,3,400,'normal','ما هو الشيء الذي تكسره بمجرد أن تنطق باسمه؟','الصمت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',14,4,600,'normal','ما هو الشيء الذي يعطيك القوة لتمشي عبر الحائط؟','الباب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',14,5,600,'normal','ما هو الشيء الذي يوجد في أول الشتاء وفي آخر الصيف؟','حرف الشين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',15,0,200,'normal','ما هو الشيء الذي كلما زاد نقص؟','العمر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',15,1,200,'normal','ما هو الشيء الذي يمتلك رقبة ولا يملك رأساً؟','القميص',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',15,2,400,'normal','ما هو الشيء الذي يمتلك عيوناً كثيرة ولا يرى؟','البطاطس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',15,3,400,'normal','ما هو الشيء الذي له قدرة على المشي والوقوف وليس له أقدام؟','الساعة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',15,4,600,'normal','ما هو الشيء الذي لا يمشي إلا إذا ضربته على رأسه؟','المسمار',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('riddles',15,5,600,'normal','ما هو الشيء الذي كلما زاد الحاضرون نقص؟','الطعام',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',1,0,200,'normal','ما هو الكوكب الذي يلقب بـ "الكوكب الأحمر"؟','المريخ',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',1,1,200,'normal','ما هو الغاز الذي نتنفسه للحصول على الحياة؟','الأكسجين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',1,2,400,'normal','ما هو الغاز الذي يشكل الجزء الأكبر من الغلاف الجوي؟','النيتروجين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',1,3,400,'normal','ما اسم العملية التي تصنع بها النباتات غذاءها؟','البناء الضوئي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',1,4,600,'normal','ما هو الثقب الأسود؟','منطقة في الفضاء جاذبيتها قوية جداً لا تسمح حتى للضوء بالهروب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',1,5,600,'normal','ما هو قانون نيوتن الثاني؟','$F = m \times a$ (القوة تساوي الكتلة في التسارع)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',2,0,200,'normal','كم عدد كواكب المجموعة الشمسية؟','8 كواكب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',2,1,200,'normal','ما هي أقرب نجم إلى الأرض؟','الشمس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',2,2,400,'normal','كم عدد الكروموسومات في الخلية البشرية الطبيعية؟','46 كروموسوم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',2,3,400,'normal','ما هو الحمض النووي المسؤول عن الوراثة؟','DNA',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',2,4,600,'normal','ما هي المادة المظلمة؟','مادة غير مرئية تشكل معظم كتلة الكون وتؤثر بجاذبيتها',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',2,5,600,'normal','ما هو الانشطار النووي؟','انقسام نواة ذرة ثقيلة إلى أنوية أخف مع إطلاق طاقة هائلة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',3,0,200,'normal','ما هو أسرع حيوان بري في العالم؟','الفهد (الشيتا)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',3,1,200,'normal','ما هو العضو الذي يضخ الدم في جسم الإنسان؟','القلب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',3,2,400,'normal','ما هي سرعة الضوء التقريبية؟','300 ألف كيلومتر في الثانية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',3,3,400,'normal','ما هو الرمز الكيميائي للماء؟','H2O',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',3,4,600,'normal','ما هو "مبدأ عدم اليقين" لهايزنبرج؟','لا يمكن تحديد موقع وسرعة جسيم دونري في آن واحد بدقة مطلقة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',3,5,600,'normal','ماذا تعني النسبة الذهبية في الطبيعة؟','نسبة رياضية تظهر في تكرارات الأشكال والنمو الطبيعي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',4,0,200,'normal','ما هي الحالة الصلبة للماء؟','الثلج',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',4,1,200,'normal','ما هو أصغر جزء في المادة؟','الذرة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',4,2,400,'normal','ما هو الكوكب الذي يمتلك حلقات واضحة حوله؟','زحل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',4,3,400,'normal','ماذا نسمي الحيوانات التي تأكل اللحوم والنباتات؟','القوارت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',4,4,600,'normal','ما هو الجينوم البشري؟','الخريطة الكاملة لتسلسل الـ DNA في الإنسان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',4,5,600,'normal','ما هي "المادة المضادة"؟','جسيمات لها نفس كتلة الجسيمات العادية لكن بشحنة معاكسة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',5,0,200,'normal','ما اسم الحيوان الذي يلقب بـ "سفينة الصحراء"؟','الجمل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',5,1,200,'normal','ما هو الغاز الذي يطرده النبات في عملية البناء الضوئي؟','الأكسجين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',5,2,400,'normal','ما هو العضو المسؤول عن توازن الجسم؟','الأذن الداخلية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',5,3,400,'normal','ما هو أبرد مكان في المجموعة الشمسية؟','نبتون (أو المناطق المظلمة في الكواكب البعيدة)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',5,4,600,'normal','كيف تتكون النجوم النيوترونية؟','من انهيار نواة نجم عملاق بعد انفجار سوبرنوفا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',5,5,600,'normal','ما هو قانون الديناميكا الحرارية الثاني؟','الإنتروبيا (العشوائية) في نظام معزول تزداد دائماً',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',6,0,200,'normal','ما هي أقوى مادة طبيعية على وجه الأرض؟','الألماس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',6,1,200,'normal','ما هي القوة التي تجذب الأشياء لمركز الأرض؟','الجاذبية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',6,2,400,'normal','ما اسم قوة المقاومة التي تمنع حركة الأجسام على الأسطح؟','الاحتكاك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',6,3,400,'normal','ما هي المادة التي تزيد سرعة التفاعل الكيميائي دون أن تستهلك؟','الحافز (العامل المساعد)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',6,4,600,'normal','ما هي الأشعة الكونية؟','جسيمات مشحونة عالية الطاقة تأتي من خارج النظام الشمسي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',6,5,600,'normal','ما هي الخلايا الجذعية؟','خلايا غير متخصصة يمكنها التحول لأي نوع من خلايا الجسم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',7,0,200,'normal','كم عدد عظام جسم الإنسان البالغ؟','206 عظمة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',7,1,200,'normal','ما هو أضخم كوكب في مجموعتنا الشمسية؟','المشتري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',7,2,400,'normal','ما هو أصغر كوكب في المجموعة الشمسية؟','عطارد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',7,3,400,'normal','كم يبلغ عدد نبضات قلب الإنسان السليم في الدقيقة تقريباً؟','60-100 نبضة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',7,4,600,'normal','ما هو "تأثير دوبلر"؟','تغير تردد الموجات الصوتية أو الضوئية بسبب حركة المصدر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',7,5,600,'normal','ما هي البلازما؟','الحالة الرابعة للمادة (غاز متأين بشدة)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',8,0,200,'normal','ما اسم المادة التي تعطي النبات لونه الأخضر؟','الكلوروفيل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',8,1,200,'normal','ما هو أسرع شيء في الكون؟','الضوء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',8,2,400,'normal','ماذا تسمى الصخور التي تنصهر في باطن الأرض؟','الصهارة (الماجما)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',8,3,400,'normal','ما هو الفيتامين الذي نحصل عليه من أشعة الشمس؟','فيتامين د',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',8,4,600,'normal','ما هو الإشعاع الميكروي الخلفي للكون؟','بقايا حرارية من الانفجار العظيم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',8,5,600,'normal','ماذا يعني مصطلح "التطور المتقارب"؟','تطور صفات متشابهة في كائنات غير مرتبطة وراثياً',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',9,0,200,'normal','ما هي أكبر حاسة عند الإنسان؟','الجلد (حاسة اللمس)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',9,1,200,'normal','ما اسم العلم الذي يدرس الكائنات الحية؟','علم الأحياء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',9,2,400,'normal','ما اسم القوة التي تبقي الكواكب في مداراتها؟','الجاذبية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',9,3,400,'normal','ما هو العنصر الأكثر وفرة في الكون؟','الهيدروجين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',9,4,600,'normal','ما هي الجاذبية الكمية؟','نظرية تحاول دمج ميكانيكا الكم مع النسبية العامة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',9,5,600,'normal','ما هو إنزيم "تيلوميراز"؟','إنزيم يحمي أطراف الكروموسومات من القصر أثناء الانقسام',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',10,0,200,'normal','ماذا نسمي صغار الضفادع؟','أبو ذنيبة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',10,1,200,'normal','ما هو الغاز الذي نخرجه من أجسامنا أثناء الزفير؟','ثاني أكسيد الكربون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',10,2,400,'normal','ما هي وحدة قياس القوة؟','النيوتن',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',10,3,400,'normal','ماذا نسمى تحول المادة من الغاز إلى السائل؟','التكثف',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',10,4,600,'normal','ما هي "الكتلة الحرجة" في التفاعلات النووية؟','أصغر كمية من الوقود النووي اللازمة لاستمرار التفاعل المتسلسل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',10,5,600,'normal','ما هو التكافؤ الكيميائي؟','قدرة الذرة على الاتحاد مع ذرات أخرى',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',11,0,200,'normal','ما هي وحدة قياس درجة الحرارة في معظم العالم؟','السيليزيوس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',11,1,200,'normal','ما هو أكبر حيوان يعيش على الأرض حالياً؟','الحوت الأزرق',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',11,2,400,'normal','ما هو الجهاز الذي يحول الطاقة الكهربائية إلى طاقة حركية؟','المحرك الكهربائي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',11,3,400,'normal','ما هي وظيفة كريات الدم الحمراء؟','نقل الأكسجين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',11,4,600,'normal','ما هي "سنة ضوئية"؟','المسافة التي يقطعها الضوء في سنة واحدة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',11,5,600,'normal','ما هو البوزون (مثل بوزون هيغز)؟','جسيم مسؤول عن منح الجسيمات الأخرى كتلتها',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',12,0,200,'normal','كم يوماً تستغرق الأرض للدوران حول الشمس؟','365.25 يوماً',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',12,1,200,'normal','ماذا نسمي دراسة النجوم والكواكب؟','علم الفلك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',12,2,400,'normal','ما اسم الحيوان الثديي الوحيد الذي يطير؟','الخفاش',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',12,3,400,'normal','ما هي طبقة الأرض التي نعيش فوقها؟','القشرة الأرضية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',12,4,600,'normal','ماذا يعني "النمو الأسي"؟','نمو يتناسب مع حجم الكمية الحالية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',12,5,600,'normal','ما هي "الإنتروبيا"؟','مقياس للعشوائية أو الفوضى في نظام ما',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',13,0,200,'normal','أي معدن يكون سائلاً في درجة حرارة الغرفة؟','الزئبق',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',13,1,200,'normal','ما هي الطبقة التي تحمي الأرض من أشعة الشمس الضارة؟','طبقة الأوزون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',13,2,400,'normal','ما هو الغاز الذي يجعل المشروبات الغازية فوارة؟','ثاني أكسيد الكربون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',13,3,400,'normal','ما هي وحدة قياس التيار الكهربائي؟','الأمبير',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',13,4,600,'normal','ما هي "النظائر"؟','ذرات لنفس العنصر تختلف في عدد النيوترونات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',13,5,600,'normal','ما هي ظاهرة "الاحتباس الحراري"؟','حبس حرارة الشمس داخل الغلاف الجوي بسبب الغازات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',14,0,200,'normal','ما هو أطول نهر في العالم؟','النيل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',14,1,200,'normal','ماذا نسمى تحول المادة من الحالة السائلة إلى الغازية؟','التبخر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',14,2,400,'normal','ما اسم أكبر بركان في المجموعة الشمسية؟','أوليمبوس مونس (على المريخ)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',14,3,400,'normal','ماذا نسمى دراسة الصخور والأرض؟','الجيولوجيا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',14,4,600,'normal','ما هو "التشابك الكمي"؟','حالة ترتبط فيها الجسيمات بحيث تؤثر حالة أحدهما على الآخر لحظياً مهما كانت المسافة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',14,5,600,'normal','ما هو "الانزياح نحو الأحمر"؟','ظاهرة تدل على ابتعاد المجرات عنا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',15,0,200,'normal','ما هو الحيوان الذي ينام وعيناه مفتوحتان؟','السمك',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',15,1,200,'normal','ما هو الملح الشائع المستخدم في الطعام؟','كلوريد الصوديوم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',15,2,400,'normal','ما هو الفرق بين الوزن والكتلة؟','الكتلة مقدار المادة، الوزن هو قوة الجاذبية عليها',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',15,3,400,'normal','ما هي المادة التي لا تسمح بمرور التيار الكهربائي؟','العازل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',15,4,600,'normal','ما هي الخلية البدائية النواة؟','خلية لا تمتلك غشاءً نووياً (مثل البكتيريا)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('science',15,5,600,'normal','ما هو قانون الجذب العام لنيوتن؟','القوة تتناسب طردياً مع الكتلتين وعكسياً مع مربع المسافة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',1,0,200,'normal','ما هو الجهاز الذي نستخدمه يومياً للاتصال وتصفح الإنترنت؟','الهاتف الذكي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',1,1,200,'normal','ما اسم محرك البحث الأكثر شهرة في العالم؟','جوجل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',1,2,400,'normal','ما هو الذكاء الاصطناعي؟','قدرة الآلات على محاكاة التفكير البشري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',1,3,400,'normal','ما هو المعالج (CPU)؟','هو "عقل" الحاسوب المسؤول عن معالجة البيانات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',1,4,600,'normal','ما هو الحاسوب الكمي (Quantum Computer)؟','حاسوب يعتمد على "الكيو بت" لمعالجة البيانات بسرعات هائلة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',1,5,600,'normal','ما هي الشبكات العصبية الاصطناعية (Neural Networks)؟','نموذج حاسوبي مستوحى من الدماغ البشري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',2,0,200,'normal','ماذا تعني كلمة "WiFi"؟','تقنية الاتصال اللاسلكي بالإنترنت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',2,1,200,'normal','ما هو نظام التشغيل الأكثر استخداماً للهواتف الذكية؟','أندرويد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',2,2,400,'normal','ماذا يعني التشفير (Encryption)؟','تحويل البيانات إلى صيغة غير مفهومة لحمايتها',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',2,3,400,'normal','ما هو "HTML"؟','لغة ترميز لبناء صفحات الويب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',2,4,600,'normal','ماذا يعني مصطلح "طول الموجة" في تقنيات الاتصال؟','المسافة بين قمتين متتاليتين للموجة الكهرومغناطيسية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',2,5,600,'normal','ما هو "مبدأ فون نيومان" في تصميم الحواسيب؟','تصميم يخزن البرنامج والبيانات في نفس الذاكرة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',3,0,200,'normal','ما اسم الشركة التي أسسها ستيف جوبز؟','أبل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',3,1,200,'normal','ما هي الشبكة الاجتماعية التي تعتمد على الصور بشكل أساسي؟','إنستغرام',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',3,2,400,'normal','ما هو الفرق بين الذاكرة العشوائية (RAM) والقرص الصلب (HDD)؟','الرام مؤقتة وسريعة، القرص الصلب دائم وبطيء',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',3,3,400,'normal','ما هو "البيانات الضخمة" (Big Data)؟','مجموعات ضخمة من البيانات التي يصعب معالجتها بالطرق التقليدية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',3,4,600,'normal','ما هي "الخوارزمية الجينية" (Genetic Algorithm)؟','خوارزمية تطور الحلول بناءً على الانتقاء الطبيعي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',3,5,600,'normal','ما هو "التحويل الرقمي" (Digital Transformation)؟','دمج التكنولوجيا في كافة جوانب العمل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',4,0,200,'normal','ماذا نسمي البرامج الخبيثة التي تضر الحاسوب؟','فيروسات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',4,1,200,'normal','ما هو الجهاز الذي يحول الإشارات الرقمية إلى بيانات يمكن قراءتها؟','المودم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',4,2,400,'normal','ما هي الحوسبة السحابية؟','تقديم خدمات تقنية عبر الإنترنت بدلاً من القرص المحلي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',4,3,400,'normal','ماذا تعني "Open Source"؟','البرمجيات التي يمكن للجميع الاطلاع على كودها وتعديله',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',4,4,600,'normal','ما هي "الحوسبة الطرفية" (Edge Computing)؟','معالجة البيانات قريباً من مكان توليدها بدلاً من السحابة المركزية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',4,5,600,'normal','ماذا تعني "Zero-day vulnerability"؟','ثغرة أمنية غير مكتشفة ولا يوجد لها تصحيح',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',5,0,200,'normal','ما اسم منصة الفيديوهات الأشهر عالمياً؟','يوتيوب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',5,1,200,'normal','ماذا يعني اختصار "PC"؟','حاسوب شخصي (Personal Computer)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',5,2,400,'normal','ما هو "البلوكشين" (Blockchain)؟','سجل رقمي مشفر ومنتشر لتسجيل المعاملات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',5,3,400,'normal','ما هو اسم أول لغة برمجة عالية المستوى؟','فورتران',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',5,4,600,'normal','ما هو "التعلم المعزز" (Reinforcement Learning)؟','تعلم الآلة من خلال التجربة والمكافأة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',5,5,600,'normal','ما هي "بروتوكولات التوجيه" (Routing Protocols)؟','قواعد تحديد مسار حزم البيانات في الشبكات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',6,0,200,'normal','ما هو الاختصار المستخدم لنسخ النصوص؟','Ctrl + C',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',6,1,200,'normal','ماذا نسمي المكان الذي تخزن فيه ملفاتك سحابياً؟','التخزين السحابي (Cloud Storage)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',6,2,400,'normal','ماذا يعني "Cybersecurity"؟','حماية الأنظمة والشبكات من الهجمات الإلكترونية',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',6,3,400,'normal','ما هو "IP Address"؟','هوية رقمية فريدة لكل جهاز على الإنترنت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',6,4,600,'normal','ما هي "الذاكرة المخبئية" (Cache Memory)؟','ذاكرة سريعة جداً قريبة من المعالج',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',6,5,600,'normal','ما هو الفرق بين "Compiler" و"Interpreter"؟','الكومبايلر يحول الكود دفعة واحدة، المفسر يترجمه سطراً بسطر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',7,0,200,'normal','ما هو جهاز الإدخال الأساسي في الحاسوب؟','لوحة المفاتيح',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',7,1,200,'normal','ما اسم المتصفح الخاص بشركة مايكروسوفت؟','إيدج',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',7,2,400,'normal','ما هو "الواقع الافتراضي" (VR)؟','تقنية تحاكي بيئة حقيقية في عالم رقمي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',7,3,400,'normal','ما هو "الواقع المعزز" (AR)؟','دمج عناصر رقمية في العالم الحقيقي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',7,4,600,'normal','ما هو "عنق الزجاجة" (Bottleneck) في الحواسيب؟','تقييد الأداء بسبب أضعف مكون في النظام',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',7,5,600,'normal','ما هي "العمليات المتوازية" (Parallel Processing)؟','تقسيم المهمة إلى أجزاء ومعالجتها في آن واحد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',8,0,200,'normal','ما هو "الماوس"؟','جهاز تأشير للتحكم في واجهة الحاسوب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',8,1,200,'normal','ماذا تعني كلمة "Download"؟','تحميل البيانات من الإنترنت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',8,2,400,'normal','ما هو "الخادم" (Server)؟','حاسوب مركزي يقدم خدمات لأجهزة أخرى',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',8,3,400,'normal','ماذا تعني "HTTP"؟','بروتوكول نقل النص التشعبي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',8,4,600,'normal','ما هو "المنطق الضبابي" (Fuzzy Logic)؟','منطق رياضي يتعامل مع درجات الحقيقة بين 0 و1',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',8,5,600,'normal','ماذا يعني مصطلح "Latency" في الشبكات؟','التأخير في وصول البيانات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',9,0,200,'normal','ما هي لغة البرمجة التي تشتهر بكونها سهلة للمبتدئين؟','بايثون',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',9,1,200,'normal','ما اسم نظام التشغيل الخاص بأجهزة الكمبيوتر من أبل؟','ماك (macOS)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',9,2,400,'normal','ما هي "إنترنت الأشياء" (IoT)؟','ربط الأجهزة المنزلية والذكية بالإنترنت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',9,3,400,'normal','ما هو "الفلاش ميموري"؟','وحدة تخزين بيانات محمولة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',9,4,600,'normal','ما هي لغة "Assembly"؟','لغة برمجة قريبة جداً من لغة الآلة (الأصفار والآحاد)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',9,5,600,'normal','ما هو "الاستنتاج الاستقرائي" في الذكاء الاصطناعي؟','توليد معرفة عامة من بيانات محددة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',10,0,200,'normal','ما هي التكنولوجيا التي تسمح بدفع الأموال عبر الهاتف؟','المحفظة الرقمية (Digital Wallet)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',10,1,200,'normal','ما هو البريد الإلكتروني؟','وسيلة لإرسال الرسائل عبر الإنترنت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',10,2,400,'normal','ما هي لغة البرمجة الأساسية لتطبيقات أندرويد؟','كوتلن (Kotlin) أو جافا',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',10,3,400,'normal','ماذا نسمي اختراق النظام للحصول على بيانات؟','هجوم إلكتروني',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',10,4,600,'normal','ما هو "تعدين البيانات" (Data Mining)؟','استخراج أنماط مفيدة من بيانات ضخمة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',10,5,600,'normal','ماذا يعني "Virtualization"؟','تشغيل بيئات افتراضية متعددة على عتاد مادي واحد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',11,0,200,'normal','ماذا يعني مصطلح "Hardware"؟','المكونات المادية للحاسوب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',11,1,200,'normal','ماذا يعني مصطلح "Software"؟','البرمجيات أو التطبيقات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',11,2,400,'normal','ما هو "Cookie" في المتصفح؟','ملف صغير يحفظ بيانات المستخدم',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',11,3,400,'normal','ما هو نظام إدارة المحتوى (CMS)؟','برنامج لإدارة محتوى المواقع مثل ووردبريس',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',11,4,600,'normal','ما هي "البت" (Bit) مقابل "البايت" (Byte)؟','البت هو أصغر وحدة، والبايت يتكون من 8 بت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',11,5,600,'normal','ما هو "التفرد التكنولوجي" (Singularity)؟','فرضية وصول الذكاء الاصطناعي لمرحلة تجاوز الذكاء البشري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',12,0,200,'normal','ما هو الرابط الذي يفتح صفحة الويب؟','URL',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',12,1,200,'normal','ما هو الجهاز الذي يطبع الصور على الورق؟','الطابعة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',12,2,400,'normal','ما هي "لوحة الأم" (Motherboard)؟','اللوحة الأساسية التي تربط مكونات الحاسوب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',12,3,400,'normal','ماذا يعني مصطلح "Bandwidth"؟','سعة نقل البيانات عبر الشبكة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',12,4,600,'normal','ما هي "مصفوفة البوابات المنطقية" (FPGA)؟','دوائر إلكترونية قابلة للبرمجة بعد التصنيع',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',12,5,600,'normal','ماذا يعني "Denial of Service" (DoS)؟','هجوم يهدف لإيقاف خدمة النظام عن طريق إغراقه بالطلبات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',13,0,200,'normal','ماذا نسمي الشخص الذي يطور البرامج؟','مبرمج',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',13,1,200,'normal','ما اسم نظام التشغيل الأكثر شيوعاً للحواسيب المكتبية؟','ويندوز',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',13,2,400,'normal','ما هو "الفيرموير" (Firmware)؟','برمجيات مدمجة تتحكم في العتاد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',13,3,400,'normal','ما هو اسم الشركة التي صنعت معالجات "Ryzen"؟','AMD',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',13,4,600,'normal','ما هو "الاستدلال" (Inference) في تعلم الآلة؟','استخدام النموذج المدرب للتنبؤ ببيانات جديدة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',13,5,600,'normal','ما هي "خوارزمية التجزئة" (Hashing)؟','تحويل البيانات إلى سلسلة ثابتة الطول',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',14,0,200,'normal','ما هي البطارية التي لا تُشحن وتُرمى؟','البطارية الجافة (القلوية)',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',14,1,200,'normal','ما هو البلوتوث؟','تقنية لنقل البيانات بين جهازين قريبين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',14,2,400,'normal','ما هو "الأتمتة" (Automation)؟','تنفيذ المهام دون تدخل بشري',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',14,3,400,'normal','ما هو "البرمجة كائنية التوجه" (OOP)؟','نموذج برمجي يعتمد على الكائنات',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',14,4,600,'normal','ما هو "ناقل البيانات" (Bus)؟','مسار مادي لنقل البيانات داخل الحاسوب',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',14,5,600,'normal','ما هي "الدوائر المتكاملة" (IC)؟','مجموعة من المكونات الإلكترونية على شريحة سيلكون واحدة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',15,0,200,'normal','ما هو "الآيباد"؟','جهاز لوحي',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',15,1,200,'normal','ماذا يعني "Offline"؟','عدم الاتصال بالإنترنت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',15,2,400,'normal','ماذا يعني "API"؟','واجهة برمجة التطبيقات لربط البرامج ببعضها',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',15,3,400,'normal','ما هي الشاشة ذات الدقة العالية المعروفة بـ "4K"؟','دقة عرض 3840×2160 بكسل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',15,4,600,'normal','ما هو "بروتوكول TCP/IP"؟','حزمة البروتوكولات الأساسية للإنترنت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('tech',15,5,600,'normal','ما هو "الذكاء الاصطناعي العام" (AGI)؟','ذكاء اصطناعي يمكنه تنفيذ أي مهمة فكرية يقوم بها الإنسان',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',1,0,200,'normal','من هو ملك الغابة؟','الأسد',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',1,1,200,'normal','ما الحيوان الذي يلقب بسفينة الصحراء؟','الجمل',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',1,2,400,'normal','ما هو الحيوان الذي يمتلك قلوباً ثلاثة؟','الأخطبوط',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',1,3,400,'normal','ما هو الحيوان الذي يغطي جسمه الحراشف ويدافع عن نفسه بالتكور؟','البنغول',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',1,4,600,'normal','ما هو الحيوان الذي يمتلك أكبر حجم مخ مقارنة بجسمه بين الثدييات؟','الدلفين',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',1,5,600,'normal','ما هو الحيوان الذي يمتلك جهازه الهضمي أربع غرف للمعدة؟','البقرة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',2,0,200,'normal','من هو أضخم كائن على وجه الأرض؟','الحوت',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',2,1,200,'normal','ما الحيوان الذي يتميز برقبته الطويلة جداً؟','الزرافة',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',2,2,400,'normal','ما هو الحيوان الذي يمتلك القدرة على تجديد أطرافه المقطوعة؟','نجم البحر',NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('animals',2,3,400,'normal','ما هو الحيوان الذي يتحدث "بصدى الصوت"؟','الخفاش',NULL,NULL,NULL,NULL,NULL,NULL,NULL)
on conflict(category,version,ord) do update set value=excluded.value,type=excluded.type,q=excluded.q,a=excluded.a,note=excluded.note,flag=excluded.flag,clues=excluded.clues,num=excluded.num,evidence=excluded.evidence,suspects=excluded.suspects,image=excluded.image;

commit;
