// Curated dataset for the "احزر اللاعب" (Guess the Player) category.
// 90 footballers in 3 difficulty tiers (30 each):
//   tier200  = iconic, instantly recognizable        -> 200-point slots
//   tier400  = well-known to football followers       -> 400-point slots
//   tier600  = legends / harder to place              -> 600-point slots
// Each entry: ar (Arabic name = answer), wiki (English Wikipedia title for the
// photo), slug (local image filename), clue (Arabic prompt shown with the photo).

export const tier200 = [
  { ar: "ليونيل ميسي", wiki: "Lionel Messi", slug: "messi", clue: "نجم أرجنتيني وأحد أعظم اللاعبين في التاريخ، فاز بالكرة الذهبية ثماني مرات وبكأس العالم 2022." },
  { ar: "كريستيانو رونالدو", wiki: "Cristiano Ronaldo", slug: "ronaldo-cr7", clue: "أسطورة برتغالية ومن أكثر الهدافين تسجيلًا في التاريخ، لعب لمانشستر يونايتد وريال مدريد." },
  { ar: "نيمار", wiki: "Neymar", slug: "neymar", clue: "جناح برازيلي مهاري، انتقل من برشلونة إلى باريس سان جيرمان بصفقة قياسية عام 2017." },
  { ar: "كيليان مبابي", wiki: "Kylian Mbappé", slug: "mbappe", clue: "مهاجم فرنسي سريع، توّج بكأس العالم 2018 وهو في سن المراهقة." },
  { ar: "بيليه", wiki: "Pelé", slug: "pele", clue: "أسطورة برازيلية، اللاعب الوحيد الذي فاز بثلاث بطولات كأس عالم." },
  { ar: "دييغو مارادونا", wiki: "Diego Maradona", slug: "maradona", clue: "أسطورة أرجنتينية، صاحب هدف القرن وهدف اليد في مونديال 1986." },
  { ar: "زين الدين زيدان", wiki: "Zinedine Zidane", slug: "zidane", clue: "نجم فرنسي وصانع ألعاب، سجّل هدفين في نهائي كأس العالم 1998." },
  { ar: "رونالدينيو", wiki: "Ronaldinho", slug: "ronaldinho", clue: "ساحر برازيلي، فاز بالكرة الذهبية 2005 وأمتع الجماهير مع برشلونة." },
  { ar: "رونالدو البرازيلي", wiki: "Ronaldo (Brazilian footballer)", slug: "ronaldo-r9", clue: "الظاهرة البرازيلية، مهاجم فتّاك توّج هدافًا لكأس العالم 2002." },
  { ar: "محمد صلاح", wiki: "Mohamed Salah", slug: "salah", clue: "نجم مصري وجناح ليفربول، يُلقّب بالملك ومن أبرز هدافي الدوري الإنجليزي." },
  { ar: "كريم بنزيمة", wiki: "Karim Benzema", slug: "benzema", clue: "مهاجم فرنسي، قاد ريال مدريد للقب دوري الأبطال 2022 وفاز بالكرة الذهبية." },
  { ar: "إيرلينغ هالاند", wiki: "Erling Haaland", slug: "haaland", clue: "مهاجم نرويجي هدّاف، حطّم أرقامًا تهديفية مع مانشستر سيتي." },
  { ar: "روبرت ليفاندوفسكي", wiki: "Robert Lewandowski", slug: "lewandowski", clue: "مهاجم بولندي صريح، تألق طويلًا مع بايرن ميونخ ثم برشلونة." },
  { ar: "لوكا مودريتش", wiki: "Luka Modrić", slug: "modric", clue: "صانع ألعاب كرواتي، فاز بالكرة الذهبية 2018 بعد مونديال روسيا." },
  { ar: "كيفن دي بروين", wiki: "Kevin De Bruyne", slug: "debruyne", clue: "صانع ألعاب بلجيكي، من أفضل الممررين في العالم مع مانشستر سيتي." },
  { ar: "هاري كين", wiki: "Harry Kane", slug: "kane", clue: "مهاجم إنجليزي وهدّاف منتخب بلاده التاريخي، انتقل إلى بايرن ميونخ." },
  { ar: "أندريس إنييستا", wiki: "Andrés Iniesta", slug: "iniesta", clue: "نجم إسباني، سجّل هدف التتويج بكأس العالم 2010." },
  { ar: "تشافي هيرنانديز", wiki: "Xavi", slug: "xavi", clue: "صانع ألعاب إسباني وأسطورة برشلونة، درّب الفريق لاحقًا." },
  { ar: "ديفيد بيكهام", wiki: "David Beckham", slug: "beckham", clue: "نجم إنجليزي اشتهر بركلاته الحرة، لعب لمانشستر يونايتد وريال مدريد." },
  { ar: "زلاتان إبراهيموفيتش", wiki: "Zlatan Ibrahimović", slug: "ibrahimovic", clue: "مهاجم سويدي طويل القامة وصاحب شخصية قوية، لعب لأندية كبيرة عدة." },
  { ar: "تييري هنري", wiki: "Thierry Henry", slug: "henry", clue: "مهاجم فرنسي والهداف التاريخي لنادي أرسنال." },
  { ar: "واين روني", wiki: "Wayne Rooney", slug: "rooney", clue: "مهاجم إنجليزي والهداف التاريخي السابق لمانشستر يونايتد ومنتخب إنجلترا." },
  { ar: "سيرخيو راموس", wiki: "Sergio Ramos", slug: "ramos", clue: "مدافع إسباني صلب وقائد، اشتهر بأهدافه الحاسمة مع ريال مدريد." },
  { ar: "لويس سواريز", wiki: "Luis Suárez", slug: "suarez", clue: "مهاجم أوروغوياني، تألق مع ليفربول وبرشلونة بثلاثية هجومية شهيرة." },
  { ar: "كاكا", wiki: "Kaká", slug: "kaka", clue: "صانع ألعاب برازيلي، فاز بالكرة الذهبية 2007 مع ميلان." },
  { ar: "جانلويجي بوفون", wiki: "Gianluigi Buffon", slug: "buffon", clue: "حارس مرمى إيطالي أسطوري، توّج بكأس العالم 2006." },
  { ar: "إيكر كاسياس", wiki: "Iker Casillas", slug: "casillas", clue: "حارس مرمى إسباني وقائد، رفع كأس العالم 2010." },
  { ar: "أندريا بيرلو", wiki: "Andrea Pirlo", slug: "pirlo", clue: "صانع ألعاب إيطالي أنيق، أحد أفضل الممررين في جيله." },
  { ar: "ديدييه دروغبا", wiki: "Didier Drogba", slug: "drogba", clue: "مهاجم إيفواري قوي، أسطورة تشيلسي وصاحب هدف نهائي دوري الأبطال 2012." },
  { ar: "غاريث بيل", wiki: "Gareth Bale", slug: "bale", clue: "جناح ويلزي سريع، سجّل أهدافًا خارقة مع ريال مدريد." },
];

export const tier400 = [
  { ar: "أنطوان غريزمان", wiki: "Antoine Griezmann", slug: "griezmann", clue: "مهاجم فرنسي، من نجوم منتخب فرنسا بطل العالم 2018." },
  { ar: "بول بوغبا", wiki: "Paul Pogba", slug: "pogba", clue: "لاعب وسط فرنسي قوي، بطل العالم 2018 ولعب لمانشستر يونايتد ويوفنتوس." },
  { ar: "سون هيونغ مين", wiki: "Son Heung-min", slug: "son", clue: "جناح كوري جنوبي وقائد توتنهام، من أبرز نجوم آسيا." },
  { ar: "ساديو ماني", wiki: "Sadio Mané", slug: "mane", clue: "جناح سنغالي سريع، تألق مع ليفربول وفاز بكأس أمم أفريقيا." },
  { ar: "رياض محرز", wiki: "Riyad Mahrez", slug: "mahrez", clue: "جناح جزائري ماهر، قاد بلاده للقب أمم أفريقيا 2019 ولعب لمانشستر سيتي." },
  { ar: "نغولو كانتي", wiki: "N'Golo Kanté", slug: "kante", clue: "لاعب وسط فرنسي دؤوب، بطل العالم 2018 وأحد أفضل المدافعين المتوسطين." },
  { ar: "مانويل نوير", wiki: "Manuel Neuer", slug: "neuer", clue: "حارس مرمى ألماني، اشتهر بأسلوب الحارس المكتسح وتوّج بكأس العالم 2014." },
  { ar: "تيبو كورتوا", wiki: "Thibaut Courtois", slug: "courtois", clue: "حارس مرمى بلجيكي، تألق في نهائي دوري الأبطال 2022 مع ريال مدريد." },
  { ar: "توماس مولر", wiki: "Thomas Müller", slug: "muller", clue: "مهاجم وصانع ألعاب ألماني ذكي، أسطورة بايرن ميونخ وبطل العالم 2014." },
  { ar: "توني كروس", wiki: "Toni Kroos", slug: "kroos", clue: "لاعب وسط ألماني دقيق التمرير، بطل العالم 2014 ونجم ريال مدريد." },
  { ar: "سيرخيو أغويرو", wiki: "Sergio Agüero", slug: "aguero", clue: "مهاجم أرجنتيني، سجّل هدف لقب الدوري الإنجليزي الشهير لمانشستر سيتي 2012." },
  { ar: "إدينسون كافاني", wiki: "Edinson Cavani", slug: "cavani", clue: "مهاجم أوروغوياني هدّاف، الهداف التاريخي لباريس سان جيرمان." },
  { ar: "أنخيل دي ماريا", wiki: "Ángel Di María", slug: "dimaria", clue: "جناح أرجنتيني، سجّل في نهائي كأس العالم 2022." },
  { ar: "غونزالو هيغواين", wiki: "Gonzalo Higuaín", slug: "higuain", clue: "مهاجم أرجنتيني، لعب لريال مدريد ونابولي ويوفنتوس." },
  { ar: "أليسون بيكر", wiki: "Alisson", slug: "alisson", clue: "حارس مرمى برازيلي، حارس ليفربول ومنتخب البرازيل." },
  { ar: "فيرجيل فان دايك", wiki: "Virgil van Dijk", slug: "vandijk", clue: "مدافع هولندي قوي وقائد، أحد أفضل المدافعين مع ليفربول." },
  { ar: "رحيم سترلينغ", wiki: "Raheem Sterling", slug: "sterling", clue: "جناح إنجليزي سريع، لعب لمانشستر سيتي وتشيلسي." },
  { ar: "فينيسيوس جونيور", wiki: "Vinícius Júnior", slug: "vinicius", clue: "جناح برازيلي مهاري، سجّل هدف نهائي دوري الأبطال 2022 لريال مدريد." },
  { ar: "بيدري", wiki: "Pedri", slug: "pedri", clue: "موهبة إسبانية في خط الوسط، من نجوم برشلونة." },
  { ar: "فيل فودين", wiki: "Phil Foden", slug: "foden", clue: "لاعب وسط هجومي إنجليزي، خرّيج أكاديمية مانشستر سيتي." },
  { ar: "ماركوس راشفورد", wiki: "Marcus Rashford", slug: "rashford", clue: "مهاجم وجناح إنجليزي، خرّيج أكاديمية مانشستر يونايتد." },
  { ar: "بوكايو ساكا", wiki: "Bukayo Saka", slug: "saka", clue: "جناح إنجليزي شاب، من نجوم نادي أرسنال." },
  { ar: "لاوتارو مارتينيز", wiki: "Lautaro Martínez", slug: "lautaro", clue: "مهاجم أرجنتيني، قائد إنتر ميلان وبطل العالم 2022." },
  { ar: "فيكتور أوسيمين", wiki: "Victor Osimhen", slug: "osimhen", clue: "مهاجم نيجيري هدّاف، قاد نابولي للقب الدوري الإيطالي 2023." },
  { ar: "خاميس رودريغيز", wiki: "James Rodríguez", slug: "james", clue: "صانع ألعاب كولومبي، هداف كأس العالم 2014." },
  { ar: "راداميل فالكاو", wiki: "Radamel Falcao", slug: "falcao", clue: "مهاجم كولومبي هدّاف، لُقّب بالنمر." },
  { ar: "فيليبي كوتينيو", wiki: "Philippe Coutinho", slug: "coutinho", clue: "صانع ألعاب برازيلي، اشتهر بأهدافه من خارج المنطقة مع ليفربول." },
  { ar: "باولو ديبالا", wiki: "Paulo Dybala", slug: "dybala", clue: "مهاجم أرجنتيني ماهر، لعب ليوفنتوس وروما." },
  { ar: "جود بيلينغهام", wiki: "Jude Bellingham", slug: "bellingham", clue: "لاعب وسط إنجليزي شاب، انتقل إلى ريال مدريد وتألق سريعًا." },
  { ar: "كاسيميرو", wiki: "Casemiro", slug: "casemiro", clue: "لاعب وسط ارتكاز برازيلي، فاز بدوري الأبطال مرات عدة مع ريال مدريد." },
];

export const tier600 = [
  { ar: "كافو", wiki: "Cafu", slug: "cafu", clue: "ظهير أيمن برازيلي، القائد الذي رفع كأس العالم في ثلاث نهائيات متتالية." },
  { ar: "روبرتو كارلوس", wiki: "Roberto Carlos", slug: "robertocarlos", clue: "ظهير أيسر برازيلي، اشتهر بركلاته الحرة الصاروخية." },
  { ar: "روبرتو باجو", wiki: "Roberto Baggio", slug: "baggio", clue: "صانع ألعاب إيطالي، أهدر ركلة الترجيح الحاسمة في نهائي 1994." },
  { ar: "باولو مالديني", wiki: "Paolo Maldini", slug: "maldini", clue: "مدافع إيطالي أسطوري، أمضى مسيرته كلها مع ميلان." },
  { ar: "فرانكو باريزي", wiki: "Franco Baresi", slug: "baresi", clue: "مدافع إيطالي وقائد ميلان التاريخي في الثمانينيات والتسعينيات." },
  { ar: "جورجي هاجي", wiki: "Gheorghe Hagi", slug: "hagi", clue: "صانع ألعاب روماني موهوب، لُقّب بمارادونا الكاربات." },
  { ar: "جورج وياه", wiki: "George Weah", slug: "weah", clue: "مهاجم ليبيري، اللاعب الأفريقي الفائز بالكرة الذهبية، وصار رئيسًا لبلاده." },
  { ar: "هريستو ستويتشكوف", wiki: "Hristo Stoichkov", slug: "stoichkov", clue: "مهاجم بلغاري، هداف كأس العالم 1994 والفائز بالكرة الذهبية." },
  { ar: "دافور شوكر", wiki: "Davor Šuker", slug: "suker", clue: "مهاجم كرواتي، هداف كأس العالم 1998." },
  { ar: "ريفالدو", wiki: "Rivaldo", slug: "rivaldo", clue: "صانع ألعاب برازيلي، فاز بالكرة الذهبية 1999 وبكأس العالم 2002." },
  { ar: "روماريو", wiki: "Romário", slug: "romario", clue: "مهاجم برازيلي قصير وفتّاك، نجم تتويج 1994." },
  { ar: "بيبيتو", wiki: "Bebeto", slug: "bebeto", clue: "مهاجم برازيلي، اشتهر باحتفال هزّ المهد في مونديال 1994." },
  { ar: "كلارنس سيدورف", wiki: "Clarence Seedorf", slug: "seedorf", clue: "لاعب وسط هولندي، فاز بدوري الأبطال مع ثلاثة أندية مختلفة." },
  { ar: "باتريك فييرا", wiki: "Patrick Vieira", slug: "vieira", clue: "لاعب وسط فرنسي قوي، قائد أرسنال وبطل العالم 1998." },
  { ar: "فابيو كانافارو", wiki: "Fabio Cannavaro", slug: "cannavaro", clue: "مدافع إيطالي، فاز بالكرة الذهبية 2006 بعد قيادته إيطاليا للقب العالم." },
  { ar: "أليساندرو ديل بييرو", wiki: "Alessandro Del Piero", slug: "delpiero", clue: "مهاجم وصانع ألعاب إيطالي، أسطورة يوفنتوس." },
  { ar: "فرانشيسكو توتي", wiki: "Francesco Totti", slug: "totti", clue: "صانع ألعاب إيطالي، أسطورة نادي روما الذي لعب له طوال مسيرته." },
  { ar: "راؤول غونزاليس", wiki: "Raúl (footballer, born 1977)", slug: "raul", clue: "مهاجم إسباني، الهداف التاريخي السابق لريال مدريد." },
  { ar: "فيرناندو توريس", wiki: "Fernando Torres", slug: "torres", clue: "مهاجم إسباني، سجّل هدف نهائي يورو 2008." },
  { ar: "دافيد فيا", wiki: "David Villa", slug: "villa", clue: "مهاجم إسباني، الهداف التاريخي لمنتخب إسبانيا." },
  { ar: "كارليس بويول", wiki: "Carles Puyol", slug: "puyol", clue: "مدافع إسباني صلب وقائد برشلونة، بطل العالم 2010." },
  { ar: "داني ألفيش", wiki: "Dani Alves", slug: "danialves", clue: "ظهير أيمن برازيلي، من أكثر اللاعبين تتويجًا بالألقاب في التاريخ." },
  { ar: "أندريه شيفتشينكو", wiki: "Andriy Shevchenko", slug: "shevchenko", clue: "مهاجم أوكراني، فاز بالكرة الذهبية 2004 مع ميلان." },
  { ar: "بافيل نيدفيد", wiki: "Pavel Nedvěd", slug: "nedved", clue: "لاعب وسط تشيكي مجتهد، فاز بالكرة الذهبية 2003." },
  { ar: "لويس فيغو", wiki: "Luís Figo", slug: "figo", clue: "جناح برتغالي، اشتهر بانتقاله المثير من برشلونة إلى ريال مدريد عام 2000." },
  { ar: "صامويل إيتو", wiki: "Samuel Eto'o", slug: "etoo", clue: "مهاجم كاميروني هدّاف، فاز بثلاثيات تاريخية مع برشلونة وإنتر." },
  { ar: "ستيفن جيرارد", wiki: "Steven Gerrard", slug: "gerrard", clue: "قائد ليفربول التاريخي، قاد ريمونتادا إسطنبول 2005." },
  { ar: "فرانك لامبارد", wiki: "Frank Lampard", slug: "lampard", clue: "لاعب وسط إنجليزي، الهداف التاريخي لنادي تشيلسي." },
  { ar: "رايان غيغز", wiki: "Ryan Giggs", slug: "giggs", clue: "جناح ويلزي، أمضى مسيرته كلها مع مانشستر يونايتد بأرقام قياسية." },
  { ar: "مايكل أوين", wiki: "Michael Owen", slug: "owen", clue: "مهاجم إنجليزي سريع، فاز بالكرة الذهبية 2001." },
];

export const ALL = [...tier200, ...tier400, ...tier600];
